<Project Sdk="MSTest.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateErrorForMissingTargetingPacks>false</GenerateErrorForMissingTargetingPacks>
    <IsPublishable>false</IsPublishable>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Finance.API\Finance.API.csproj" />
    <ProjectReference Include="..\..\src\Finance.Domain\Finance.Domain.csproj" />
    <ProjectReference Include="..\..\src\Finance.Infrastructure\Finance.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Application\bill-sample.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
