// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AddStayMemberData, AddStayMemberErrors, AddStayMemberResponses, AssignStayCustomerData, AssignStayCustomerErrors, AssignStayCustomerResponses, CancelMyHoldData, CancelMyHoldErrors, CancelMyHoldResponses, CancelStayData, CancelStayErrors, CancelStayResponses, ChangeStayOptionData, ChangeStayOptionErrors, ChangeStayOptionResponses, ConfirmStayData, ConfirmStayErrors, ConfirmStayResponses, CreatePlaceData, CreatePlaceErrors, CreatePlaceResponses, DeletePlaceData, DeletePlaceErrors, DeletePlaceResponses, EndStayData, EndStayErrors, EndStayResponses, GetAvailablePlacesData, GetAvailablePlacesResponses, GetMyStaysData, GetMyStaysErrors, GetMyStaysResponses, GetOpenStaysData, GetOpenStaysErrors, GetOpenStaysResponses, GetPlaceData, GetPlaceErrors, GetPlaceResponses, GetPlaceStayHistoryData, GetPlaceStayHistoryErrors, GetPlaceStayHistoryResponses, GetStayData, GetStayErrors, GetStayHistoryData, GetStayHistoryErrors, GetStayHistoryResponses, GetStayResponses, GetStayStatsData, GetStayStatsErrors, GetStayStatsResponses, HoldPlaceData, HoldPlaceErrors, HoldPlaceResponses, JoinStayData, JoinStayErrors, JoinStayResponses, LeaveStayData, LeaveStayErrors, LeaveStayResponses, ListPlacesData, ListPlacesResponses, RemoveStayMemberData, RemoveStayMemberErrors, RemoveStayMemberResponses, ScanPlaceData, ScanPlaceErrors, ScanPlaceResponses, SetPlaceActiveData, SetPlaceActiveErrors, SetPlaceActiveResponses, SetPlaceStatusData, SetPlaceStatusErrors, SetPlaceStatusResponses, SetPlaceTariffData, SetPlaceTariffErrors, SetPlaceTariffResponses, StartStayData, StartStayErrors, StartStayResponses, StartWalkInData, StartWalkInErrors, StartWalkInResponses, UpdatePlaceData, UpdatePlaceErrors, UpdatePlaceResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List places
 *
 * Every place of the branch with its status; narrow by kind or to timed places
 */
export const listPlaces = <ThrowOnError extends boolean = false>(options?: Options<ListPlacesData, ThrowOnError>): RequestResult<ListPlacesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListPlacesResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/places',
    ...options
});

/**
 * Create a place (Admin)
 */
export const createPlace = <ThrowOnError extends boolean = false>(options: Options<CreatePlaceData, ThrowOnError>): RequestResult<CreatePlaceResponses, CreatePlaceErrors, ThrowOnError> => (options.client ?? client).post<CreatePlaceResponses, CreatePlaceErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/places',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Places a customer can book now
 */
export const getAvailablePlaces = <ThrowOnError extends boolean = false>(options?: Options<GetAvailablePlacesData, ThrowOnError>): RequestResult<GetAvailablePlacesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetAvailablePlacesResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/places/available',
    ...options
});

/**
 * Delete a place (Admin)
 *
 * Its printed QR stops working — prefer deactivating. Refused while a stay is held or running there.
 */
export const deletePlace = <ThrowOnError extends boolean = false>(options: Options<DeletePlaceData, ThrowOnError>): RequestResult<DeletePlaceResponses, DeletePlaceErrors, ThrowOnError> => (options.client ?? client).delete<DeletePlaceResponses, DeletePlaceErrors, ThrowOnError>({ url: '/api/places/{id}', ...options });

/**
 * Get a place
 *
 * What a scanned place QR resolves to
 */
export const getPlace = <ThrowOnError extends boolean = false>(options: Options<GetPlaceData, ThrowOnError>): RequestResult<GetPlaceResponses, GetPlaceErrors, ThrowOnError> => (options.client ?? client).get<GetPlaceResponses, GetPlaceErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/places/{id}',
    ...options
});

/**
 * Rename a place or change its description (Admin)
 */
export const updatePlace = <ThrowOnError extends boolean = false>(options: Options<UpdatePlaceData, ThrowOnError>): RequestResult<UpdatePlaceResponses, UpdatePlaceErrors, ThrowOnError> => (options.client ?? client).put<UpdatePlaceResponses, UpdatePlaceErrors, ThrowOnError>({
    url: '/api/places/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Give a place a tariff, change it, or take it away (Admin)
 *
 * A place with a tariff is timed and can be reserved; without one it only takes orders. Refused while a stay runs there.
 */
export const setPlaceTariff = <ThrowOnError extends boolean = false>(options: Options<SetPlaceTariffData, ThrowOnError>): RequestResult<SetPlaceTariffResponses, SetPlaceTariffErrors, ThrowOnError> => (options.client ?? client).put<SetPlaceTariffResponses, SetPlaceTariffErrors, ThrowOnError>({
    url: '/api/places/{id}/tariff',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Activate or deactivate a place (Admin)
 *
 * Deactivating keeps the place and its printed QR but stops customers ordering to it or holding it
 */
export const setPlaceActive = <ThrowOnError extends boolean = false>(options: Options<SetPlaceActiveData, ThrowOnError>): RequestResult<SetPlaceActiveResponses, SetPlaceActiveErrors, ThrowOnError> => (options.client ?? client).put<SetPlaceActiveResponses, SetPlaceActiveErrors, ThrowOnError>({
    url: '/api/places/{id}/active',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Set a place's physical status (Admin)
 */
export const setPlaceStatus = <ThrowOnError extends boolean = false>(options: Options<SetPlaceStatusData, ThrowOnError>): RequestResult<SetPlaceStatusResponses, SetPlaceStatusErrors, ThrowOnError> => (options.client ?? client).put<SetPlaceStatusResponses, SetPlaceStatusErrors, ThrowOnError>({ url: '/api/places/{id}/status', ...options });

/**
 * What this customer sees after scanning the place's QR
 */
export const scanPlace = <ThrowOnError extends boolean = false>(options: Options<ScanPlaceData, ThrowOnError>): RequestResult<ScanPlaceResponses, ScanPlaceErrors, ThrowOnError> => (options.client ?? client).get<ScanPlaceResponses, ScanPlaceErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/places/{id}/scan',
    ...options
});

/**
 * Hold a timed place
 *
 * The customer has 10 minutes to arrive. With startOnConfirm the clock starts the moment the till confirms.
 */
export const holdPlace = <ThrowOnError extends boolean = false>(options: Options<HoldPlaceData, ThrowOnError>): RequestResult<HoldPlaceResponses, HoldPlaceErrors, ThrowOnError> => (options.client ?? client).post<HoldPlaceResponses, HoldPlaceErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/places/{id}/hold',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Start the clock for a party that walked in (staff)
 */
export const startWalkIn = <ThrowOnError extends boolean = false>(options: Options<StartWalkInData, ThrowOnError>): RequestResult<StartWalkInResponses, StartWalkInErrors, ThrowOnError> => (options.client ?? client).post<StartWalkInResponses, StartWalkInErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/places/{id}/walk-in',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Join the stay running at a place (QR scan)
 */
export const joinStay = <ThrowOnError extends boolean = false>(options: Options<JoinStayData, ThrowOnError>): RequestResult<JoinStayResponses, JoinStayErrors, ThrowOnError> => (options.client ?? client).post<JoinStayResponses, JoinStayErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/places/{id}/join',
    ...options
});

/**
 * Ended and cancelled stays at a place (Admin)
 */
export const getPlaceStayHistory = <ThrowOnError extends boolean = false>(options: Options<GetPlaceStayHistoryData, ThrowOnError>): RequestResult<GetPlaceStayHistoryResponses, GetPlaceStayHistoryErrors, ThrowOnError> => (options.client ?? client).get<GetPlaceStayHistoryResponses, GetPlaceStayHistoryErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/places/{id}/stays',
    ...options
});

/**
 * The signed-in customer's stays, newest first
 */
export const getMyStays = <ThrowOnError extends boolean = false>(options?: Options<GetMyStaysData, ThrowOnError>): RequestResult<GetMyStaysResponses, GetMyStaysErrors, ThrowOnError> => (options?.client ?? client).get<GetMyStaysResponses, GetMyStaysErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/stays/my',
    ...options
});

/**
 * Held and running stays of the branch (staff)
 */
export const getOpenStays = <ThrowOnError extends boolean = false>(options?: Options<GetOpenStaysData, ThrowOnError>): RequestResult<GetOpenStaysResponses, GetOpenStaysErrors, ThrowOnError> => (options?.client ?? client).get<GetOpenStaysResponses, GetOpenStaysErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/stays/open',
    ...options
});

/**
 * Ended and cancelled stays across the branch, paged (Admin)
 */
export const getStayHistory = <ThrowOnError extends boolean = false>(options?: Options<GetStayHistoryData, ThrowOnError>): RequestResult<GetStayHistoryResponses, GetStayHistoryErrors, ThrowOnError> => (options?.client ?? client).get<GetStayHistoryResponses, GetStayHistoryErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/stays/history',
    ...options
});

/**
 * Per-day and per-place hours, stays and revenue (Admin)
 */
export const getStayStats = <ThrowOnError extends boolean = false>(options: Options<GetStayStatsData, ThrowOnError>): RequestResult<GetStayStatsResponses, GetStayStatsErrors, ThrowOnError> => (options.client ?? client).get<GetStayStatsResponses, GetStayStatsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/stays/stats',
    ...options
});

/**
 * Get a stay
 */
export const getStay = <ThrowOnError extends boolean = false>(options: Options<GetStayData, ThrowOnError>): RequestResult<GetStayResponses, GetStayErrors, ThrowOnError> => (options.client ?? client).get<GetStayResponses, GetStayErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/stays/{id}',
    ...options
});

/**
 * The customer arrived (staff)
 *
 * Starts the clock when the hold asked for start-on-confirm; otherwise the hold waits for Start
 */
export const confirmStay = <ThrowOnError extends boolean = false>(options: Options<ConfirmStayData, ThrowOnError>): RequestResult<ConfirmStayResponses, ConfirmStayErrors, ThrowOnError> => (options.client ?? client).post<ConfirmStayResponses, ConfirmStayErrors, ThrowOnError>({
    url: '/api/stays/{id}/confirm',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Start the clock on a held stay (staff)
 */
export const startStay = <ThrowOnError extends boolean = false>(options: Options<StartStayData, ThrowOnError>): RequestResult<StartStayResponses, StartStayErrors, ThrowOnError> => (options.client ?? client).post<StartStayResponses, StartStayErrors, ThrowOnError>({
    url: '/api/stays/{id}/start',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Stop the clock and settle the cost (staff)
 */
export const endStay = <ThrowOnError extends boolean = false>(options: Options<EndStayData, ThrowOnError>): RequestResult<EndStayResponses, EndStayErrors, ThrowOnError> => (options.client ?? client).post<EndStayResponses, EndStayErrors, ThrowOnError>({ url: '/api/stays/{id}/end', ...options });

/**
 * Give up a hold or cut a running stay short (staff)
 */
export const cancelStay = <ThrowOnError extends boolean = false>(options: Options<CancelStayData, ThrowOnError>): RequestResult<CancelStayResponses, CancelStayErrors, ThrowOnError> => (options.client ?? client).post<CancelStayResponses, CancelStayErrors, ThrowOnError>({ url: '/api/stays/{id}/cancel', ...options });

/**
 * Switch a running stay to another rate option (staff)
 */
export const changeStayOption = <ThrowOnError extends boolean = false>(options: Options<ChangeStayOptionData, ThrowOnError>): RequestResult<ChangeStayOptionResponses, ChangeStayOptionErrors, ThrowOnError> => (options.client ?? client).put<ChangeStayOptionResponses, ChangeStayOptionErrors, ThrowOnError>({
    url: '/api/stays/{id}/option',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Give an unclaimed walk-in its owner (staff)
 */
export const assignStayCustomer = <ThrowOnError extends boolean = false>(options: Options<AssignStayCustomerData, ThrowOnError>): RequestResult<AssignStayCustomerResponses, AssignStayCustomerErrors, ThrowOnError> => (options.client ?? client).post<AssignStayCustomerResponses, AssignStayCustomerErrors, ThrowOnError>({
    url: '/api/stays/{id}/assign-customer',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Name someone in the party (staff)
 *
 * Allowed on a running or ended stay: after the clock stops this still names who was there, so their share can go on their tab at settle
 */
export const addStayMember = <ThrowOnError extends boolean = false>(options: Options<AddStayMemberData, ThrowOnError>): RequestResult<AddStayMemberResponses, AddStayMemberErrors, ThrowOnError> => (options.client ?? client).post<AddStayMemberResponses, AddStayMemberErrors, ThrowOnError>({
    url: '/api/stays/{id}/members',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Remove a member (not the owner) from a running stay (staff)
 */
export const removeStayMember = <ThrowOnError extends boolean = false>(options: Options<RemoveStayMemberData, ThrowOnError>): RequestResult<RemoveStayMemberResponses, RemoveStayMemberErrors, ThrowOnError> => (options.client ?? client).delete<RemoveStayMemberResponses, RemoveStayMemberErrors, ThrowOnError>({ url: '/api/stays/{id}/members/{customerId}', ...options });

/**
 * Leave a stay you joined (not as its owner)
 */
export const leaveStay = <ThrowOnError extends boolean = false>(options: Options<LeaveStayData, ThrowOnError>): RequestResult<LeaveStayResponses, LeaveStayErrors, ThrowOnError> => (options.client ?? client).post<LeaveStayResponses, LeaveStayErrors, ThrowOnError>({ url: '/api/stays/{id}/leave', ...options });

/**
 * Give up your own hold before it starts
 */
export const cancelMyHold = <ThrowOnError extends boolean = false>(options: Options<CancelMyHoldData, ThrowOnError>): RequestResult<CancelMyHoldResponses, CancelMyHoldErrors, ThrowOnError> => (options.client ?? client).post<CancelMyHoldResponses, CancelMyHoldErrors, ThrowOnError>({ url: '/api/stays/my/{id}/cancel', ...options });
