// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

export type AssignAdminRequest = {
    adminUserId: string;
};

export type BranchResponse = {
    id: number | string;
    name: LocalizedText;
    address: null | LocalizedText;
    phone: null | string;
    isActive: boolean;
    displayOrder: number | string;
    dayStartTime: string;
    dayEndTime: string;
    isOrderingEnabled: boolean;
    isReservationsEnabled: boolean;
};

export type CreateBranchRequest = {
    name: LocalizedText;
    address: null | LocalizedText;
    phone: null | string;
    displayOrder?: number | string;
    dayStartTime?: null | string;
    dayEndTime?: null | string;
    isOrderingEnabled?: boolean;
    isReservationsEnabled?: boolean;
};

export type LocalizedText = {
    en?: string;
    ar?: null | string;
};

export type UpdateBranchRequest = {
    name: LocalizedText;
    address: null | LocalizedText;
    phone: null | string;
    isActive: boolean;
    displayOrder: number | string;
    dayStartTime?: null | string;
    dayEndTime?: null | string;
    isOrderingEnabled?: null | boolean;
    isReservationsEnabled?: null | boolean;
};

export type UpdateBranchSettingsRequest = {
    isOrderingEnabled?: null | boolean;
    isReservationsEnabled?: null | boolean;
};

export type GetBranchesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/branches';
};

export type GetBranchesResponses = {
    /**
     * OK
     */
    200: Array<BranchResponse>;
};

export type GetBranchesResponse = GetBranchesResponses[keyof GetBranchesResponses];

export type CreateBranchData = {
    body: CreateBranchRequest;
    path?: never;
    query?: never;
    url: '/api/branches';
};

export type CreateBranchErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type CreateBranchResponses = {
    /**
     * Created
     */
    201: BranchResponse;
};

export type CreateBranchResponse = CreateBranchResponses[keyof CreateBranchResponses];

export type GetAllBranchesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/branches/all';
};

export type GetAllBranchesErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetAllBranchesResponses = {
    /**
     * OK
     */
    200: Array<BranchResponse>;
};

export type GetAllBranchesResponse = GetAllBranchesResponses[keyof GetAllBranchesResponses];

export type UpdateBranchData = {
    body: UpdateBranchRequest;
    path: {
        /**
         * The branch ID
         */
        id: number;
    };
    query?: never;
    url: '/api/branches/{id}';
};

export type UpdateBranchErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type UpdateBranchResponses = {
    /**
     * OK
     */
    200: BranchResponse;
};

export type UpdateBranchResponse = UpdateBranchResponses[keyof UpdateBranchResponses];

export type UpdateBranchSettingsData = {
    body: UpdateBranchSettingsRequest;
    path: {
        /**
         * The branch ID
         */
        id: number;
    };
    query?: never;
    url: '/api/branches/{id}/settings';
};

export type UpdateBranchSettingsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type UpdateBranchSettingsResponses = {
    /**
     * OK
     */
    200: BranchResponse;
};

export type UpdateBranchSettingsResponse = UpdateBranchSettingsResponses[keyof UpdateBranchSettingsResponses];

export type GetBranchesByAdminData = {
    body?: never;
    path: {
        /**
         * The admin user ID
         */
        adminUserId: string;
    };
    query?: never;
    url: '/api/branches/admin/{adminUserId}';
};

export type GetBranchesByAdminErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetBranchesByAdminResponses = {
    /**
     * OK
     */
    200: Array<BranchResponse>;
};

export type GetBranchesByAdminResponse = GetBranchesByAdminResponses[keyof GetBranchesByAdminResponses];

export type AssignAdminData = {
    body: AssignAdminRequest;
    path: {
        /**
         * The branch ID
         */
        id: number;
    };
    query?: never;
    url: '/api/branches/{id}/admins';
};

export type AssignAdminErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Conflict
     */
    409: string;
};

export type AssignAdminError = AssignAdminErrors[keyof AssignAdminErrors];

export type AssignAdminResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type RemoveAdminData = {
    body?: never;
    path: {
        /**
         * The branch ID
         */
        id: number;
        /**
         * The admin user ID
         */
        userId: string;
    };
    query?: never;
    url: '/api/branches/{id}/admins/{userId}';
};

export type RemoveAdminErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type RemoveAdminResponses = {
    /**
     * No Content
     */
    204: void;
};

export type RemoveAdminResponse = RemoveAdminResponses[keyof RemoveAdminResponses];
