#nullable enable
using System.ComponentModel.DataAnnotations;

namespace Ninja.Ordering.Domain.AggregatesModel.OrderAggregate;

/// <summary>
/// Order aggregate root.
/// Simple flow: Submitted -> Confirmed (goes to POS) or Cancelled
/// </summary>
public class Order
    : Entity, IAggregateRoot
{
    public DateTime OrderDate { get; private set; }

    public int? BuyerId { get; private set; }

    public Buyer? Buyer { get; }

    public OrderStatus OrderStatus { get; private set; }

    public string? Description { get; private set; }

    /// <summary>
    /// The Spaces place the order goes to — a room, a table, a station.
    /// Null for an order-ahead or a counter sale.
    /// </summary>
    public int? PlaceId { get; private set; }

    /// <summary>"Room", "Table" or "Station", as Spaces names it.</summary>
    public string? PlaceKind { get; private set; }

    /// <summary>Place name snapshot at order time - localized.</summary>
    public LocalizedText? PlaceName { get; private set; }

    /// <summary>Where the order goes, as one value: the place and, when its clock runs, the stay.</summary>
    public OrderDestination Destination => new(PlaceId, PlaceKind, PlaceName, SessionId);

    /// <summary>
    /// The Spaces stay this order was placed into, when the customer ordered
    /// from a timed place with its clock running. <see cref="PlaceName"/> is
    /// for display; this id is what lets a bill be assembled per stay.
    /// </summary>
    public int? SessionId { get; private set; }

    /// <summary>
    /// Who put this order into the system — a signed-in customer, a guest at
    /// a table, or staff at the counter POS.
    /// </summary>
    public OrderSource Source { get; private set; }

    /// <summary>
    /// The Sales ticket this order must land on, when the cashier rang it up
    /// against an already-open bill. Ordering never reads it — it only carries
    /// it to Sales, which otherwise has to infer the bill from the session or
    /// table and cannot name a counter tab at all.
    /// </summary>
    public int? TicketId { get; private set; }

    /// <summary>
    /// When the till settled the bill this order was on — projected from
    /// Sales' TicketSettled event, never set here. Null until then: an order
    /// is confirmed long before it is paid.
    /// </summary>
    public DateTime? PaidAt { get; private set; }

    /// <summary>The receipt that covered the order; the same number the tab and the till show.</summary>
    public int? ReceiptNumber { get; private set; }

    /// <summary>"Cash", "Card", "InstaPay", "Account" (the customer's tab) or "Mixed".</summary>
    public string? PaidWith { get; private set; }

    /// <summary>What credit notes have given back against this order, capped at its total.</summary>
    public decimal RefundedAmount { get; private set; }

    /// <summary>
    /// When an owner voided the open bill this order was on — it will never
    /// be paid. Projected from Sales' TicketVoided event.
    /// </summary>
    public DateTime? VoidedAt { get; private set; }

    public bool IsPaid => PaidAt != null;

    /// <summary>Whether the order says where it is going: a place was named.</summary>
    public bool HasDestination => PlaceId.HasValue;

    /// <summary>
    /// Special instructions or notes from the customer
    /// </summary>
    public string? CustomerNote { get; private set; }

    /// <summary>
    /// Loyalty points to redeem for this order (redeemed when order is confirmed)
    /// </summary>
    public int PointsToRedeem { get; private set; }

    /// <summary>
    /// Loyalty discount in currency, computed by the Loyalty API at order time
    /// </summary>
    public double LoyaltyDiscount { get; private set; }

    /// <summary>
    /// The promo code typed at checkout: as requested while the items are
    /// being checked, then as Catalog redeemed it — or null once Catalog said
    /// it does not apply.
    /// </summary>
    public string? PromoCode { get; private set; }

    /// <summary>What the promo code took off, in currency; set when the items check out.</summary>
    public decimal PromoDiscount { get; private set; }

    /// <summary>
    /// The branch this order was placed at
    /// </summary>
    public int BranchId { get; private set; }

    /// <summary>
    /// Identifies the device a guest ordered from, so they can see their own
    /// orders back without an account. Generated by the client and kept only
    /// in that browser — treat it as the secret it is, never as a public id.
    /// Null on orders placed by a signed-in customer.
    /// </summary>
    public string? GuestId { get; private set; }

    /// <summary>
    /// Name a guest left at checkout. Signed-in orders carry the name on the
    /// <see cref="Buyer"/> instead.
    /// </summary>
    public string? GuestName { get; private set; }

    /// <summary>
    /// Phone number a guest left at checkout, so staff can reach them. This is
    /// the only contact route for a guest order — there is no account behind it.
    /// </summary>
    public string? GuestPhone { get; private set; }

    /// <summary>
    /// A guest order has no <see cref="Buyer"/>: nobody signed in to place it.
    /// </summary>
    public bool IsGuestOrder => GuestId != null;

    /// <summary>
    /// What the delivery platform said about an order it dispatched here;
    /// null on every order placed in the business's own apps or at its till.
    /// </summary>
    public PlatformOrder? Platform { get; private set; }

    /// <summary>
    /// The business's own delivery of the order — where it goes and who takes
    /// it; null on every order eaten in, collected, or delivered by a platform.
    /// </summary>
    public Delivery? Delivery { get; private set; }

    public bool IsDelivery => Delivery != null;

    // Draft orders have this set to true
#pragma warning disable CS0414
    private bool _isDraft;
#pragma warning restore CS0414

    // Using a private collection field for DDD Aggregate's encapsulation
    private readonly List<OrderItem> _orderItems;

    public IReadOnlyCollection<OrderItem> OrderItems => _orderItems.AsReadOnly();

    private readonly List<OrderStationPart> _stationParts;

    /// <summary>
    /// The order split by kitchen station, one part per station that makes
    /// any of its lines. Set when the order reaches the kitchen; empty on
    /// orders confirmed before stations, which the kitchen treats as whole.
    /// </summary>
    public IReadOnlyCollection<OrderStationPart> StationParts => _stationParts.AsReadOnly();

    /// <summary>
    /// Order rating (null if not rated yet)
    /// </summary>
    public OrderRating? Rating { get; private set; }

    /// <summary>
    /// Number of reminder notifications sent for this order while pending
    /// </summary>
    public int ReminderCount { get; private set; }

    /// <summary>
    /// When the last reminder notification was sent (null if none sent)
    /// </summary>
    public DateTime? LastReminderSentAt { get; private set; }

    /// <summary>
    /// When staff confirmed the order — the moment it reached the kitchen.
    /// Null on orders confirmed before the kitchen display existed, which is
    /// how the kitchen query leaves history alone.
    /// </summary>
    public DateTime? ConfirmedAt { get; private set; }

    /// <summary>
    /// When the kitchen finished it; null while it is still on the board,
    /// and null again if the kitchen brings it back. With stations, it is
    /// set when the last part on a screen is ready — a printed part never
    /// counts, and an order made only at printers is never marked ready.
    /// Never changes what the order costs.
    /// </summary>
    public DateTime? ReadyAt { get; private set; }

    public bool IsReady => ReadyAt != null;

    /// <summary>
    /// When the stock its confirmation took was given back or written off
    /// (the order cancelled, or its bill voided); null while it stands. Once
    /// only: a cancelled delivery whose bill is then voided releases nothing more.
    /// </summary>
    public DateTime? StockReleasedAt { get; private set; }

    /// <summary>What became of that stock: written off as waste, or back on the shelf.</summary>
    public StockDisposition? StockDisposition { get; private set; }

    /// <summary>
    /// Whether the food was made, as far as Ordering can tell: the kitchen
    /// marked it (or any of its parts) ready, it left with the business's
    /// rider, or a platform's rider collected it. An order made only at
    /// kitchen printers, or served without a kitchen screen, never says so:
    /// the till asks the cashier there.
    /// </summary>
    public bool WasPrepared =>
        IsReady
        || _stationParts.Any(p => p.IsReady)
        || Delivery is { OutAt: not null }
        || Platform is { PickedUpAt: not null };

    public static Order NewDraft()
    {
        var order = new Order
        {
            _isDraft = true
        };
        return order;
    }

    protected Order()
    {
        _orderItems = new List<OrderItem>();
        _stationParts = new List<OrderStationPart>();
        _isDraft = false;
    }

    public Order(string userId, string userName, int branchId, string? customerNote = null, int? buyerId = null, int pointsToRedeem = 0, double loyaltyDiscount = 0, string? guestId = null, string? guestName = null, string? guestPhone = null, OrderSource? source = null, int? sessionId = null, int? ticketId = null, DateTime? placedAt = null, int? placeId = null, string? placeKind = null, LocalizedText? placeName = null, string? promoCode = null, bool guestOrdersAnywhere = false, PlatformOrder? platform = null, Delivery? delivery = null) : this()
    {
        BuyerId = buyerId;
        PromoCode = string.IsNullOrWhiteSpace(promoCode) ? null : promoCode.Trim().ToUpperInvariant();
        OrderStatus = OrderStatus.AwaitingValidation;
        // A replayed offline sale is dated when it was rung up, not when it reached us
        OrderDate = placedAt ?? DateTime.UtcNow;
        SessionId = sessionId;
        TicketId = ticketId;

        // The kind and the name only mean something with the place id
        if (placeId is not null)
        {
            PlaceId = placeId;
            PlaceKind = placeKind;
            PlaceName = placeName;
        }
        CustomerNote = customerNote;
        PointsToRedeem = pointsToRedeem;
        LoyaltyDiscount = loyaltyDiscount;
        BranchId = branchId;
        Description = "Order awaiting item availability validation.";

        // Callers that know better (the POS path) say so; otherwise the
        // identity decides: a signed-in user is a customer, nobody is a guest.
        Source = source ?? (string.IsNullOrWhiteSpace(userId) ? OrderSource.Guest : OrderSource.Customer);

        // No identity behind the order means a guest placed it. The name and
        // phone they left at checkout are then the only way staff can reach
        // them, so the aggregate refuses to exist without both. A counter sale
        // (Source = Pos) is exempt: the cashier standing there is the contact.
        // The till is often given a name for someone with no account — the
        // waiters know the regulars. It identifies nobody and unlocks nothing;
        // it just has to travel, onto the kitchen card and onto the bill line.
        if (Source == OrderSource.Pos)
        {
            GuestName = string.IsNullOrWhiteSpace(guestName) ? null : guestName.Trim();
        }

        // A delivery platform's order has no account and no table here: the
        // platform took the customer's details and runs the delivery. What it
        // sent is kept whole; the name and phone ride the kitchen card and the
        // bill like a walk-in's, for the rider and the counter.
        if (Source == OrderSource.Talabat)
        {
            Platform = platform ?? throw new OrderingDomainException("A Talabat order needs Talabat's details.");
            GuestName = string.IsNullOrWhiteSpace(guestName) ? null : guestName.Trim();
            GuestPhone = string.IsNullOrWhiteSpace(guestPhone) ? null : guestPhone.Trim();
        }

        // The business's own delivery goes to an address, never to a place in
        // the building, and only from its own apps and till
        if (delivery is not null)
        {
            if (Source == OrderSource.Talabat)
                throw new OrderingDomainException("A platform's order is delivered by the platform.");
            if (HasDestination)
                throw new OrderingDomainException("An order goes to a table or room, or is delivered — not both.", DeliveryErrors.PlaceConflict);
            Delivery = delivery;
        }

        if (Source == OrderSource.Guest)
        {
            GuestId = !string.IsNullOrWhiteSpace(guestId)
                ? guestId
                : throw new OrderingDomainException("A guest order needs a guest id.");
            GuestName = !string.IsNullOrWhiteSpace(guestName)
                ? guestName
                : throw new OrderingDomainException("A guest order needs a name.");
            GuestPhone = !string.IsNullOrWhiteSpace(guestPhone)
                ? guestPhone
                : throw new OrderingDomainException("A guest order needs a phone number.");

            // Where they are sitting is the only thing anchoring a guest order
            // to someone actually in the building. Without it there is nobody
            // to carry it to, and ordering ahead — which is what a destination
            // less order really is — is reserved for account holders who can
            // be held to it. In practice this always means a table: a room
            // session belongs to an account. A business that takes guests' orders
            // from anywhere lets one go without: it is collected, and the
            // phone above is how the counter finds whoever ordered it.
            // A delivery is anchored too: to an address, with a phone to call at the door.
            if (!HasDestination && Delivery is null && !guestOrdersAnywhere)
            {
                throw new OrderingDomainException("A guest order needs a table or room to be delivered to.");
            }
        }

        // Add the OrderStartedDomainEvent to the domain events collection
        AddOrderStartedDomainEvent(userId, userName);
    }

    /// <summary>
    /// Add item to the order
    /// </summary>
    public void AddOrderItem(int productId, LocalizedText productName, decimal unitPrice, decimal discount, string? pictureUrl, int units = 1, LocalizedText? customizationsDescription = null, string? specialInstructions = null, IEnumerable<int>? optionIds = null, SuggestionSource suggestion = SuggestionSource.None)
    {
        // When items have customizations, treat them as unique items (don't
        // combine); nor is a suggested line folded into one picked by hand, or
        // what the suggestion sold would be lost
        var existingOrderForProduct = customizationsDescription == null
            ? _orderItems.SingleOrDefault(o => o.ProductId == productId && o.CustomizationsDescription == null && o.Suggestion == suggestion)
            : null;

        if (existingOrderForProduct != null)
        {
            // If previous line exists, modify it with higher discount and units
            if (discount > existingOrderForProduct.Discount)
            {
                existingOrderForProduct.SetNewDiscount(discount);
            }

            existingOrderForProduct.AddUnits(units);
        }
        else
        {
            // Add validated new order item
            var orderItem = new OrderItem(productId, productName, unitPrice, discount, pictureUrl, units, customizationsDescription, specialInstructions, optionIds, suggestion);
            _orderItems.Add(orderItem);
        }
    }

    /// <summary>
    /// Set the buyer after validation
    /// </summary>
    public void SetBuyerId(int buyerId)
    {
        BuyerId = buyerId;
    }

    /// <summary>
    /// Name the customer after the fact — the cashier rang the sale up and
    /// only then remembered whose it was, or named the wrong regular.
    /// Allowed until the order is cancelled. A bare name identifies nobody,
    /// so an account (or a better name) may replace it. An account may be
    /// replaced by another: the points it earned at confirmation follow the
    /// order, which is why the event names the account losing them as well
    /// as the one gaining them. It cannot be swapped for itself, nor dropped
    /// back to a bare name. The name travels the way the POS constructor's
    /// does — onto the kitchen card and the bill line; the account, when
    /// there is one, becomes the <see cref="Buyer"/>.
    /// </summary>
    /// <param name="previousBuyerIdentityGuid">
    /// The identity behind the current <see cref="BuyerId"/>, looked up by
    /// the caller: the aggregate holds only the row id, and the event goes
    /// out before anything is saved.
    /// </param>
    public void AssignCustomer(string customerName, Buyer? buyer = null, string? previousBuyerIdentityGuid = null)
    {
        if (OrderStatus == OrderStatus.Cancelled)
        {
            throw new OrderingDomainException("A cancelled order cannot be assigned a customer.");
        }

        if (BuyerId is not null)
        {
            if (buyer is null)
            {
                throw new OrderingDomainException("This order belongs to a customer account — it can move to another account, not to a bare name.");
            }

            if (buyer.Id == BuyerId || buyer.IdentityGuid == previousBuyerIdentityGuid)
            {
                throw new OrderingDomainException("This order already belongs to this customer.");
            }
        }

        if (string.IsNullOrWhiteSpace(customerName))
        {
            throw new OrderingDomainException("A customer needs a name.");
        }

        // Whose it was only matters if it was anyone's
        var previous = BuyerId is null ? null : previousBuyerIdentityGuid;

        GuestName = customerName.Trim();
        BuyerId = buyer?.Id;

        AddDomainEvent(new OrderCustomerAssignedDomainEvent(this, buyer?.IdentityGuid, previous));
    }

    /// <summary>
    /// Catalog checked the order and every line can be sold: submitted for
    /// staff. Catalog answers the rest in the same breath — each line's price
    /// by line id (the menu's word, not the app's; null leaves the lines as
    /// they came, for a Talabat order or an answer without prices), the promo
    /// code as redeemed and its worth or nothing when it did not apply, and
    /// each product's menu category, which later sends a line to its station.
    /// The loyalty discount is worked out again on the prices that stand.
    /// </summary>
    public void SetValidatedStatus(
        IReadOnlyDictionary<int, decimal>? prices = null,
        string? promoCode = null,
        decimal promoDiscount = 0,
        IReadOnlyDictionary<int, int>? categories = null)
    {
        if (OrderStatus != OrderStatus.AwaitingValidation)
        {
            throw new OrderingDomainException($"Cannot validate the order from status {OrderStatus}. Order must be in AwaitingValidation status.");
        }

        if (prices is not null)
        {
            foreach (var item in _orderItems)
            {
                if (prices.TryGetValue(item.Id, out var price))
                    item.SetUnitPrice(price);
            }

            LoyaltyDiscount = GetLoyaltyDiscountFor(PointsToRedeem, GetItemsTotal());
        }

        OrderStatus = OrderStatus.Submitted;
        Description = "Items validated. Order ready for confirmation.";
        // A reminder that it was stuck on the check does not count against staff
        ReminderCount = 0;
        LastReminderSentAt = null;
        PromoCode = promoDiscount > 0 ? promoCode : null;
        PromoDiscount = Math.Clamp(promoDiscount, 0, Math.Max(0, GetItemsTotal()));

        if (categories is not null)
        {
            foreach (var item in _orderItems)
            {
                item.SetCategory(categories.TryGetValue(item.ProductId, out var categoryId) ? categoryId : null);
            }
        }

        AddDomainEvent(new OrderStatusChangedToSubmittedDomainEvent(Id));
    }

    /// <summary>
    /// A delivery held to the branch's minimum at the menu's prices, not the
    /// app's: Catalog lowered a price and the order no longer comes to it, so
    /// it is cancelled as a failed check would be.
    /// </summary>
    public void SetBelowDeliveryMinimum(decimal minimum)
    {
        if (OrderStatus != OrderStatus.AwaitingValidation)
        {
            throw new OrderingDomainException($"Cannot fail validation from status {OrderStatus}. Order must be in AwaitingValidation status.");
        }

        OrderStatus = OrderStatus.Cancelled;
        Description = $"Order cancelled - delivery needs an order of at least {minimum:0.##} at the menu's prices.";
        AddDomainEvent(new OrderCancelledDomainEvent(this));
    }

    /// <summary>What the items would come to at <paramref name="prices"/> (by line id); the lines' own where none is given.</summary>
    public decimal GetItemsTotalAt(IReadOnlyDictionary<int, decimal>? prices) =>
        _orderItems.Sum(o => o.Units * (prices is not null && prices.TryGetValue(o.Id, out var price) ? price : o.UnitPrice) - o.Discount);

    /// <summary>
    /// Catalog turned lines down: the order is cancelled, saying why — the
    /// menu asks more than the app showed (<see cref="ValidationFailure.PriceChanged"/>),
    /// or items or options cannot be had. A Talabat order is refused to
    /// Talabat as unavailable either way; its prices are never the menu's.
    /// </summary>
    public void SetValidationFailedStatus(IReadOnlyCollection<ValidationFailure> failures)
    {
        if (OrderStatus != OrderStatus.AwaitingValidation)
        {
            throw new OrderingDomainException($"Cannot fail validation from status {OrderStatus}. Order must be in AwaitingValidation status.");
        }

        var repriced = failures.Where(f => f.Reason == ValidationFailure.PriceChanged).Select(f => f.ProductId).Distinct().ToList();
        var unavailable = failures.Where(f => f.Reason != ValidationFailure.PriceChanged).Select(f => f.ProductId).Distinct().ToList();

        OrderStatus = OrderStatus.Cancelled;
        Description = unavailable.Count > 0
            ? $"Order cancelled - some items are not available: {string.Join(", ", unavailable)}"
            : $"Order cancelled - prices changed since the order was made: {string.Join(", ", repriced)}";
        Platform?.Reject(PlatformRejectReasons.ItemUnavailable);
        AddDomainEvent(new OrderCancelledDomainEvent(this));
    }

    /// <summary>
    /// Confirm the order (admin action) - moves to POS, and to the kitchen:
    /// with the branch's <paramref name="routing"/>, every line goes to the
    /// station that makes it and the order is split into one part per station.
    /// </summary>
    public void SetConfirmedStatus(KitchenRouting? routing = null)
    {
        if (OrderStatus != OrderStatus.Submitted)
        {
            throw new OrderingDomainException($"Cannot confirm order from status {OrderStatus}. Order must be in Submitted status.");
        }

        AddDomainEvent(new OrderStatusChangedToConfirmedDomainEvent(Id, _orderItems));
        OrderStatus = OrderStatus.Confirmed;
        ConfirmedAt = DateTime.UtcNow;
        Description = "Order confirmed and sent to POS.";

        if (routing is not null)
        {
            RouteToStations(routing);
        }
    }

    private void RouteToStations(KitchenRouting routing)
    {
        foreach (var item in _orderItems)
        {
            var station = routing.StationFor(item.CategoryId);
            item.RouteTo(station.Id);

            if (_stationParts.All(p => p.StationId != station.Id))
            {
                _stationParts.Add(new OrderStationPart(station.Id, station.Name, station.ShowsOnScreen, station.PrintsTickets));
            }
        }

        if (_stationParts.Any(p => p.PrintsTickets))
        {
            AddDomainEvent(new OrderSentToKitchenPrintersDomainEvent(
                Id, BranchId, _stationParts.Where(p => p.PrintsTickets).Select(p => p.StationId).ToList()));
        }
    }

    /// <summary>
    /// Mark the whole order ready in the kitchen, or bring a ready one back
    /// to the board (a card bumped too early, or a remake) — from the pass,
    /// where every part on a screen goes with it. The same state twice is a
    /// no-op, so two screens tapping the same card do not race each other
    /// into an error. Only a confirmed order is in the kitchen at all.
    /// </summary>
    public void SetReady(bool ready)
    {
        EnsureInKitchen();

        if (_stationParts.Count == 0)
        {
            // Confirmed before stations: the order is one card
            if (ready != IsReady)
            {
                ReadyAt = ready ? DateTime.UtcNow : null;
                AddDomainEvent(new OrderReadyChangedDomainEvent(Id, BranchId, ready));
            }
            return;
        }

        var onScreen = _stationParts.Where(p => p.ShowsOnScreen).ToList();
        if (onScreen.Count == 0)
        {
            throw new OrderingDomainException("This order only went to kitchen printers; nobody marks it ready.");
        }

        var now = DateTime.UtcNow;
        foreach (var part in onScreen)
        {
            part.SetReady(ready, now);
        }

        SyncReady(now);
    }

    /// <summary>
    /// One station's screen marked its part done, or brought it back. The
    /// order is ready once every part on a screen is; bringing one back
    /// takes the whole order back. The same state twice is a no-op.
    /// </summary>
    public void SetStationReady(int stationId, bool ready)
    {
        EnsureInKitchen();

        var part = _stationParts.SingleOrDefault(p => p.StationId == stationId)
            ?? throw new OrderingDomainException($"Nothing on order {Id} is made at station {stationId}.");

        if (!part.ShowsOnScreen)
        {
            throw new OrderingDomainException("That station prints its part; nobody marks it ready.");
        }

        var now = DateTime.UtcNow;
        part.SetReady(ready, now);
        SyncReady(now);
    }

    private void SyncReady(DateTime now)
    {
        var ready = _stationParts.Where(p => p.ShowsOnScreen).All(p => p.IsReady);
        if (ready == IsReady)
        {
            return;
        }

        ReadyAt = ready ? now : null;
        AddDomainEvent(new OrderReadyChangedDomainEvent(Id, BranchId, ready));
    }

    private void EnsureInKitchen()
    {
        if (OrderStatus != OrderStatus.Confirmed)
        {
            throw new OrderingDomainException($"Cannot change kitchen state from status {OrderStatus}. Only a confirmed order is in the kitchen.");
        }
    }

    /// <summary>
    /// Cancel the order (can cancel submitted or awaiting validation orders).
    /// A delivery platform's order is turned down on the platform too, for
    /// <paramref name="platformReason"/> — the kitchen being too busy when
    /// staff give none.
    /// </summary>
    /// <param name="stockDisposition">
    /// For a confirmed delivery that came back: what becomes of its food, as
    /// the cashier said; left out, it is waste once made (<see cref="WasPrepared"/>).
    /// </param>
    public void SetCancelledStatus(string? platformReason = null, StockDisposition? stockDisposition = null)
    {
        // A confirmed delivery that could not be handed over, or came back,
        // is cancelled by the till too, as long as no cash came in for it
        var deliveryCameBack = OrderStatus == OrderStatus.Confirmed
            && Delivery is { Stage: DeliveryStage.Failed or DeliveryStage.Returned, CashHandedInAt: null };

        if (OrderStatus != OrderStatus.Submitted && OrderStatus != OrderStatus.AwaitingValidation && !deliveryCameBack)
        {
            throw new OrderingDomainException($"Cannot cancel order from status {OrderStatus}. Only submitted or awaiting validation orders, or a delivery that came back, can be cancelled.");
        }

        OrderStatus = OrderStatus.Cancelled;
        Description = "The order was cancelled.";
        Platform?.Reject(string.IsNullOrWhiteSpace(platformReason) ? PlatformRejectReasons.TooBusy : platformReason);
        AddDomainEvent(new OrderCancelledDomainEvent(this));
        // Only a confirmed order took stock; one cancelled before never did
        ReleaseStock(stockDisposition, StockReleaseReason.Cancelled, DateTime.UtcNow);
    }

    /// <summary>
    /// The stock this order's confirmation took is let go, once: as waste when
    /// the food was made, back to the shelf when it never was, or as the
    /// cashier said. Nothing for an order never confirmed (it took nothing)
    /// or already released.
    /// </summary>
    private void ReleaseStock(StockDisposition? chosen, StockReleaseReason reason, DateTime at)
    {
        if (ConfirmedAt is null || StockReleasedAt is not null)
        {
            return;
        }

        var disposition = chosen ?? (WasPrepared ? AggregatesModel.OrderAggregate.StockDisposition.Waste : AggregatesModel.OrderAggregate.StockDisposition.Restock);
        StockReleasedAt = at;
        StockDisposition = disposition;
        AddDomainEvent(new OrderStockReleasedDomainEvent(Id, BranchId, disposition, reason));
    }

    /// <summary>
    /// The platform cancelled its order: the customer changed their mind, or
    /// nobody here answered it in time. Not yet in the kitchen, it is simply
    /// cancelled — and nothing is reported back, the platform knows. Already
    /// accepted, it stays where it is (in the kitchen, on its bill) with the
    /// cancellation recorded, for the till to deal with. A repeat is a no-op.
    /// </summary>
    public void CancelByPlatform(DateTime at)
    {
        if (Platform is null)
        {
            throw new OrderingDomainException("Only a delivery platform's order can be cancelled by the platform.");
        }

        if (Platform.CancelledAt is not null)
        {
            return;
        }

        Platform.MarkCancelled(at);

        if (OrderStatus is OrderStatus.Submitted or OrderStatus.AwaitingValidation)
        {
            OrderStatus = OrderStatus.Cancelled;
            Description = $"{Platform.Name} cancelled the order.";
            AddDomainEvent(new OrderCancelledDomainEvent(this));
        }
        else if (OrderStatus == OrderStatus.Confirmed)
        {
            Description = $"{Platform.Name} cancelled the order after it was accepted.";
            // Its stock went at acceptance: waste once made, back otherwise
            ReleaseStock(null, StockReleaseReason.PlatformCancelled, at);
        }
    }

    /// <summary>The platform's rider collected it. A repeat is a no-op.</summary>
    public void MarkPickedUpByPlatform(DateTime at)
    {
        if (Platform is null)
        {
            throw new OrderingDomainException("Only a delivery platform's order is picked up by the platform.");
        }

        Platform.MarkPickedUp(at);
    }

    private void AddOrderStartedDomainEvent(string userId, string userName)
    {
        var orderStartedDomainEvent = new OrderStartedDomainEvent(this, userId, userName);
        this.AddDomainEvent(orderStartedDomainEvent);
    }

    /// <summary>
    /// Give a confirmed delivery to a rider, or hand it to another before it
    /// leaves. The same rider again is a no-op.
    /// </summary>
    public void AssignRider(string riderUserId, string riderName, DateTime? at = null)
    {
        var delivery = EnsureDelivering();
        if (delivery.RiderUserId == riderUserId)
            return;

        var previous = delivery.AssignRider(riderUserId, riderName, at ?? DateTime.UtcNow);
        AddDomainEvent(new OrderDeliveryChangedDomainEvent(this, delivery.Stage, previous));
    }

    /// <summary>Take a delivery back from its rider before it leaves.</summary>
    public void UnassignRider()
    {
        var delivery = EnsureDelivering();
        if (delivery.RiderUserId is null)
            return;

        var previous = delivery.Unassign();
        AddDomainEvent(new OrderDeliveryChangedDomainEvent(this, delivery.Stage, previous));
    }

    /// <summary>The rider left with it. A repeat is a no-op.</summary>
    public void MarkOutForDelivery(DateTime? at = null)
    {
        var delivery = EnsureDelivering();
        if (delivery.MarkOut(at ?? DateTime.UtcNow))
            AddDomainEvent(new OrderDeliveryChangedDomainEvent(this, delivery.Stage));
    }

    /// <summary>The customer has it. A repeat is a no-op.</summary>
    public void MarkDelivered(DateTime? at = null)
    {
        var delivery = EnsureDelivering();
        if (delivery.MarkDelivered(at ?? DateTime.UtcNow))
            AddDomainEvent(new OrderDeliveryChangedDomainEvent(this, delivery.Stage));
    }

    /// <summary>It could not be handed over (nobody answered, refused). A repeat is a no-op.</summary>
    public void MarkDeliveryFailed(string reason, DateTime? at = null)
    {
        var delivery = EnsureDelivering();
        if (delivery.MarkFailed(reason, at ?? DateTime.UtcNow))
            AddDomainEvent(new OrderDeliveryChangedDomainEvent(this, delivery.Stage));
    }

    /// <summary>The rider brought it back to the branch. A repeat is a no-op.</summary>
    public void MarkDeliveryReturned(DateTime? at = null)
    {
        var delivery = EnsureDelivering();
        if (delivery.MarkReturned(at ?? DateTime.UtcNow))
            AddDomainEvent(new OrderDeliveryChangedDomainEvent(this, delivery.Stage));
    }

    /// <summary>
    /// The rider handed in what they collected at the till, which settles the
    /// bill with it. A repeat is a no-op; a bill already settled another way
    /// is refused, so the drawer is not counted twice.
    /// </summary>
    public void MarkDeliveryCashHandedIn(decimal amount, DateTime? at = null)
    {
        var delivery = EnsureDelivering();
        if (delivery.CashHandedInAt is null && IsPaid)
            throw new OrderingDomainException("The bill was settled already.", DeliveryErrors.AlreadySettled);
        if (delivery.MarkCashHandedIn(amount, at ?? DateTime.UtcNow))
            AddDomainEvent(new OrderDeliveryChangedDomainEvent(this, delivery.Stage, CashHandedIn: true));
    }

    private Delivery EnsureDelivering()
    {
        if (Delivery is null)
            throw new OrderingDomainException("This order isn't delivered.", DeliveryErrors.NotDelivery);
        if (OrderStatus != OrderStatus.Confirmed)
            throw new OrderingDomainException("Only a confirmed order goes out for delivery.", DeliveryErrors.NotConfirmed);
        return Delivery;
    }

    /// <summary>
    /// Record that a reminder notification was sent for this pending order
    /// </summary>
    public void RecordReminderSent()
    {
        ReminderCount++;
        LastReminderSentAt = DateTime.UtcNow;
    }

    /// <summary>
    /// The receipt that covered this order. Idempotent on the receipt number
    /// (the bus redelivers); a different receipt overwrites, since an order
    /// can only ever be on one bill.
    /// </summary>
    public void MarkPaid(int receiptNumber, string tender, DateTime at, int? ticketId = null)
    {
        if (ReceiptNumber == receiptNumber)
            return;
        ReceiptNumber = receiptNumber;
        PaidWith = tender;
        PaidAt = at;
        // The bill it landed on, when the cashier did not say so up front —
        // it is what the customer's receipt link opens
        TicketId ??= ticketId;
    }

    /// <summary>
    /// The open bill this order was on was voided; a paid order never is. Its
    /// stock is let go as the cashier said (<paramref name="stockDisposition"/>),
    /// or by whether the food was made.
    /// </summary>
    public void MarkVoided(DateTime at, StockDisposition? stockDisposition = null)
    {
        if (IsPaid || VoidedAt != null)
            return;
        VoidedAt = at;
        ReleaseStock(stockDisposition, StockReleaseReason.Voided, at);
    }

    /// <summary>A credit note gave part of this order back; never more than it cost.</summary>
    public void RecordRefund(decimal amount)
    {
        if (amount <= 0)
            return;
        RefundedAmount = Math.Min(GetTotal(), RefundedAmount + amount);
    }

    /// <summary>
    /// How many loyalty points buy one unit of currency (100 points = 1 EGP).
    /// Mirrors Loyalty.API's RedemptionPointsPerUnit — services share no code,
    /// so the business constant is deliberately duplicated, not referenced.
    /// </summary>
    public const int LoyaltyPointsPerCurrencyUnit = 100;

    /// <summary>
    /// What the redeemed points are worth against this subtotal: rate-derived,
    /// never trusted from a client, and never more than the order itself.
    /// </summary>
    public static double GetLoyaltyDiscountFor(int pointsToRedeem, decimal itemsTotal)
        => Math.Min((double)Math.Max(0, pointsToRedeem) / LoyaltyPointsPerCurrencyUnit, (double)Math.Max(0, itemsTotal));

    /// <summary>
    /// Item lines net of their own discounts, before the loyalty discount.
    /// </summary>
    public decimal GetItemsTotal() => _orderItems.Sum(o => o.Units * o.UnitPrice - o.Discount);

    /// <summary>
    /// What the customer actually pays: items net of line discounts, minus the
    /// promo and loyalty discounts, never below nothing — and the delivery fee
    /// on top, which no discount takes off.
    /// </summary>
    public decimal GetTotal() => Math.Max(0, GetItemsTotal() - PromoDiscount - (decimal)LoyaltyDiscount) + (Delivery?.Fee ?? 0);

    /// <summary>
    /// Check if the order can be rated (must be confirmed)
    /// </summary>
    public bool CanBeRated() => OrderStatus == OrderStatus.Confirmed;

    /// <summary>
    /// Check if the order has already been rated
    /// </summary>
    public bool HasRating() => Rating != null;
}
