#nullable enable
using System.ComponentModel.DataAnnotations;

namespace Chillax.Ordering.Domain.AggregatesModel.OrderAggregate;

/// <summary>
/// Order aggregate root for cafe orders.
/// Simple flow: Submitted -> Confirmed (goes to POS) or Cancelled
/// </summary>
public class Order
    : Entity, IAggregateRoot
{
    public DateTime OrderDate { get; private set; }

    public int? BuyerId { get; private set; }

    public Buyer? Buyer { get; }

    public OrderStatus OrderStatus { get; private set; }

    public string? Description { get; private set; }

    /// <summary>
    /// Room name for the session (e.g., "VIP", "Room 1") - localized
    /// </summary>
    public LocalizedText? RoomName { get; private set; }

    /// <summary>
    /// The café table the order is delivered to, when the customer is not in a room.
    /// Kept as an id as well as a name so open orders can be counted per table.
    /// </summary>
    public int? TableId { get; private set; }

    /// <summary>
    /// Table name captured at order time (e.g., "Table 3") - localized
    /// </summary>
    public LocalizedText? TableName { get; private set; }

    /// <summary>
    /// Special instructions or notes from the customer
    /// </summary>
    public string? CustomerNote { get; private set; }

    /// <summary>
    /// Loyalty points to redeem for this order (redeemed when order is confirmed)
    /// </summary>
    public int PointsToRedeem { get; private set; }

    /// <summary>
    /// Loyalty discount in currency, computed by the Loyalty API at order time
    /// </summary>
    public double LoyaltyDiscount { get; private set; }

    /// <summary>
    /// The branch this order was placed at
    /// </summary>
    public int BranchId { get; private set; }

    /// <summary>
    /// Identifies the device a guest ordered from, so they can see their own
    /// orders back without an account. Generated by the client and kept only
    /// in that browser — treat it as the secret it is, never as a public id.
    /// Null on orders placed by a signed-in customer.
    /// </summary>
    public string? GuestId { get; private set; }

    /// <summary>
    /// Name a guest left at checkout. Signed-in orders carry the name on the
    /// <see cref="Buyer"/> instead.
    /// </summary>
    public string? GuestName { get; private set; }

    /// <summary>
    /// Phone number a guest left at checkout, so staff can reach them. This is
    /// the only contact route for a guest order — there is no account behind it.
    /// </summary>
    public string? GuestPhone { get; private set; }

    /// <summary>
    /// A guest order has no <see cref="Buyer"/>: nobody signed in to place it.
    /// </summary>
    public bool IsGuestOrder => GuestId != null;

    // Draft orders have this set to true
#pragma warning disable CS0414
    private bool _isDraft;
#pragma warning restore CS0414

    // Using a private collection field for DDD Aggregate's encapsulation
    private readonly List<OrderItem> _orderItems;

    public IReadOnlyCollection<OrderItem> OrderItems => _orderItems.AsReadOnly();

    /// <summary>
    /// Order rating (null if not rated yet)
    /// </summary>
    public OrderRating? Rating { get; private set; }

    /// <summary>
    /// Number of reminder notifications sent for this order while pending
    /// </summary>
    public int ReminderCount { get; private set; }

    /// <summary>
    /// When the last reminder notification was sent (null if none sent)
    /// </summary>
    public DateTime? LastReminderSentAt { get; private set; }

    public static Order NewDraft()
    {
        var order = new Order
        {
            _isDraft = true
        };
        return order;
    }

    protected Order()
    {
        _orderItems = new List<OrderItem>();
        _isDraft = false;
    }

    public Order(string userId, string userName, int branchId, LocalizedText? roomName = null, string? customerNote = null, int? buyerId = null, int pointsToRedeem = 0, double loyaltyDiscount = 0, int? tableId = null, LocalizedText? tableName = null, string? guestId = null, string? guestName = null, string? guestPhone = null) : this()
    {
        BuyerId = buyerId;
        OrderStatus = OrderStatus.AwaitingValidation;
        OrderDate = DateTime.UtcNow;
        RoomName = roomName;
        TableId = tableId;
        TableName = tableName;
        CustomerNote = customerNote;
        PointsToRedeem = pointsToRedeem;
        LoyaltyDiscount = loyaltyDiscount;
        BranchId = branchId;
        Description = "Order awaiting item availability validation.";

        // No identity behind the order means a guest placed it. The name and
        // phone they left at checkout are then the only way staff can reach
        // them, so the aggregate refuses to exist without both.
        if (string.IsNullOrWhiteSpace(userId))
        {
            GuestId = !string.IsNullOrWhiteSpace(guestId)
                ? guestId
                : throw new OrderingDomainException("A guest order needs a guest id.");
            GuestName = !string.IsNullOrWhiteSpace(guestName)
                ? guestName
                : throw new OrderingDomainException("A guest order needs a name.");
            GuestPhone = !string.IsNullOrWhiteSpace(guestPhone)
                ? guestPhone
                : throw new OrderingDomainException("A guest order needs a phone number.");
        }

        // Add the OrderStartedDomainEvent to the domain events collection
        AddOrderStartedDomainEvent(userId, userName);
    }

    /// <summary>
    /// Add item to the order
    /// </summary>
    public void AddOrderItem(int productId, LocalizedText productName, decimal unitPrice, decimal discount, string? pictureUrl, int units = 1, LocalizedText? customizationsDescription = null, string? specialInstructions = null)
    {
        // When items have customizations, treat them as unique items (don't combine)
        var existingOrderForProduct = customizationsDescription == null
            ? _orderItems.SingleOrDefault(o => o.ProductId == productId && o.CustomizationsDescription == null)
            : null;

        if (existingOrderForProduct != null)
        {
            // If previous line exists, modify it with higher discount and units
            if (discount > existingOrderForProduct.Discount)
            {
                existingOrderForProduct.SetNewDiscount(discount);
            }

            existingOrderForProduct.AddUnits(units);
        }
        else
        {
            // Add validated new order item
            var orderItem = new OrderItem(productId, productName, unitPrice, discount, pictureUrl, units, customizationsDescription, specialInstructions);
            _orderItems.Add(orderItem);
        }
    }

    /// <summary>
    /// Set the buyer after validation
    /// </summary>
    public void SetBuyerId(int buyerId)
    {
        BuyerId = buyerId;
    }

    /// <summary>
    /// Set order to submitted after stock validation passes
    /// </summary>
    public void SetStockConfirmedStatus()
    {
        if (OrderStatus != OrderStatus.AwaitingValidation)
        {
            throw new OrderingDomainException($"Cannot confirm stock from status {OrderStatus}. Order must be in AwaitingValidation status.");
        }

        OrderStatus = OrderStatus.Submitted;
        Description = "Items validated. Order ready for confirmation.";
    }

    /// <summary>
    /// Set order to cancelled when stock validation fails
    /// </summary>
    public void SetStockRejectedStatus(IEnumerable<int> unavailableProductIds)
    {
        if (OrderStatus != OrderStatus.AwaitingValidation)
        {
            throw new OrderingDomainException($"Cannot reject stock from status {OrderStatus}. Order must be in AwaitingValidation status.");
        }

        OrderStatus = OrderStatus.Cancelled;
        Description = $"Order cancelled - some items are not available: {string.Join(", ", unavailableProductIds)}";
        AddDomainEvent(new OrderCancelledDomainEvent(this));
    }

    /// <summary>
    /// Confirm the order (admin action) - moves to POS
    /// </summary>
    public void SetConfirmedStatus()
    {
        if (OrderStatus != OrderStatus.Submitted)
        {
            throw new OrderingDomainException($"Cannot confirm order from status {OrderStatus}. Order must be in Submitted status.");
        }

        AddDomainEvent(new OrderStatusChangedToConfirmedDomainEvent(Id, _orderItems));
        OrderStatus = OrderStatus.Confirmed;
        Description = "Order confirmed and sent to POS.";
    }

    /// <summary>
    /// Cancel the order (can cancel submitted or awaiting validation orders)
    /// </summary>
    public void SetCancelledStatus()
    {
        if (OrderStatus != OrderStatus.Submitted && OrderStatus != OrderStatus.AwaitingValidation)
        {
            throw new OrderingDomainException($"Cannot cancel order from status {OrderStatus}. Only submitted or awaiting validation orders can be cancelled.");
        }

        OrderStatus = OrderStatus.Cancelled;
        Description = "The order was cancelled.";
        AddDomainEvent(new OrderCancelledDomainEvent(this));
    }

    private void AddOrderStartedDomainEvent(string userId, string userName)
    {
        var orderStartedDomainEvent = new OrderStartedDomainEvent(this, userId, userName);
        this.AddDomainEvent(orderStartedDomainEvent);
    }

    /// <summary>
    /// Record that a reminder notification was sent for this pending order
    /// </summary>
    public void RecordReminderSent()
    {
        ReminderCount++;
        LastReminderSentAt = DateTime.UtcNow;
    }

    public decimal GetTotal() => _orderItems.Sum(o => o.Units * o.UnitPrice);

    /// <summary>
    /// Check if the order can be rated (must be confirmed)
    /// </summary>
    public bool CanBeRated() => OrderStatus == OrderStatus.Confirmed;

    /// <summary>
    /// Check if the order has already been rated
    /// </summary>
    public bool HasRating() => Rating != null;
}
