#nullable enable
using System.ComponentModel.DataAnnotations;

namespace Chillax.Ordering.Domain.AggregatesModel.OrderAggregate;

/// <summary>
/// Order aggregate root for cafe orders.
/// Simple flow: Submitted -> Confirmed (goes to POS) or Cancelled
/// </summary>
public class Order
    : Entity, IAggregateRoot
{
    public DateTime OrderDate { get; private set; }

    public int? BuyerId { get; private set; }

    public Buyer? Buyer { get; }

    public OrderStatus OrderStatus { get; private set; }

    public string? Description { get; private set; }

    /// <summary>
    /// Room name for the session (e.g., "VIP", "Room 1") - localized
    /// </summary>
    public LocalizedText? RoomName { get; private set; }

    /// <summary>
    /// The Spaces session (reservation) this order was placed into, when the
    /// customer ordered from an active room session. The name snapshot above
    /// is for display; this id is what lets a bill be assembled per session.
    /// </summary>
    public int? SessionId { get; private set; }

    /// <summary>
    /// The room behind <see cref="SessionId"/>, captured so per-room queries
    /// don't need to resolve the session.
    /// </summary>
    public int? RoomId { get; private set; }

    /// <summary>
    /// Who put this order into the system — a signed-in customer, a guest at
    /// a table, or staff at the counter POS.
    /// </summary>
    public OrderSource Source { get; private set; }

    /// <summary>
    /// The café table the order is delivered to, when the customer is not in a room.
    /// Kept as an id as well as a name so open orders can be counted per table.
    /// </summary>
    public int? TableId { get; private set; }

    /// <summary>
    /// Table name captured at order time (e.g., "Table 3") - localized
    /// </summary>
    public LocalizedText? TableName { get; private set; }

    /// <summary>
    /// The Sales ticket this order must land on, when the cashier rang it up
    /// against an already-open bill. Ordering never reads it — it only carries
    /// it to Sales, which otherwise has to infer the bill from the session or
    /// table and cannot name a counter tab at all.
    /// </summary>
    public int? TicketId { get; private set; }

    /// <summary>
    /// When the till settled the bill this order was on — projected from
    /// Sales' TicketSettled event, never set here. Null until then: an order
    /// is confirmed long before it is paid.
    /// </summary>
    public DateTime? PaidAt { get; private set; }

    /// <summary>The receipt that covered the order; the same number the tab and the till show.</summary>
    public int? ReceiptNumber { get; private set; }

    /// <summary>"Cash", "Card", "InstaPay", "Account" (the customer's tab) or "Mixed".</summary>
    public string? PaidWith { get; private set; }

    /// <summary>What credit notes have given back against this order, capped at its total.</summary>
    public decimal RefundedAmount { get; private set; }

    /// <summary>
    /// When an owner voided the open bill this order was on — it will never
    /// be paid. Projected from Sales' TicketVoided event.
    /// </summary>
    public DateTime? VoidedAt { get; private set; }

    public bool IsPaid => PaidAt != null;

    /// <summary>
    /// Whether the order says where it is going. A running room session wins
    /// over a scanned table on the way in, so at most one of the two is set.
    /// </summary>
    public bool HasDestination => RoomName is not null || TableId.HasValue;

    /// <summary>
    /// Special instructions or notes from the customer
    /// </summary>
    public string? CustomerNote { get; private set; }

    /// <summary>
    /// Loyalty points to redeem for this order (redeemed when order is confirmed)
    /// </summary>
    public int PointsToRedeem { get; private set; }

    /// <summary>
    /// Loyalty discount in currency, computed by the Loyalty API at order time
    /// </summary>
    public double LoyaltyDiscount { get; private set; }

    /// <summary>
    /// The branch this order was placed at
    /// </summary>
    public int BranchId { get; private set; }

    /// <summary>
    /// Identifies the device a guest ordered from, so they can see their own
    /// orders back without an account. Generated by the client and kept only
    /// in that browser — treat it as the secret it is, never as a public id.
    /// Null on orders placed by a signed-in customer.
    /// </summary>
    public string? GuestId { get; private set; }

    /// <summary>
    /// Name a guest left at checkout. Signed-in orders carry the name on the
    /// <see cref="Buyer"/> instead.
    /// </summary>
    public string? GuestName { get; private set; }

    /// <summary>
    /// Phone number a guest left at checkout, so staff can reach them. This is
    /// the only contact route for a guest order — there is no account behind it.
    /// </summary>
    public string? GuestPhone { get; private set; }

    /// <summary>
    /// A guest order has no <see cref="Buyer"/>: nobody signed in to place it.
    /// </summary>
    public bool IsGuestOrder => GuestId != null;

    // Draft orders have this set to true
#pragma warning disable CS0414
    private bool _isDraft;
#pragma warning restore CS0414

    // Using a private collection field for DDD Aggregate's encapsulation
    private readonly List<OrderItem> _orderItems;

    public IReadOnlyCollection<OrderItem> OrderItems => _orderItems.AsReadOnly();

    /// <summary>
    /// Order rating (null if not rated yet)
    /// </summary>
    public OrderRating? Rating { get; private set; }

    /// <summary>
    /// Number of reminder notifications sent for this order while pending
    /// </summary>
    public int ReminderCount { get; private set; }

    /// <summary>
    /// When the last reminder notification was sent (null if none sent)
    /// </summary>
    public DateTime? LastReminderSentAt { get; private set; }

    /// <summary>
    /// When staff confirmed the order — the moment it reached the kitchen.
    /// Null on orders confirmed before the kitchen display existed, which is
    /// how the kitchen query leaves history alone.
    /// </summary>
    public DateTime? ConfirmedAt { get; private set; }

    /// <summary>
    /// When the kitchen finished it; null while it is still on the board,
    /// and null again if the kitchen brings it back. The order's only
    /// kitchen state: never shown to the customer, never changes what the
    /// order costs.
    /// </summary>
    public DateTime? ReadyAt { get; private set; }

    public bool IsReady => ReadyAt != null;

    public static Order NewDraft()
    {
        var order = new Order
        {
            _isDraft = true
        };
        return order;
    }

    protected Order()
    {
        _orderItems = new List<OrderItem>();
        _isDraft = false;
    }

    public Order(string userId, string userName, int branchId, LocalizedText? roomName = null, string? customerNote = null, int? buyerId = null, int pointsToRedeem = 0, double loyaltyDiscount = 0, int? tableId = null, LocalizedText? tableName = null, string? guestId = null, string? guestName = null, string? guestPhone = null, OrderSource? source = null, int? sessionId = null, int? roomId = null, int? ticketId = null, DateTime? placedAt = null) : this()
    {
        BuyerId = buyerId;
        OrderStatus = OrderStatus.AwaitingValidation;
        // A replayed offline sale is dated when it was rung up, not when it reached us
        OrderDate = placedAt ?? DateTime.UtcNow;
        RoomName = roomName;
        SessionId = sessionId;
        RoomId = roomId;
        TableId = tableId;
        TableName = tableName;
        TicketId = ticketId;
        CustomerNote = customerNote;
        PointsToRedeem = pointsToRedeem;
        LoyaltyDiscount = loyaltyDiscount;
        BranchId = branchId;
        Description = "Order awaiting item availability validation.";

        // Callers that know better (the POS path) say so; otherwise the
        // identity decides: a signed-in user is a customer, nobody is a guest.
        Source = source ?? (string.IsNullOrWhiteSpace(userId) ? OrderSource.Guest : OrderSource.Customer);

        // No identity behind the order means a guest placed it. The name and
        // phone they left at checkout are then the only way staff can reach
        // them, so the aggregate refuses to exist without both. A counter sale
        // (Source = Pos) is exempt: the cashier standing there is the contact.
        // The till is often given a name for someone with no account — the
        // waiters know the regulars. It identifies nobody and unlocks nothing;
        // it just has to travel, onto the kitchen card and onto the bill line.
        if (Source == OrderSource.Pos)
        {
            GuestName = string.IsNullOrWhiteSpace(guestName) ? null : guestName.Trim();
        }

        if (Source == OrderSource.Guest)
        {
            GuestId = !string.IsNullOrWhiteSpace(guestId)
                ? guestId
                : throw new OrderingDomainException("A guest order needs a guest id.");
            GuestName = !string.IsNullOrWhiteSpace(guestName)
                ? guestName
                : throw new OrderingDomainException("A guest order needs a name.");
            GuestPhone = !string.IsNullOrWhiteSpace(guestPhone)
                ? guestPhone
                : throw new OrderingDomainException("A guest order needs a phone number.");

            // Where they are sitting is the only thing anchoring a guest order
            // to someone actually in the building. Without it there is nobody
            // to carry it to, and ordering ahead — which is what a destination
            // less order really is — is reserved for account holders who can
            // be held to it. In practice this always means a table: a room
            // session belongs to an account.
            if (!HasDestination)
            {
                throw new OrderingDomainException("A guest order needs a table or room to be delivered to.");
            }
        }

        // Add the OrderStartedDomainEvent to the domain events collection
        AddOrderStartedDomainEvent(userId, userName);
    }

    /// <summary>
    /// Add item to the order
    /// </summary>
    public void AddOrderItem(int productId, LocalizedText productName, decimal unitPrice, decimal discount, string? pictureUrl, int units = 1, LocalizedText? customizationsDescription = null, string? specialInstructions = null, IEnumerable<int>? optionIds = null)
    {
        // When items have customizations, treat them as unique items (don't combine)
        var existingOrderForProduct = customizationsDescription == null
            ? _orderItems.SingleOrDefault(o => o.ProductId == productId && o.CustomizationsDescription == null)
            : null;

        if (existingOrderForProduct != null)
        {
            // If previous line exists, modify it with higher discount and units
            if (discount > existingOrderForProduct.Discount)
            {
                existingOrderForProduct.SetNewDiscount(discount);
            }

            existingOrderForProduct.AddUnits(units);
        }
        else
        {
            // Add validated new order item
            var orderItem = new OrderItem(productId, productName, unitPrice, discount, pictureUrl, units, customizationsDescription, specialInstructions, optionIds);
            _orderItems.Add(orderItem);
        }
    }

    /// <summary>
    /// Set the buyer after validation
    /// </summary>
    public void SetBuyerId(int buyerId)
    {
        BuyerId = buyerId;
    }

    /// <summary>
    /// Name the customer after the fact — the cashier rang the sale up and
    /// only then remembered whose it was, or named the wrong regular.
    /// Allowed until the order is cancelled. A bare name identifies nobody,
    /// so an account (or a better name) may replace it. An account may be
    /// replaced by another: the points it earned at confirmation follow the
    /// order, which is why the event names the account losing them as well
    /// as the one gaining them. It cannot be swapped for itself, nor dropped
    /// back to a bare name. The name travels the way the POS constructor's
    /// does — onto the kitchen card and the bill line; the account, when
    /// there is one, becomes the <see cref="Buyer"/>.
    /// </summary>
    /// <param name="previousBuyerIdentityGuid">
    /// The identity behind the current <see cref="BuyerId"/>, looked up by
    /// the caller: the aggregate holds only the row id, and the event goes
    /// out before anything is saved.
    /// </param>
    public void AssignCustomer(string customerName, Buyer? buyer = null, string? previousBuyerIdentityGuid = null)
    {
        if (OrderStatus == OrderStatus.Cancelled)
        {
            throw new OrderingDomainException("A cancelled order cannot be assigned a customer.");
        }

        if (BuyerId is not null)
        {
            if (buyer is null)
            {
                throw new OrderingDomainException("This order belongs to a customer account — it can move to another account, not to a bare name.");
            }

            if (buyer.Id == BuyerId || buyer.IdentityGuid == previousBuyerIdentityGuid)
            {
                throw new OrderingDomainException("This order already belongs to this customer.");
            }
        }

        if (string.IsNullOrWhiteSpace(customerName))
        {
            throw new OrderingDomainException("A customer needs a name.");
        }

        // Whose it was only matters if it was anyone's
        var previous = BuyerId is null ? null : previousBuyerIdentityGuid;

        GuestName = customerName.Trim();
        BuyerId = buyer?.Id;

        AddDomainEvent(new OrderCustomerAssignedDomainEvent(this, buyer?.IdentityGuid, previous));
    }

    /// <summary>
    /// Set order to submitted after stock validation passes
    /// </summary>
    public void SetStockConfirmedStatus()
    {
        if (OrderStatus != OrderStatus.AwaitingValidation)
        {
            throw new OrderingDomainException($"Cannot confirm stock from status {OrderStatus}. Order must be in AwaitingValidation status.");
        }

        OrderStatus = OrderStatus.Submitted;
        Description = "Items validated. Order ready for confirmation.";
        AddDomainEvent(new OrderStatusChangedToSubmittedDomainEvent(Id));
    }

    /// <summary>
    /// Set order to cancelled when stock validation fails
    /// </summary>
    public void SetStockRejectedStatus(IEnumerable<int> unavailableProductIds)
    {
        if (OrderStatus != OrderStatus.AwaitingValidation)
        {
            throw new OrderingDomainException($"Cannot reject stock from status {OrderStatus}. Order must be in AwaitingValidation status.");
        }

        OrderStatus = OrderStatus.Cancelled;
        Description = $"Order cancelled - some items are not available: {string.Join(", ", unavailableProductIds)}";
        AddDomainEvent(new OrderCancelledDomainEvent(this));
    }

    /// <summary>
    /// Confirm the order (admin action) - moves to POS
    /// </summary>
    public void SetConfirmedStatus()
    {
        if (OrderStatus != OrderStatus.Submitted)
        {
            throw new OrderingDomainException($"Cannot confirm order from status {OrderStatus}. Order must be in Submitted status.");
        }

        AddDomainEvent(new OrderStatusChangedToConfirmedDomainEvent(Id, _orderItems));
        OrderStatus = OrderStatus.Confirmed;
        ConfirmedAt = DateTime.UtcNow;
        Description = "Order confirmed and sent to POS.";
    }

    /// <summary>
    /// Mark the order ready in the kitchen, or bring a ready one back to the
    /// board (a card bumped too early, or a remake). The same state twice is
    /// a no-op, so two screens tapping the same card do not race each other
    /// into an error. Only a confirmed order is in the kitchen at all.
    /// </summary>
    public void SetReady(bool ready)
    {
        if (OrderStatus != OrderStatus.Confirmed)
        {
            throw new OrderingDomainException($"Cannot change kitchen state from status {OrderStatus}. Only a confirmed order is in the kitchen.");
        }

        if (ready == IsReady)
        {
            return;
        }

        ReadyAt = ready ? DateTime.UtcNow : null;

        AddDomainEvent(new OrderReadyChangedDomainEvent(Id, BranchId, ready));
    }

    /// <summary>
    /// Cancel the order (can cancel submitted or awaiting validation orders)
    /// </summary>
    public void SetCancelledStatus()
    {
        if (OrderStatus != OrderStatus.Submitted && OrderStatus != OrderStatus.AwaitingValidation)
        {
            throw new OrderingDomainException($"Cannot cancel order from status {OrderStatus}. Only submitted or awaiting validation orders can be cancelled.");
        }

        OrderStatus = OrderStatus.Cancelled;
        Description = "The order was cancelled.";
        AddDomainEvent(new OrderCancelledDomainEvent(this));
    }

    private void AddOrderStartedDomainEvent(string userId, string userName)
    {
        var orderStartedDomainEvent = new OrderStartedDomainEvent(this, userId, userName);
        this.AddDomainEvent(orderStartedDomainEvent);
    }

    /// <summary>
    /// Record that a reminder notification was sent for this pending order
    /// </summary>
    public void RecordReminderSent()
    {
        ReminderCount++;
        LastReminderSentAt = DateTime.UtcNow;
    }

    /// <summary>
    /// The receipt that covered this order. Idempotent on the receipt number
    /// (the bus redelivers); a different receipt overwrites, since an order
    /// can only ever be on one bill.
    /// </summary>
    public void MarkPaid(int receiptNumber, string tender, DateTime at)
    {
        if (ReceiptNumber == receiptNumber)
            return;
        ReceiptNumber = receiptNumber;
        PaidWith = tender;
        PaidAt = at;
    }

    /// <summary>The open bill this order was on was voided; a paid order never is.</summary>
    public void MarkVoided(DateTime at)
    {
        if (IsPaid || VoidedAt != null)
            return;
        VoidedAt = at;
    }

    /// <summary>A credit note gave part of this order back; never more than it cost.</summary>
    public void RecordRefund(decimal amount)
    {
        if (amount <= 0)
            return;
        RefundedAmount = Math.Min(GetTotal(), RefundedAmount + amount);
    }

    /// <summary>
    /// How many loyalty points buy one unit of currency (100 points = 1 EGP).
    /// Mirrors Loyalty.API's RedemptionPointsPerUnit — services share no code,
    /// so the business constant is deliberately duplicated, not referenced.
    /// </summary>
    public const int LoyaltyPointsPerCurrencyUnit = 100;

    /// <summary>
    /// What the redeemed points are worth against this subtotal: rate-derived,
    /// never trusted from a client, and never more than the order itself.
    /// </summary>
    public static double GetLoyaltyDiscountFor(int pointsToRedeem, decimal itemsTotal)
        => Math.Min((double)Math.Max(0, pointsToRedeem) / LoyaltyPointsPerCurrencyUnit, (double)Math.Max(0, itemsTotal));

    /// <summary>
    /// Item lines net of their own discounts, before the loyalty discount.
    /// </summary>
    public decimal GetItemsTotal() => _orderItems.Sum(o => o.Units * o.UnitPrice - o.Discount);

    /// <summary>
    /// What the customer actually pays: items net of line discounts, minus the
    /// loyalty discount. Never negative.
    /// </summary>
    public decimal GetTotal() => Math.Max(0, GetItemsTotal() - (decimal)LoyaltyDiscount);

    /// <summary>
    /// Check if the order can be rated (must be confirmed)
    /// </summary>
    public bool CanBeRated() => OrderStatus == OrderStatus.Confirmed;

    /// <summary>
    /// Check if the order has already been rated
    /// </summary>
    public bool HasRating() => Rating != null;
}
