// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { attachExpenseReceipt, getExpenseCategories, getExpenseReceipt, getExpenses, getPartnerLedger, getPartners, getProfit, getProfitTrend, getRecurringExpenses, getSupplierLedger, getSuppliers, getTillCategories, getTillPartners, getTillSuppliers, type Options, postPartnerEntry, postSupplierEntry, recordExpense, removeExpenseReceipt, saveExpenseCategory, savePartner, saveRecurringExpense, saveSupplier, voidExpense } from '../sdk.gen';
import type { AttachExpenseReceiptData, AttachExpenseReceiptError, GetExpenseCategoriesData, GetExpenseCategoriesResponse, GetExpenseReceiptData, GetExpensesData, GetExpensesResponse, GetPartnerLedgerData, GetPartnerLedgerResponse, GetPartnersData, GetPartnersResponse, GetProfitData, GetProfitResponse, GetProfitTrendData, GetProfitTrendResponse, GetRecurringExpensesData, GetRecurringExpensesResponse, GetSupplierLedgerData, GetSupplierLedgerResponse, GetSuppliersData, GetSuppliersResponse, GetTillCategoriesData, GetTillCategoriesResponse, GetTillPartnersData, GetTillPartnersResponse, GetTillSuppliersData, GetTillSuppliersResponse, PostPartnerEntryData, PostPartnerEntryError, PostPartnerEntryResponse, PostSupplierEntryData, PostSupplierEntryError, PostSupplierEntryResponse, RecordExpenseData, RecordExpenseError, RecordExpenseResponse, RemoveExpenseReceiptData, SaveExpenseCategoryData, SaveExpenseCategoryError, SaveExpenseCategoryResponse, SavePartnerData, SavePartnerError, SavePartnerResponse, SaveRecurringExpenseData, SaveRecurringExpenseError, SaveRecurringExpenseResponse, SaveSupplierData, SaveSupplierError, SaveSupplierResponse, VoidExpenseData, VoidExpenseError } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getExpenseCategoriesQueryKey = (options: Options<GetExpenseCategoriesData>) => createQueryKey('getExpenseCategories', options);

export const getExpenseCategoriesOptions = (options: Options<GetExpenseCategoriesData>) => queryOptions<GetExpenseCategoriesResponse, AxiosError<DefaultError>, GetExpenseCategoriesResponse, ReturnType<typeof getExpenseCategoriesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getExpenseCategories({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getExpenseCategoriesQueryKey(options)
});

/**
 * Add a category, or edit one when the body carries its id
 */
export const saveExpenseCategoryMutation = (options?: Partial<Options<SaveExpenseCategoryData>>): UseMutationOptions<SaveExpenseCategoryResponse, AxiosError<SaveExpenseCategoryError>, Options<SaveExpenseCategoryData>> => {
    const mutationOptions: UseMutationOptions<SaveExpenseCategoryResponse, AxiosError<SaveExpenseCategoryError>, Options<SaveExpenseCategoryData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await saveExpenseCategory({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getExpensesQueryKey = (options: Options<GetExpensesData>) => createQueryKey('getExpenses', options);

/**
 * The branch's expenses in a date range, with totals by category
 */
export const getExpensesOptions = (options: Options<GetExpensesData>) => queryOptions<GetExpensesResponse, AxiosError<DefaultError>, GetExpensesResponse, ReturnType<typeof getExpensesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getExpenses({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getExpensesQueryKey(options)
});

/**
 * An expense keyed in: from the drawer, the bank, or a partner's own pocket
 */
export const recordExpenseMutation = (options?: Partial<Options<RecordExpenseData>>): UseMutationOptions<RecordExpenseResponse, AxiosError<RecordExpenseError>, Options<RecordExpenseData>> => {
    const mutationOptions: UseMutationOptions<RecordExpenseResponse, AxiosError<RecordExpenseError>, Options<RecordExpenseData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await recordExpense({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Void an expense with a reason; it stays on the list, struck through
 */
export const voidExpenseMutation = (options?: Partial<Options<VoidExpenseData>>): UseMutationOptions<unknown, AxiosError<VoidExpenseError>, Options<VoidExpenseData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<VoidExpenseError>, Options<VoidExpenseData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await voidExpense({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const removeExpenseReceiptMutation = (options?: Partial<Options<RemoveExpenseReceiptData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<RemoveExpenseReceiptData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<RemoveExpenseReceiptData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await removeExpenseReceipt({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getExpenseReceiptQueryKey = (options: Options<GetExpenseReceiptData>) => createQueryKey('getExpenseReceipt', options);

/**
 * The attached bill, as the file it was uploaded as
 */
export const getExpenseReceiptOptions = (options: Options<GetExpenseReceiptData>) => queryOptions<unknown, AxiosError<DefaultError>, unknown, ReturnType<typeof getExpenseReceiptQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getExpenseReceipt({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getExpenseReceiptQueryKey(options)
});

/**
 * Attach the photo or PDF of the bill (5 MB at most); uploading again replaces it
 */
export const attachExpenseReceiptMutation = (options?: Partial<Options<AttachExpenseReceiptData>>): UseMutationOptions<unknown, AxiosError<AttachExpenseReceiptError>, Options<AttachExpenseReceiptData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<AttachExpenseReceiptError>, Options<AttachExpenseReceiptData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await attachExpenseReceipt({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getRecurringExpensesQueryKey = (options: Options<GetRecurringExpensesData>) => createQueryKey('getRecurringExpenses', options);

/**
 * The branch's monthly bills that post themselves
 */
export const getRecurringExpensesOptions = (options: Options<GetRecurringExpensesData>) => queryOptions<GetRecurringExpensesResponse, AxiosError<DefaultError>, GetRecurringExpensesResponse, ReturnType<typeof getRecurringExpensesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRecurringExpenses({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRecurringExpensesQueryKey(options)
});

/**
 * Add a recurring bill, or edit one when the body carries its id
 */
export const saveRecurringExpenseMutation = (options?: Partial<Options<SaveRecurringExpenseData>>): UseMutationOptions<SaveRecurringExpenseResponse, AxiosError<SaveRecurringExpenseError>, Options<SaveRecurringExpenseData>> => {
    const mutationOptions: UseMutationOptions<SaveRecurringExpenseResponse, AxiosError<SaveRecurringExpenseError>, Options<SaveRecurringExpenseData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await saveRecurringExpense({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getSuppliersQueryKey = (options: Options<GetSuppliersData>) => createQueryKey('getSuppliers', options);

/**
 * Suppliers with what the branch owes each
 */
export const getSuppliersOptions = (options: Options<GetSuppliersData>) => queryOptions<GetSuppliersResponse, AxiosError<DefaultError>, GetSuppliersResponse, ReturnType<typeof getSuppliersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSuppliers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSuppliersQueryKey(options)
});

/**
 * Add a supplier, or edit one when the body carries its id
 */
export const saveSupplierMutation = (options?: Partial<Options<SaveSupplierData>>): UseMutationOptions<SaveSupplierResponse, AxiosError<SaveSupplierError>, Options<SaveSupplierData>> => {
    const mutationOptions: UseMutationOptions<SaveSupplierResponse, AxiosError<SaveSupplierError>, Options<SaveSupplierData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await saveSupplier({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getSupplierLedgerQueryKey = (options: Options<GetSupplierLedgerData>) => createQueryKey('getSupplierLedger', options);

export const getSupplierLedgerOptions = (options: Options<GetSupplierLedgerData>) => queryOptions<GetSupplierLedgerResponse, AxiosError<DefaultError>, GetSupplierLedgerResponse, ReturnType<typeof getSupplierLedgerQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSupplierLedger({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSupplierLedgerQueryKey(options)
});

/**
 * A payment made outside the drawer, a credit, or an invoice with no stock receipt
 */
export const postSupplierEntryMutation = (options?: Partial<Options<PostSupplierEntryData>>): UseMutationOptions<PostSupplierEntryResponse, AxiosError<PostSupplierEntryError>, Options<PostSupplierEntryData>> => {
    const mutationOptions: UseMutationOptions<PostSupplierEntryResponse, AxiosError<PostSupplierEntryError>, Options<PostSupplierEntryData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postSupplierEntry({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getPartnersQueryKey = (options: Options<GetPartnersData>) => createQueryKey('getPartners', options);

/**
 * The branch's partners with what the café holds of theirs
 */
export const getPartnersOptions = (options: Options<GetPartnersData>) => queryOptions<GetPartnersResponse, AxiosError<DefaultError>, GetPartnersResponse, ReturnType<typeof getPartnersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPartners({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPartnersQueryKey(options)
});

/**
 * Add a partner, or edit one when the body carries its id
 */
export const savePartnerMutation = (options?: Partial<Options<SavePartnerData>>): UseMutationOptions<SavePartnerResponse, AxiosError<SavePartnerError>, Options<SavePartnerData>> => {
    const mutationOptions: UseMutationOptions<SavePartnerResponse, AxiosError<SavePartnerError>, Options<SavePartnerData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await savePartner({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getPartnerLedgerQueryKey = (options: Options<GetPartnerLedgerData>) => createQueryKey('getPartnerLedger', options);

export const getPartnerLedgerOptions = (options: Options<GetPartnerLedgerData>) => queryOptions<GetPartnerLedgerResponse, AxiosError<DefaultError>, GetPartnerLedgerResponse, ReturnType<typeof getPartnerLedgerQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPartnerLedger({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPartnerLedgerQueryKey(options)
});

/**
 * Money a partner put in or took outside the drawer
 */
export const postPartnerEntryMutation = (options?: Partial<Options<PostPartnerEntryData>>): UseMutationOptions<PostPartnerEntryResponse, AxiosError<PostPartnerEntryError>, Options<PostPartnerEntryData>> => {
    const mutationOptions: UseMutationOptions<PostPartnerEntryResponse, AxiosError<PostPartnerEntryError>, Options<PostPartnerEntryData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postPartnerEntry({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getProfitQueryKey = (options: Options<GetProfitData>) => createQueryKey('getProfit', options);

/**
 * A month's profit and loss at the branch: sales, cost of goods, labour, expenses
 */
export const getProfitOptions = (options: Options<GetProfitData>) => queryOptions<GetProfitResponse, AxiosError<DefaultError>, GetProfitResponse, ReturnType<typeof getProfitQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getProfit({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getProfitQueryKey(options)
});

export const getProfitTrendQueryKey = (options: Options<GetProfitTrendData>) => createQueryKey('getProfitTrend', options);

/**
 * The last months' headline figures, newest first
 */
export const getProfitTrendOptions = (options: Options<GetProfitTrendData>) => queryOptions<GetProfitTrendResponse, AxiosError<DefaultError>, GetProfitTrendResponse, ReturnType<typeof getProfitTrendQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getProfitTrend({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getProfitTrendQueryKey(options)
});

export const getTillSuppliersQueryKey = (options: Options<GetTillSuppliersData>) => createQueryKey('getTillSuppliers', options);

export const getTillSuppliersOptions = (options: Options<GetTillSuppliersData>) => queryOptions<GetTillSuppliersResponse, AxiosError<DefaultError>, GetTillSuppliersResponse, ReturnType<typeof getTillSuppliersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getTillSuppliers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTillSuppliersQueryKey(options)
});

export const getTillPartnersQueryKey = (options: Options<GetTillPartnersData>) => createQueryKey('getTillPartners', options);

export const getTillPartnersOptions = (options: Options<GetTillPartnersData>) => queryOptions<GetTillPartnersResponse, AxiosError<DefaultError>, GetTillPartnersResponse, ReturnType<typeof getTillPartnersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getTillPartners({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTillPartnersQueryKey(options)
});

export const getTillCategoriesQueryKey = (options: Options<GetTillCategoriesData>) => createQueryKey('getTillCategories', options);

export const getTillCategoriesOptions = (options: Options<GetTillCategoriesData>) => queryOptions<GetTillCategoriesResponse, AxiosError<DefaultError>, GetTillCategoriesResponse, ReturnType<typeof getTillCategoriesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getTillCategories({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTillCategoriesQueryKey(options)
});
