// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { CreateBranchData, CreateBranchErrors, CreateBranchResponses, DeleteTenantImageData, DeleteTenantImageErrors, DeleteTenantImageResponses, GetAllBranchesData, GetAllBranchesErrors, GetAllBranchesResponses, GetBranchesData, GetBranchesResponses, GetTenantData, GetTenantIconData, GetTenantIconErrors, GetTenantImageData, GetTenantImageErrors, GetTenantManifestData, GetTenantManifestErrors, GetTenantResponses, SetTenantEntitlementsData, SetTenantEntitlementsErrors, SetTenantEntitlementsResponses, UpdateBranchData, UpdateBranchErrors, UpdateBranchResponses, UpdateBranchSettingsData, UpdateBranchSettingsErrors, UpdateBranchSettingsResponses, UpdateTenantData, UpdateTenantErrors, UpdateTenantResponses, UploadTenantImageData, UploadTenantImageErrors, UploadTenantImageResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List active branches
 */
export const getBranches = <ThrowOnError extends boolean = false>(options?: Options<GetBranchesData, ThrowOnError>): RequestResult<GetBranchesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetBranchesResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/branches',
    ...options
});

/**
 * Create a branch
 */
export const createBranch = <ThrowOnError extends boolean = false>(options: Options<CreateBranchData, ThrowOnError>): RequestResult<CreateBranchResponses, CreateBranchErrors, ThrowOnError> => (options.client ?? client).post<CreateBranchResponses, CreateBranchErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/branches',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List all branches including inactive
 */
export const getAllBranches = <ThrowOnError extends boolean = false>(options?: Options<GetAllBranchesData, ThrowOnError>): RequestResult<GetAllBranchesResponses, GetAllBranchesErrors, ThrowOnError> => (options?.client ?? client).get<GetAllBranchesResponses, GetAllBranchesErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/branches/all',
    ...options
});

/**
 * Update a branch
 */
export const updateBranch = <ThrowOnError extends boolean = false>(options: Options<UpdateBranchData, ThrowOnError>): RequestResult<UpdateBranchResponses, UpdateBranchErrors, ThrowOnError> => (options.client ?? client).put<UpdateBranchResponses, UpdateBranchErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/branches/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update branch operational settings (ordering, reservations)
 */
export const updateBranchSettings = <ThrowOnError extends boolean = false>(options: Options<UpdateBranchSettingsData, ThrowOnError>): RequestResult<UpdateBranchSettingsResponses, UpdateBranchSettingsErrors, ThrowOnError> => (options.client ?? client).patch<UpdateBranchSettingsResponses, UpdateBranchSettingsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/branches/{branchId}/settings',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * The tenant's name, color, logo URLs and feature switches
 */
export const getTenant = <ThrowOnError extends boolean = false>(options?: Options<GetTenantData, ThrowOnError>): RequestResult<GetTenantResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetTenantResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/tenant',
    ...options
});

/**
 * Change the name, the brand color or the feature switches (within what the plan allows)
 */
export const updateTenant = <ThrowOnError extends boolean = false>(options: Options<UpdateTenantData, ThrowOnError>): RequestResult<UpdateTenantResponses, UpdateTenantErrors, ThrowOnError> => (options.client ?? client).put<UpdateTenantResponses, UpdateTenantErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/tenant',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * The modules the café's plan allows; a switch outside them goes off. The control plane only
 */
export const setTenantEntitlements = <ThrowOnError extends boolean = false>(options: Options<SetTenantEntitlementsData, ThrowOnError>): RequestResult<SetTenantEntitlementsResponses, SetTenantEntitlementsErrors, ThrowOnError> => (options.client ?? client).put<SetTenantEntitlementsResponses, SetTenantEntitlementsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/tenant/entitlements',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Remove one image; the surfaces fall back (dark to light, Arabic to English, the wordmark to the mark and the name)
 */
export const deleteTenantImage = <ThrowOnError extends boolean = false>(options: Options<DeleteTenantImageData, ThrowOnError>): RequestResult<DeleteTenantImageResponses, DeleteTenantImageErrors, ThrowOnError> => (options.client ?? client).delete<DeleteTenantImageResponses, DeleteTenantImageErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/tenant/images/{slot}',
    ...options
});

/**
 * One image as PNG, transparent margins trimmed
 */
export const getTenantImage = <ThrowOnError extends boolean = false>(options: Options<GetTenantImageData, ThrowOnError>): RequestResult<unknown, GetTenantImageErrors, ThrowOnError> => (options.client ?? client).get<unknown, GetTenantImageErrors, ThrowOnError>({ url: '/api/tenant/images/{slot}', ...options });

/**
 * Replace one image: logo, logo-dark, wordmark-en, wordmark-en-dark, wordmark-ar or wordmark-ar-dark; the icons are cut from the logo
 */
export const uploadTenantImage = <ThrowOnError extends boolean = false>(options: Options<UploadTenantImageData, ThrowOnError>): RequestResult<UploadTenantImageResponses, UploadTenantImageErrors, ThrowOnError> => (options.client ?? client).put<UploadTenantImageResponses, UploadTenantImageErrors, ThrowOnError>({
    ...formDataBodySerializer,
    responseType: 'json',
    url: '/api/tenant/images/{slot}',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * One of icon-192.png, icon-512.png, maskable-512.png, apple-touch-icon.png, favicon.png
 */
export const getTenantIcon = <ThrowOnError extends boolean = false>(options: Options<GetTenantIconData, ThrowOnError>): RequestResult<unknown, GetTenantIconErrors, ThrowOnError> => (options.client ?? client).get<unknown, GetTenantIconErrors, ThrowOnError>({ url: '/api/tenant/icons/{name}', ...options });

/**
 * The web app manifest for one surface, in the tenant's name
 */
export const getTenantManifest = <ThrowOnError extends boolean = false>(options?: Options<GetTenantManifestData, ThrowOnError>): RequestResult<unknown, GetTenantManifestErrors, ThrowOnError> => (options?.client ?? client).get<unknown, GetTenantManifestErrors, ThrowOnError>({ url: '/api/tenant/manifest', ...options });
