// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateBranchData, CreateBranchErrors, CreateBranchResponses, GetAllBranchesData, GetAllBranchesErrors, GetAllBranchesResponses, GetBranchesData, GetBranchesResponses, UpdateBranchData, UpdateBranchErrors, UpdateBranchResponses, UpdateBranchSettingsData, UpdateBranchSettingsErrors, UpdateBranchSettingsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List active branches
 */
export const getBranches = <ThrowOnError extends boolean = false>(options?: Options<GetBranchesData, ThrowOnError>): RequestResult<GetBranchesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetBranchesResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/branches',
    ...options
});

/**
 * Create a branch
 */
export const createBranch = <ThrowOnError extends boolean = false>(options: Options<CreateBranchData, ThrowOnError>): RequestResult<CreateBranchResponses, CreateBranchErrors, ThrowOnError> => (options.client ?? client).post<CreateBranchResponses, CreateBranchErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/branches',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List all branches including inactive
 */
export const getAllBranches = <ThrowOnError extends boolean = false>(options?: Options<GetAllBranchesData, ThrowOnError>): RequestResult<GetAllBranchesResponses, GetAllBranchesErrors, ThrowOnError> => (options?.client ?? client).get<GetAllBranchesResponses, GetAllBranchesErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/branches/all',
    ...options
});

/**
 * Update a branch
 */
export const updateBranch = <ThrowOnError extends boolean = false>(options: Options<UpdateBranchData, ThrowOnError>): RequestResult<UpdateBranchResponses, UpdateBranchErrors, ThrowOnError> => (options.client ?? client).put<UpdateBranchResponses, UpdateBranchErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/branches/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update branch operational settings (ordering, reservations)
 */
export const updateBranchSettings = <ThrowOnError extends boolean = false>(options: Options<UpdateBranchSettingsData, ThrowOnError>): RequestResult<UpdateBranchSettingsResponses, UpdateBranchSettingsErrors, ThrowOnError> => (options.client ?? client).patch<UpdateBranchSettingsResponses, UpdateBranchSettingsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/branches/{branchId}/settings',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
