// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

export type AccountDto = {
    id?: number | string;
    userId?: string;
    userDisplayName?: null | string;
    pointsBalance?: number | string;
    lifetimePoints?: number | string;
    currentTier?: string;
    createdAt?: string;
    updatedAt?: string;
};

export type AdjustPointsRequest = {
    userId: string;
    points: number | string;
    reason: string;
};

export type BalanceDto = {
    balance: number | string;
    lifetimePoints: number | string;
    tier: string;
};

export type CreateAccountRequest = {
    userId: string;
};

export type EarnPointsRequest = {
    userId: string;
    points: number | string;
    type: string;
    referenceId?: null | string;
    description?: null | string;
    userDisplayName?: null | string;
};

export type LoyaltyStatsDto = {
    totalAccounts: number | string;
    accountsByTier: {
        [key: string]: number | string;
    };
    pointsIssuedToday: number | string;
    pointsIssuedThisWeek: number | string;
    pointsIssuedThisMonth: number | string;
};

export type PointsValueDto = {
    points: number | string;
    discountValue: number | string;
    redemptionRate: number | string;
};

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
};

export type TierInfoDto = {
    name: string;
    pointsRequired: number | string;
    benefits: string;
};

export type TransactionDto = {
    id?: number | string;
    points?: number | string;
    type?: string;
    referenceId?: null | string;
    description?: null | string;
    createdAt?: string;
};

export type ListAccountsData = {
    body?: never;
    path?: never;
    query: {
        first?: number | string;
        max?: number | string;
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/loyalty/accounts';
};

export type ListAccountsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type ListAccountsResponses = {
    /**
     * OK
     */
    200: Array<AccountDto>;
};

export type ListAccountsResponse = ListAccountsResponses[keyof ListAccountsResponses];

export type CreateAccountData = {
    body: CreateAccountRequest;
    path?: never;
    query: {
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/loyalty/accounts';
};

export type CreateAccountErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type CreateAccountError = CreateAccountErrors[keyof CreateAccountErrors];

export type CreateAccountResponses = {
    /**
     * Created
     */
    201: AccountDto;
};

export type CreateAccountResponse = CreateAccountResponses[keyof CreateAccountResponses];

export type GetAccountData = {
    body?: never;
    path: {
        /**
         * The user ID
         */
        userId: string;
    };
    query: {
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/loyalty/accounts/{userId}';
};

export type GetAccountErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetAccountResponses = {
    /**
     * OK
     */
    200: AccountDto;
};

export type GetAccountResponse = GetAccountResponses[keyof GetAccountResponses];

export type GetBalanceData = {
    body?: never;
    path: {
        /**
         * The user ID
         */
        userId: string;
    };
    query: {
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/loyalty/accounts/{userId}/balance';
};

export type GetBalanceErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetBalanceResponses = {
    /**
     * OK
     */
    200: BalanceDto;
};

export type GetBalanceResponse = GetBalanceResponses[keyof GetBalanceResponses];

export type GetTransactionsData = {
    body?: never;
    path: {
        /**
         * The user ID
         */
        userId: string;
    };
    query: {
        first?: number | string;
        max?: number | string;
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/loyalty/transactions/{userId}';
};

export type GetTransactionsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetTransactionsResponses = {
    /**
     * OK
     */
    200: Array<TransactionDto>;
};

export type GetTransactionsResponse = GetTransactionsResponses[keyof GetTransactionsResponses];

export type EarnPointsData = {
    body: EarnPointsRequest;
    path?: never;
    query: {
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/loyalty/transactions/earn';
};

export type EarnPointsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type EarnPointsError = EarnPointsErrors[keyof EarnPointsErrors];

export type EarnPointsResponses = {
    /**
     * OK
     */
    200: TransactionDto;
};

export type EarnPointsResponse = EarnPointsResponses[keyof EarnPointsResponses];

export type AdjustPointsData = {
    body: AdjustPointsRequest;
    path?: never;
    query: {
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/loyalty/transactions/adjust';
};

export type AdjustPointsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type AdjustPointsError = AdjustPointsErrors[keyof AdjustPointsErrors];

export type AdjustPointsResponses = {
    /**
     * OK
     */
    200: TransactionDto;
};

export type AdjustPointsResponse = AdjustPointsResponses[keyof AdjustPointsResponses];

export type GetTierInfoData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/loyalty/tiers';
};

export type GetTierInfoResponses = {
    /**
     * OK
     */
    200: Array<TierInfoDto>;
};

export type GetTierInfoResponse = GetTierInfoResponses[keyof GetTierInfoResponses];

export type GetPointsValueData = {
    body?: never;
    path?: never;
    query: {
        points: number | string;
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/loyalty/points-value';
};

export type GetPointsValueResponses = {
    /**
     * OK
     */
    200: PointsValueDto;
};

export type GetPointsValueResponse = GetPointsValueResponses[keyof GetPointsValueResponses];

export type GetStatsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/loyalty/stats';
};

export type GetStatsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetStatsResponses = {
    /**
     * OK
     */
    200: LoyaltyStatsDto;
};

export type GetStatsResponse = GetStatsResponses[keyof GetStatsResponses];
