// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ninja.Tenant.API.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ninja.Tenant.API.Migrations
{
    [DbContext(typeof(TenantContext))]
    [Migration("20260919170712_TenantImageSlots")]
    partial class TenantImageSlots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ninja.Tenant.API.Model.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("DayEndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("DayStartTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOrderingEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReservationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("RequireSignInForTableOrders")
                        .HasColumnType("boolean");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("IsActive");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("Ninja.Tenant.API.Model.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("FinanceEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("InventoryEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("KdsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("LoyaltyEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("PayrollEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<bool>("RoomsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("TabsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Ninja.Tenant.API.Model.Branch", b =>
                {
                    b.OwnsOne("Ninja.Tenant.API.Model.LocalizedText", "Address", b1 =>
                        {
                            b1.Property<int>("BranchId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("BranchId");

                            b1.ToTable("Branches");

                            b1.ToJson("Address");

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.OwnsOne("Ninja.Tenant.API.Model.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<int>("BranchId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("BranchId");

                            b1.ToTable("Branches");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.OwnsOne("Ninja.Tenant.API.Model.LocalizedText", "ReceiptFooter", b1 =>
                        {
                            b1.Property<int>("BranchId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("BranchId");

                            b1.ToTable("Branches");

                            b1.ToJson("ReceiptFooter");

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("ReceiptFooter");
                });

            modelBuilder.Entity("Ninja.Tenant.API.Model.Tenant", b =>
                {
                    b.OwnsOne("Ninja.Tenant.API.Model.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<int>("TenantId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("TenantId");

                            b1.ToTable("Tenants");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.OwnsOne("Ninja.Tenant.API.Model.TenantTheme", "Theme", b1 =>
                        {
                            b1.Property<int>("TenantId");

                            b1.Property<string>("Accent");

                            b1.Property<string>("Background");

                            b1.Property<string>("Font");

                            b1.Property<string>("Foreground");

                            b1.Property<string>("Radius");

                            b1.HasKey("TenantId");

                            b1.ToTable("Tenants");

                            b1.ToJson("Theme");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Theme")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
