// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { ConvertTenantData, ConvertTenantErrors, ConvertTenantResponses, CreateTenantData, CreateTenantErrors, CreateTenantResponses, DeleteTenantBrandImageData, DeleteTenantBrandImageErrors, DeleteTenantBrandImageResponses, DeleteTenantSeedImageData, DeleteTenantSeedImageErrors, DeleteTenantSeedImageResponses, DestroyTenantData, DestroyTenantErrors, DestroyTenantResponses, ExtendDemoData, ExtendDemoErrors, ExtendDemoResponses, GetPlatformCapacityData, GetPlatformCapacityErrors, GetPlatformCapacityResponses, GetPlatformData, GetPlatformErrors, GetPlatformResponses, GetTenantBrandData, GetTenantBrandErrors, GetTenantBrandResponses, GetTenantData, GetTenantErrors, GetTenantResponses, GetTenantSeedImageData, GetTenantSeedImageErrors, ListAuditData, ListAuditErrors, ListAuditResponses, ListTenantsData, ListTenantSeedImagesData, ListTenantSeedImagesErrors, ListTenantSeedImagesResponses, ListTenantsErrors, ListTenantsResponses, ProvisionTenantData, ProvisionTenantErrors, ProvisionTenantResponses, StartTenantData, StartTenantErrors, StartTenantResponses, StopTenantData, StopTenantErrors, StopTenantResponses, TlsAskData, TlsAskErrors, TlsAskResponses, UpdateTenantBrandData, UpdateTenantBrandErrors, UpdateTenantBrandResponses, UpdateTenantData, UpdateTenantErrors, UpdateTenantResponses, UpgradeTenantData, UpgradeTenantErrors, UpgradeTenantResponses, UploadTenantBrandImageData, UploadTenantBrandImageErrors, UploadTenantBrandImageResponses, UploadTenantSeedImageData, UploadTenantSeedImageErrors, UploadTenantSeedImageResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * The platform's domain, counts and room for more
 */
export const getPlatform = <ThrowOnError extends boolean = false>(options?: Options<GetPlatformData, ThrowOnError>): RequestResult<GetPlatformResponses, GetPlatformErrors, ThrowOnError> => (options?.client ?? client).get<GetPlatformResponses, GetPlatformErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/control/platform',
    ...options
});

/**
 * What the box has and what each stack takes; refresh=true reads it now
 */
export const getPlatformCapacity = <ThrowOnError extends boolean = false>(options?: Options<GetPlatformCapacityData, ThrowOnError>): RequestResult<GetPlatformCapacityResponses, GetPlatformCapacityErrors, ThrowOnError> => (options?.client ?? client).get<GetPlatformCapacityResponses, GetPlatformCapacityErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/control/platform/capacity',
    ...options
});

/**
 * Every tenant, newest first
 */
export const listTenants = <ThrowOnError extends boolean = false>(options?: Options<ListTenantsData, ThrowOnError>): RequestResult<ListTenantsResponses, ListTenantsErrors, ThrowOnError> => (options?.client ?? client).get<ListTenantsResponses, ListTenantsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/control/tenants',
    ...options
});

/**
 * Register a tenant and stamp its stack
 */
export const createTenant = <ThrowOnError extends boolean = false>(options: Options<CreateTenantData, ThrowOnError>): RequestResult<CreateTenantResponses, CreateTenantErrors, ThrowOnError> => (options.client ?? client).post<CreateTenantResponses, CreateTenantErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/control/tenants',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Take the stack, realm, vhost and databases down
 */
export const destroyTenant = <ThrowOnError extends boolean = false>(options: Options<DestroyTenantData, ThrowOnError>): RequestResult<DestroyTenantResponses, DestroyTenantErrors, ThrowOnError> => (options.client ?? client).delete<DestroyTenantResponses, DestroyTenantErrors, ThrowOnError>({ url: '/api/control/tenants/{slug}', ...options });

/**
 * One tenant with its latest run
 */
export const getTenant = <ThrowOnError extends boolean = false>(options: Options<GetTenantData, ThrowOnError>): RequestResult<GetTenantResponses, GetTenantErrors, ThrowOnError> => (options.client ?? client).get<GetTenantResponses, GetTenantErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/control/tenants/{slug}',
    ...options
});

/**
 * The record: contact, plan, notes, own domain, and what the next stamp uses
 */
export const updateTenant = <ThrowOnError extends boolean = false>(options: Options<UpdateTenantData, ThrowOnError>): RequestResult<UpdateTenantResponses, UpdateTenantErrors, ThrowOnError> => (options.client ?? client).put<UpdateTenantResponses, UpdateTenantErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/control/tenants/{slug}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Run (or retry) provisioning
 */
export const provisionTenant = <ThrowOnError extends boolean = false>(options: Options<ProvisionTenantData, ThrowOnError>): RequestResult<ProvisionTenantResponses, ProvisionTenantErrors, ThrowOnError> => (options.client ?? client).post<ProvisionTenantResponses, ProvisionTenantErrors, ThrowOnError>({ url: '/api/control/tenants/{slug}/provision', ...options });

export const stopTenant = <ThrowOnError extends boolean = false>(options: Options<StopTenantData, ThrowOnError>): RequestResult<StopTenantResponses, StopTenantErrors, ThrowOnError> => (options.client ?? client).post<StopTenantResponses, StopTenantErrors, ThrowOnError>({ url: '/api/control/tenants/{slug}/stop', ...options });

export const startTenant = <ThrowOnError extends boolean = false>(options: Options<StartTenantData, ThrowOnError>): RequestResult<StartTenantResponses, StartTenantErrors, ThrowOnError> => (options.client ?? client).post<StartTenantResponses, StartTenantErrors, ThrowOnError>({ url: '/api/control/tenants/{slug}/start', ...options });

/**
 * Re-stamp on a tag and pull
 */
export const upgradeTenant = <ThrowOnError extends boolean = false>(options: Options<UpgradeTenantData, ThrowOnError>): RequestResult<UpgradeTenantResponses, UpgradeTenantErrors, ThrowOnError> => (options.client ?? client).post<UpgradeTenantResponses, UpgradeTenantErrors, ThrowOnError>({
    url: '/api/control/tenants/{slug}/upgrade',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Push a demo's expiry out
 */
export const extendDemo = <ThrowOnError extends boolean = false>(options: Options<ExtendDemoData, ThrowOnError>): RequestResult<ExtendDemoResponses, ExtendDemoErrors, ThrowOnError> => (options.client ?? client).post<ExtendDemoResponses, ExtendDemoErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/control/tenants/{slug}/extend',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * The brand as the running stack serves it; image URLs point at the customer host
 */
export const getTenantBrand = <ThrowOnError extends boolean = false>(options: Options<GetTenantBrandData, ThrowOnError>): RequestResult<GetTenantBrandResponses, GetTenantBrandErrors, ThrowOnError> => (options.client ?? client).get<GetTenantBrandResponses, GetTenantBrandErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/control/tenants/{slug}/brand',
    ...options
});

/**
 * Change the name, colors, theme, customer URL or feature switches on the running stack
 */
export const updateTenantBrand = <ThrowOnError extends boolean = false>(options: Options<UpdateTenantBrandData, ThrowOnError>): RequestResult<UpdateTenantBrandResponses, UpdateTenantBrandErrors, ThrowOnError> => (options.client ?? client).put<UpdateTenantBrandResponses, UpdateTenantBrandErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/control/tenants/{slug}/brand',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Remove one image from the running stack
 */
export const deleteTenantBrandImage = <ThrowOnError extends boolean = false>(options: Options<DeleteTenantBrandImageData, ThrowOnError>): RequestResult<DeleteTenantBrandImageResponses, DeleteTenantBrandImageErrors, ThrowOnError> => (options.client ?? client).delete<DeleteTenantBrandImageResponses, DeleteTenantBrandImageErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/control/tenants/{slug}/brand/images/{slot}',
    ...options
});

/**
 * Replace one image on the running stack: logo, logo-dark, wordmark-en, wordmark-en-dark, wordmark-ar or wordmark-ar-dark
 */
export const uploadTenantBrandImage = <ThrowOnError extends boolean = false>(options: Options<UploadTenantBrandImageData, ThrowOnError>): RequestResult<UploadTenantBrandImageResponses, UploadTenantBrandImageErrors, ThrowOnError> => (options.client ?? client).put<UploadTenantBrandImageResponses, UploadTenantBrandImageErrors, ThrowOnError>({
    ...formDataBodySerializer,
    responseType: 'json',
    url: '/api/control/tenants/{slug}/brand/images/{slot}',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * The slots with an image waiting for the next provision
 */
export const listTenantSeedImages = <ThrowOnError extends boolean = false>(options: Options<ListTenantSeedImagesData, ThrowOnError>): RequestResult<ListTenantSeedImagesResponses, ListTenantSeedImagesErrors, ThrowOnError> => (options.client ?? client).get<ListTenantSeedImagesResponses, ListTenantSeedImagesErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/control/tenants/{slug}/seed-images',
    ...options
});

export const deleteTenantSeedImage = <ThrowOnError extends boolean = false>(options: Options<DeleteTenantSeedImageData, ThrowOnError>): RequestResult<DeleteTenantSeedImageResponses, DeleteTenantSeedImageErrors, ThrowOnError> => (options.client ?? client).delete<DeleteTenantSeedImageResponses, DeleteTenantSeedImageErrors, ThrowOnError>({ url: '/api/control/tenants/{slug}/seed-images/{slot}', ...options });

/**
 * One image waiting for the next provision
 */
export const getTenantSeedImage = <ThrowOnError extends boolean = false>(options: Options<GetTenantSeedImageData, ThrowOnError>): RequestResult<unknown, GetTenantSeedImageErrors, ThrowOnError> => (options.client ?? client).get<unknown, GetTenantSeedImageErrors, ThrowOnError>({ url: '/api/control/tenants/{slug}/seed-images/{slot}', ...options });

/**
 * An image the brand step uploads into the stack on the next provision
 */
export const uploadTenantSeedImage = <ThrowOnError extends boolean = false>(options: Options<UploadTenantSeedImageData, ThrowOnError>): RequestResult<UploadTenantSeedImageResponses, UploadTenantSeedImageErrors, ThrowOnError> => (options.client ?? client).put<UploadTenantSeedImageResponses, UploadTenantSeedImageErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/control/tenants/{slug}/seed-images/{slot}',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * A demo becomes a customer: no expiry, on a plan
 */
export const convertTenant = <ThrowOnError extends boolean = false>(options: Options<ConvertTenantData, ThrowOnError>): RequestResult<ConvertTenantResponses, ConvertTenantErrors, ThrowOnError> => (options.client ?? client).post<ConvertTenantResponses, ConvertTenantErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/control/tenants/{slug}/convert',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Every platform action, newest first, for one tenant or all
 */
export const listAudit = <ThrowOnError extends boolean = false>(options?: Options<ListAuditData, ThrowOnError>): RequestResult<ListAuditResponses, ListAuditErrors, ThrowOnError> => (options?.client ?? client).get<ListAuditResponses, ListAuditErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/control/audit',
    ...options
});

/**
 * 200 when the host belongs to a tenant, 404 otherwise
 */
export const tlsAsk = <ThrowOnError extends boolean = false>(options: Options<TlsAskData, ThrowOnError>): RequestResult<TlsAskResponses, TlsAskErrors, ThrowOnError> => (options.client ?? client).get<TlsAskResponses, TlsAskErrors, ThrowOnError>({ url: '/api/control/tls/ask', ...options });
