// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

export type CreateTenantRequest = {
    nameEn: string;
    nameAr: null | string;
    ownerEmail: string;
    kind?: TenantKind;
    slug?: null | string;
    primaryColor?: null | string;
    customerDomain?: null | string;
    demoDays?: null | number | string;
    provision?: null | boolean;
};

export type ExtendRequest = {
    days: number | string;
};

export type IFormFile = Blob | File;

export type PlatformResponse = {
    domain: string;
    defaultImageTag: string;
    demoDays: number | string;
    dryRun: boolean;
    running: number | string;
    total: number | string;
};

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
};

export type StepDto = {
    name: string;
    status: StepStatus;
    startedAt: string;
    finishedAt: null | string;
    output: null | string;
};

export type StepStatus = 'Pending' | 'Running' | 'Done' | 'Failed' | 'Skipped';

export type TenantDetail = {
    slug: string;
    nameEn: string;
    nameAr: null | string;
    kind: TenantKind;
    status: TenantStatus;
    primaryColor: null | string;
    hosts: TenantHostsDto;
    ownerEmail: string;
    ownerInitialPassword: null | string;
    imageTag: string;
    createdAt: string;
    expiresAt: null | string;
    provisionedAt: null | string;
    lastError: null | string;
    steps: Array<StepDto>;
};

export type TenantHostsDto = {
    customer: string;
    admin: string;
    pos: string;
    kds: string;
    api: string;
};

export type TenantKind = 'Demo' | 'Customer';

export type TenantStatus = 'Requested' | 'Provisioning' | 'Running' | 'Stopped' | 'Failed' | 'Destroying' | 'Destroyed';

export type TenantSummary = {
    slug: string;
    nameEn: string;
    nameAr: null | string;
    kind: TenantKind;
    status: TenantStatus;
    customerUrl: string;
    createdAt: string;
    expiresAt: null | string;
    imageTag: string;
    lastError: null | string;
};

export type UpgradeRequest = {
    imageTag: null | string;
};

export type GetPlatformData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/control/platform';
};

export type GetPlatformErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetPlatformResponses = {
    /**
     * OK
     */
    200: PlatformResponse;
};

export type GetPlatformResponse = GetPlatformResponses[keyof GetPlatformResponses];

export type ListTenantsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/control/tenants';
};

export type ListTenantsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type ListTenantsResponses = {
    /**
     * OK
     */
    200: Array<TenantSummary>;
};

export type ListTenantsResponse = ListTenantsResponses[keyof ListTenantsResponses];

export type CreateTenantData = {
    body: CreateTenantRequest;
    path?: never;
    query?: never;
    url: '/api/control/tenants';
};

export type CreateTenantErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type CreateTenantError = CreateTenantErrors[keyof CreateTenantErrors];

export type CreateTenantResponses = {
    /**
     * Created
     */
    201: TenantDetail;
};

export type CreateTenantResponse = CreateTenantResponses[keyof CreateTenantResponses];

export type DestroyTenantData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/control/tenants/{slug}';
};

export type DestroyTenantErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type DestroyTenantError = DestroyTenantErrors[keyof DestroyTenantErrors];

export type DestroyTenantResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetTenantData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/control/tenants/{slug}';
};

export type GetTenantErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetTenantResponses = {
    /**
     * OK
     */
    200: TenantDetail;
};

export type GetTenantResponse = GetTenantResponses[keyof GetTenantResponses];

export type UploadTenantSeedLogoData = {
    body: {
        file: IFormFile;
    };
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/control/tenants/{slug}/logo';
};

export type UploadTenantSeedLogoErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type UploadTenantSeedLogoError = UploadTenantSeedLogoErrors[keyof UploadTenantSeedLogoErrors];

export type UploadTenantSeedLogoResponses = {
    /**
     * No Content
     */
    204: void;
};

export type UploadTenantSeedLogoResponse = UploadTenantSeedLogoResponses[keyof UploadTenantSeedLogoResponses];

export type ProvisionTenantData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/control/tenants/{slug}/provision';
};

export type ProvisionTenantErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type ProvisionTenantError = ProvisionTenantErrors[keyof ProvisionTenantErrors];

export type ProvisionTenantResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type StopTenantData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/control/tenants/{slug}/stop';
};

export type StopTenantErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type StopTenantError = StopTenantErrors[keyof StopTenantErrors];

export type StopTenantResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type StartTenantData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/control/tenants/{slug}/start';
};

export type StartTenantErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type StartTenantError = StartTenantErrors[keyof StartTenantErrors];

export type StartTenantResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type UpgradeTenantData = {
    body?: null | UpgradeRequest;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/control/tenants/{slug}/upgrade';
};

export type UpgradeTenantErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type UpgradeTenantError = UpgradeTenantErrors[keyof UpgradeTenantErrors];

export type UpgradeTenantResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type ExtendDemoData = {
    body: ExtendRequest;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/control/tenants/{slug}/extend';
};

export type ExtendDemoErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type ExtendDemoError = ExtendDemoErrors[keyof ExtendDemoErrors];

export type ExtendDemoResponses = {
    /**
     * OK
     */
    200: TenantDetail;
};

export type ExtendDemoResponse = ExtendDemoResponses[keyof ExtendDemoResponses];

export type TlsAskData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The host Caddy is about to issue a certificate for
         */
        domain: string;
    };
    url: '/api/control/tls/ask';
};

export type TlsAskErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type TlsAskResponses = {
    /**
     * OK
     */
    200: unknown;
};
