// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

export type AttendanceMark = {
    employeeId: number | string;
    status: null | AttendanceStatus;
    note?: null | string;
    overtimeHours?: null | number | string;
};

export type AttendanceStatus = number;

export type AttendanceView = {
    employeeId: number | string;
    date: string;
    branchId: number | string;
    status: AttendanceStatus;
    overtimeHours: number | string;
    note: null | string;
    markedBy: string;
    markedAt: string;
};

export type CreatedResponse = {
    id: number | string;
};

export type EmployeeView = {
    id: number | string;
    name: string;
    jobTitle: null | string;
    phone: null | string;
    branchId: number | string;
    userId: null | string;
    startedOn: string;
    endedOn: null | string;
    isActive: boolean;
    paidDaysOff: number | string;
    currentTerms: null | PayTermsView;
    balance: number | string;
    terms: Array<PayTermsView>;
};

export type GeneratedResponse = {
    ids: Array<number | string>;
};

export type GeneratePayslipsRequest = {
    employeeId: null | number | string;
    periodStart: string;
    periodEnd: string;
};

export type HireEmployeeRequest = {
    name: string;
    jobTitle: null | string;
    phone: null | string;
    branchId: number | string;
    userId: null | string;
    startedOn: string;
    scheme: PayScheme;
    rate: number | string;
    paidDaysOff?: null | number | string;
};

export type LeaveRequest = {
    endedOn: string;
};

export type LedgerEntryRequest = {
    type: LedgerEntryType;
    amount: number | string;
    date: string;
    note: null | string;
};

export type LedgerEntryType = number;

export type LedgerEntryView = {
    id: number | string;
    employeeId: number | string;
    type: LedgerEntryType;
    amount: number | string;
    signed: number | string;
    date: string;
    note: null | string;
    reference: null | string;
    source: LedgerSource;
    recordedBy: string;
    recordedAt: string;
};

export type LedgerSource = number;

export type LedgerView = {
    employeeId: number | string;
    balance: number | string;
    entries: Array<LedgerEntryView>;
};

export type MarkAttendanceRequest = {
    marks: Array<AttendanceMark>;
};

export type PayPayslipRequest = {
    amount: null | number | string;
    note: null | string;
};

export type PayScheme = number;

export type PayslipStatus = number;

export type PayslipView = {
    id: number | string;
    employeeId: number | string;
    employeeName: string;
    branchId: number | string;
    periodStart: string;
    periodEnd: string;
    scheme: PayScheme;
    rate: number | string;
    termsChangedOn: null | string;
    daysWorked: number | string;
    paidOffDays: number | string;
    earned: number | string;
    overtimeHours: number | string;
    overtimePay: number | string;
    absentDays: number | string;
    absenceDeduction: number | string;
    daysOffCarriedIn: number | string;
    daysOffAllowance: number | string;
    daysOffUnused: number | string;
    bonuses: number | string;
    deductions: number | string;
    advances: number | string;
    payments: number | string;
    carriedOver: number | string;
    amountDue: number | string;
    remaining: number | string;
    status: PayslipStatus;
    paidAmount: null | number | string;
    paidAt: null | string;
    paidBy: null | string;
    note: null | string;
    generatedBy: string;
    generatedAt: string;
};

export type PayTermsRequest = {
    scheme: PayScheme;
    rate: number | string;
    effectiveFrom: string;
};

export type PayTermsView = {
    effectiveFrom: string;
    scheme: PayScheme;
    rate: number | string;
};

export type RehireRequest = {
    startedOn: string;
};

export type TillEmployeeView = {
    id: number | string;
    name: string;
    jobTitle: null | string;
    scheme: PayScheme;
};

export type UpdateEmployeeRequest = {
    name: string;
    jobTitle: null | string;
    phone: null | string;
    branchId: number | string;
    userId: null | string;
    paidDaysOff?: null | number | string;
};

export type GetEmployeesData = {
    body?: never;
    path?: never;
    query: {
        includeInactive?: boolean;
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/payroll/employees';
};

export type GetEmployeesErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetEmployeesResponses = {
    /**
     * OK
     */
    200: Array<EmployeeView>;
};

export type GetEmployeesResponse = GetEmployeesResponses[keyof GetEmployeesResponses];

export type HireEmployeeData = {
    body: HireEmployeeRequest;
    headers?: {
        'x-requestid'?: string;
    };
    path?: never;
    query: {
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/payroll/employees';
};

export type HireEmployeeErrors = {
    /**
     * Bad Request
     */
    400: string;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type HireEmployeeError = HireEmployeeErrors[keyof HireEmployeeErrors];

export type HireEmployeeResponses = {
    /**
     * OK
     */
    200: CreatedResponse;
};

export type HireEmployeeResponse = HireEmployeeResponses[keyof HireEmployeeResponses];

export type GetEmployeeData = {
    body?: never;
    path: {
        id: number;
    };
    query: {
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/payroll/employees/{id}';
};

export type GetEmployeeErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetEmployeeResponses = {
    /**
     * OK
     */
    200: EmployeeView;
};

export type GetEmployeeResponse = GetEmployeeResponses[keyof GetEmployeeResponses];

export type UpdateEmployeeData = {
    body: UpdateEmployeeRequest;
    path: {
        id: number;
    };
    query: {
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/payroll/employees/{id}';
};

export type UpdateEmployeeErrors = {
    /**
     * Bad Request
     */
    400: string;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type UpdateEmployeeError = UpdateEmployeeErrors[keyof UpdateEmployeeErrors];

export type UpdateEmployeeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type LeaveEmployeeData = {
    body: LeaveRequest;
    path: {
        id: number;
    };
    query: {
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/payroll/employees/{id}/leave';
};

export type LeaveEmployeeErrors = {
    /**
     * Bad Request
     */
    400: string;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type LeaveEmployeeError = LeaveEmployeeErrors[keyof LeaveEmployeeErrors];

export type LeaveEmployeeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RehireEmployeeData = {
    body: RehireRequest;
    path: {
        id: number;
    };
    query: {
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/payroll/employees/{id}/rehire';
};

export type RehireEmployeeErrors = {
    /**
     * Bad Request
     */
    400: string;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type RehireEmployeeError = RehireEmployeeErrors[keyof RehireEmployeeErrors];

export type RehireEmployeeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetAttendanceData = {
    body?: never;
    path?: never;
    query: {
        from: string;
        to: string;
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/payroll/attendance';
};

export type GetAttendanceErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetAttendanceResponses = {
    /**
     * OK
     */
    200: Array<AttendanceView>;
};

export type GetAttendanceResponse = GetAttendanceResponses[keyof GetAttendanceResponses];

export type MarkAttendanceData = {
    body: MarkAttendanceRequest;
    path: {
        date: string;
    };
    query: {
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/payroll/attendance/{date}';
};

export type MarkAttendanceErrors = {
    /**
     * Bad Request
     */
    400: string;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type MarkAttendanceError = MarkAttendanceErrors[keyof MarkAttendanceErrors];

export type MarkAttendanceResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetEmployeeLedgerData = {
    body?: never;
    path: {
        id: number;
    };
    query: {
        from?: string;
        to?: string;
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/payroll/employees/{id}/ledger';
};

export type GetEmployeeLedgerErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetEmployeeLedgerResponses = {
    /**
     * OK
     */
    200: LedgerView;
};

export type GetEmployeeLedgerResponse = GetEmployeeLedgerResponses[keyof GetEmployeeLedgerResponses];

export type PostLedgerEntryData = {
    body: LedgerEntryRequest;
    headers?: {
        'x-requestid'?: string;
    };
    path: {
        id: number;
    };
    query: {
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/payroll/employees/{id}/ledger';
};

export type PostLedgerEntryErrors = {
    /**
     * Bad Request
     */
    400: string;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type PostLedgerEntryError = PostLedgerEntryErrors[keyof PostLedgerEntryErrors];

export type PostLedgerEntryResponses = {
    /**
     * OK
     */
    200: CreatedResponse;
};

export type PostLedgerEntryResponse = PostLedgerEntryResponses[keyof PostLedgerEntryResponses];

export type GetPayslipsData = {
    body?: never;
    path?: never;
    query: {
        from: string;
        to: string;
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/payroll/payslips';
};

export type GetPayslipsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetPayslipsResponses = {
    /**
     * OK
     */
    200: Array<PayslipView>;
};

export type GetPayslipsResponse = GetPayslipsResponses[keyof GetPayslipsResponses];

export type GeneratePayslipsData = {
    body: GeneratePayslipsRequest;
    headers?: {
        'x-requestid'?: string;
    };
    path?: never;
    query: {
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/payroll/payslips';
};

export type GeneratePayslipsErrors = {
    /**
     * Bad Request
     */
    400: string;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GeneratePayslipsError = GeneratePayslipsErrors[keyof GeneratePayslipsErrors];

export type GeneratePayslipsResponses = {
    /**
     * OK
     */
    200: GeneratedResponse;
};

export type GeneratePayslipsResponse = GeneratePayslipsResponses[keyof GeneratePayslipsResponses];

export type DeletePayslipData = {
    body?: never;
    path: {
        id: number;
    };
    query: {
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/payroll/payslips/{id}';
};

export type DeletePayslipErrors = {
    /**
     * Bad Request
     */
    400: string;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type DeletePayslipError = DeletePayslipErrors[keyof DeletePayslipErrors];

export type DeletePayslipResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetPayslipData = {
    body?: never;
    path: {
        id: number;
    };
    query: {
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/payroll/payslips/{id}';
};

export type GetPayslipErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetPayslipResponses = {
    /**
     * OK
     */
    200: PayslipView;
};

export type GetPayslipResponse = GetPayslipResponses[keyof GetPayslipResponses];

export type PayPayslipData = {
    body: PayPayslipRequest;
    headers?: {
        'x-requestid'?: string;
    };
    path: {
        id: number;
    };
    query: {
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/payroll/payslips/{id}/pay';
};

export type PayPayslipErrors = {
    /**
     * Bad Request
     */
    400: string;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type PayPayslipError = PayPayslipErrors[keyof PayPayslipErrors];

export type PayPayslipResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type SetPayTermsData = {
    body: PayTermsRequest;
    path: {
        id: number;
    };
    query: {
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/payroll/employees/{id}/pay-terms';
};

export type SetPayTermsErrors = {
    /**
     * Bad Request
     */
    400: string;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type SetPayTermsError = SetPayTermsErrors[keyof SetPayTermsErrors];

export type SetPayTermsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetTillEmployeesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/payroll/till/employees';
};

export type GetTillEmployeesErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetTillEmployeesResponses = {
    /**
     * OK
     */
    200: Array<TillEmployeeView>;
};

export type GetTillEmployeesResponse = GetTillEmployeesResponses[keyof GetTillEmployeesResponses];
