// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AdjustPointsData, AdjustPointsErrors, AdjustPointsResponses, CreateAccountData, CreateAccountErrors, CreateAccountResponses, EarnPointsData, EarnPointsErrors, EarnPointsResponses, GetAccountData, GetAccountErrors, GetAccountResponses, GetBalanceData, GetBalanceErrors, GetBalanceResponses, GetPointsValueData, GetPointsValueResponses, GetStatsData, GetStatsErrors, GetStatsResponses, GetTierInfoData, GetTierInfoResponses, GetTransactionsData, GetTransactionsErrors, GetTransactionsResponses, ListAccountsData, ListAccountsErrors, ListAccountsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List all loyalty accounts
 *
 * Get all loyalty accounts (Admin only)
 */
export const listAccounts = <ThrowOnError extends boolean = false>(options: Options<ListAccountsData, ThrowOnError>): RequestResult<ListAccountsResponses, ListAccountsErrors, ThrowOnError> => (options.client ?? client).get<ListAccountsResponses, ListAccountsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/loyalty/accounts',
    ...options
});

/**
 * Create loyalty account
 *
 * Enroll a user in the program — themself, or the back office on their behalf
 */
export const createAccount = <ThrowOnError extends boolean = false>(options: Options<CreateAccountData, ThrowOnError>): RequestResult<CreateAccountResponses, CreateAccountErrors, ThrowOnError> => (options.client ?? client).post<CreateAccountResponses, CreateAccountErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/loyalty/accounts',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get loyalty account
 *
 * Get a loyalty account by user ID — the user themself, or till staff
 */
export const getAccount = <ThrowOnError extends boolean = false>(options: Options<GetAccountData, ThrowOnError>): RequestResult<GetAccountResponses, GetAccountErrors, ThrowOnError> => (options.client ?? client).get<GetAccountResponses, GetAccountErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/loyalty/accounts/{userId}',
    ...options
});

/**
 * Get points balance
 *
 * Get the current points balance for a user — the user themself, or till staff
 */
export const getBalance = <ThrowOnError extends boolean = false>(options: Options<GetBalanceData, ThrowOnError>): RequestResult<GetBalanceResponses, GetBalanceErrors, ThrowOnError> => (options.client ?? client).get<GetBalanceResponses, GetBalanceErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/loyalty/accounts/{userId}/balance',
    ...options
});

/**
 * Get transaction history
 *
 * Get all transactions for a user — the user themself, or till staff
 */
export const getTransactions = <ThrowOnError extends boolean = false>(options: Options<GetTransactionsData, ThrowOnError>): RequestResult<GetTransactionsResponses, GetTransactionsErrors, ThrowOnError> => (options.client ?? client).get<GetTransactionsResponses, GetTransactionsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/loyalty/transactions/{userId}',
    ...options
});

/**
 * Earn points
 *
 * Add points to a user's account (Admin only)
 */
export const earnPoints = <ThrowOnError extends boolean = false>(options: Options<EarnPointsData, ThrowOnError>): RequestResult<EarnPointsResponses, EarnPointsErrors, ThrowOnError> => (options.client ?? client).post<EarnPointsResponses, EarnPointsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/loyalty/transactions/earn',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Adjust points
 *
 * Manual adjustment of points (Admin only)
 */
export const adjustPoints = <ThrowOnError extends boolean = false>(options: Options<AdjustPointsData, ThrowOnError>): RequestResult<AdjustPointsResponses, AdjustPointsErrors, ThrowOnError> => (options.client ?? client).post<AdjustPointsResponses, AdjustPointsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/loyalty/transactions/adjust',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get tier information
 *
 * Get loyalty tier thresholds and benefits
 */
export const getTierInfo = <ThrowOnError extends boolean = false>(options: Options<GetTierInfoData, ThrowOnError>): RequestResult<GetTierInfoResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetTierInfoResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/loyalty/tiers',
    ...options
});

/**
 * Get discount value for points
 *
 * Convert loyalty points to their currency discount value
 */
export const getPointsValue = <ThrowOnError extends boolean = false>(options: Options<GetPointsValueData, ThrowOnError>): RequestResult<GetPointsValueResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetPointsValueResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/loyalty/points-value',
    ...options
});

/**
 * Get loyalty stats
 *
 * Get loyalty program statistics (Admin only)
 */
export const getStats = <ThrowOnError extends boolean = false>(options: Options<GetStatsData, ThrowOnError>): RequestResult<GetStatsResponses, GetStatsErrors, ThrowOnError> => (options.client ?? client).get<GetStatsResponses, GetStatsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/loyalty/stats',
    ...options
});
