default_platform(:android)

platform :android do
  lane :beta do |options|
    build_number = options[:build_number] || ENV['GITHUB_RUN_NUMBER'] || '1'
    track = options[:track] || 'internal'
    app_root = File.expand_path('../..', Dir.pwd)

    # Decode keystore from base64 in CI
    if ENV['CI'] && ENV['ANDROID_KEYSTORE_BASE64']
      sh("echo -n \"$ANDROID_KEYSTORE_BASE64\" | base64 --decode > \"#{app_root}/android/app/upload-keystore.jks\"")
      File.write("#{app_root}/android/key.properties", <<~PROPS)
        storePassword=#{ENV['ANDROID_STORE_PASSWORD']}
        keyPassword=#{ENV['ANDROID_KEY_PASSWORD']}
        keyAlias=#{ENV['ANDROID_KEY_ALIAS']}
        storeFile=upload-keystore.jks
      PROPS
    end

    sh("cd \"#{app_root}\" && flutter build appbundle --release --build-number=#{build_number}")

    supply(
      track: track,
      aab: "#{app_root}/build/app/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      release_status: 'draft',
    )
  end

  lane :upload_metadata do
    supply(
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_images: false,
      skip_upload_screenshots: false,
    )
  end
end
