// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateStockItemData, CreateStockItemErrors, CreateStockItemResponses, GetPurchaseData, GetPurchaseErrors, GetPurchaseResponses, GetPurchasesData, GetPurchasesErrors, GetPurchasesResponses, GetRecipeData, GetRecipeErrors, GetRecipeResponses, GetRecipesData, GetRecipesErrors, GetRecipesResponses, GetStockCountData, GetStockCountErrors, GetStockCountResponses, GetStockCountsData, GetStockCountsErrors, GetStockCountsResponses, GetStockItemData, GetStockItemErrors, GetStockItemResponses, GetStockItemsData, GetStockItemsErrors, GetStockItemsResponses, GetStockLevelsData, GetStockLevelsErrors, GetStockLevelsResponses, GetStockMovementsData, GetStockMovementsErrors, GetStockMovementsResponses, GetTransferData, GetTransferErrors, GetTransferResponses, GetTransfersData, GetTransfersErrors, GetTransfersResponses, GetUsageReportData, GetUsageReportErrors, GetUsageReportResponses, PostStockAdjustmentData, PostStockAdjustmentErrors, PostStockAdjustmentResponses, PostStockCountData, PostStockCountErrors, PostStockCountResponses, RebuildStockLevelsData, RebuildStockLevelsErrors, RebuildStockLevelsResponses, ReceivePurchaseData, ReceivePurchaseErrors, ReceivePurchaseResponses, RemoveRecipeData, RemoveRecipeErrors, RemoveRecipeResponses, SetRecipeData, SetRecipeErrors, SetRecipeResponses, SetReorderLevelData, SetReorderLevelErrors, SetReorderLevelResponses, TrackByUnitData, TrackByUnitErrors, TrackByUnitResponses, TransferStockData, TransferStockErrors, TransferStockResponses, UpdateStockItemData, UpdateStockItemErrors, UpdateStockItemResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Stock items (ingredients and sellable units), active ones unless asked otherwise
 */
export const getStockItems = <ThrowOnError extends boolean = false>(options: Options<GetStockItemsData, ThrowOnError>): RequestResult<GetStockItemsResponses, GetStockItemsErrors, ThrowOnError> => (options.client ?? client).get<GetStockItemsResponses, GetStockItemsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/inventory/items',
    ...options
});

/**
 * Add a stock item
 */
export const createStockItem = <ThrowOnError extends boolean = false>(options: Options<CreateStockItemData, ThrowOnError>): RequestResult<CreateStockItemResponses, CreateStockItemErrors, ThrowOnError> => (options.client ?? client).post<CreateStockItemResponses, CreateStockItemErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/inventory/items',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getStockItem = <ThrowOnError extends boolean = false>(options: Options<GetStockItemData, ThrowOnError>): RequestResult<GetStockItemResponses, GetStockItemErrors, ThrowOnError> => (options.client ?? client).get<GetStockItemResponses, GetStockItemErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/inventory/items/{id}',
    ...options
});

/**
 * Edit a stock item, including retiring it
 */
export const updateStockItem = <ThrowOnError extends boolean = false>(options: Options<UpdateStockItemData, ThrowOnError>): RequestResult<UpdateStockItemResponses, UpdateStockItemErrors, ThrowOnError> => (options.client ?? client).put<UpdateStockItemResponses, UpdateStockItemErrors, ThrowOnError>({
    url: '/api/inventory/items/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Set where the low-stock warning fires for this item at the branch (null clears it)
 */
export const setReorderLevel = <ThrowOnError extends boolean = false>(options: Options<SetReorderLevelData, ThrowOnError>): RequestResult<SetReorderLevelResponses, SetReorderLevelErrors, ThrowOnError> => (options.client ?? client).put<SetReorderLevelResponses, SetReorderLevelErrors, ThrowOnError>({
    url: '/api/inventory/items/{id}/reorder-level',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Every active stock item with what the branch has on hand
 */
export const getStockLevels = <ThrowOnError extends boolean = false>(options: Options<GetStockLevelsData, ThrowOnError>): RequestResult<GetStockLevelsResponses, GetStockLevelsErrors, ThrowOnError> => (options.client ?? client).get<GetStockLevelsResponses, GetStockLevelsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/inventory/levels',
    ...options
});

/**
 * The branch's ledger, newest first, optionally one item or a date range
 */
export const getStockMovements = <ThrowOnError extends boolean = false>(options: Options<GetStockMovementsData, ThrowOnError>): RequestResult<GetStockMovementsResponses, GetStockMovementsErrors, ThrowOnError> => (options.client ?? client).get<GetStockMovementsResponses, GetStockMovementsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/inventory/movements',
    ...options
});

/**
 * Record waste or an adjustment by hand, with a reason
 */
export const postStockAdjustment = <ThrowOnError extends boolean = false>(options: Options<PostStockAdjustmentData, ThrowOnError>): RequestResult<PostStockAdjustmentResponses, PostStockAdjustmentErrors, ThrowOnError> => (options.client ?? client).post<PostStockAdjustmentResponses, PostStockAdjustmentErrors, ThrowOnError>({
    url: '/api/inventory/movements',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Receipts at the branch, newest first
 */
export const getPurchases = <ThrowOnError extends boolean = false>(options: Options<GetPurchasesData, ThrowOnError>): RequestResult<GetPurchasesResponses, GetPurchasesErrors, ThrowOnError> => (options.client ?? client).get<GetPurchasesResponses, GetPurchasesErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/inventory/purchases',
    ...options
});

/**
 * Receive stock into the branch
 *
 * Quantities are in each item's base unit; the unit cost sets the branch's moving average.
 */
export const receivePurchase = <ThrowOnError extends boolean = false>(options: Options<ReceivePurchaseData, ThrowOnError>): RequestResult<ReceivePurchaseResponses, ReceivePurchaseErrors, ThrowOnError> => (options.client ?? client).post<ReceivePurchaseResponses, ReceivePurchaseErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/inventory/purchases',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getPurchase = <ThrowOnError extends boolean = false>(options: Options<GetPurchaseData, ThrowOnError>): RequestResult<GetPurchaseResponses, GetPurchaseErrors, ThrowOnError> => (options.client ?? client).get<GetPurchaseResponses, GetPurchaseErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/inventory/purchases/{id}',
    ...options
});

/**
 * Physical counts at the branch, newest first
 */
export const getStockCounts = <ThrowOnError extends boolean = false>(options: Options<GetStockCountsData, ThrowOnError>): RequestResult<GetStockCountsResponses, GetStockCountsErrors, ThrowOnError> => (options.client ?? client).get<GetStockCountsResponses, GetStockCountsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/inventory/counts',
    ...options
});

/**
 * Post a physical count; the ledger is corrected to what was found
 */
export const postStockCount = <ThrowOnError extends boolean = false>(options: Options<PostStockCountData, ThrowOnError>): RequestResult<PostStockCountResponses, PostStockCountErrors, ThrowOnError> => (options.client ?? client).post<PostStockCountResponses, PostStockCountErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/inventory/counts',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getStockCount = <ThrowOnError extends boolean = false>(options: Options<GetStockCountData, ThrowOnError>): RequestResult<GetStockCountResponses, GetStockCountErrors, ThrowOnError> => (options.client ?? client).get<GetStockCountResponses, GetStockCountErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/inventory/counts/{id}',
    ...options
});

/**
 * Transfers the branch sent or received, newest first
 */
export const getTransfers = <ThrowOnError extends boolean = false>(options: Options<GetTransfersData, ThrowOnError>): RequestResult<GetTransfersResponses, GetTransfersErrors, ThrowOnError> => (options.client ?? client).get<GetTransfersResponses, GetTransfersErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/inventory/transfers',
    ...options
});

export const getTransfer = <ThrowOnError extends boolean = false>(options: Options<GetTransferData, ThrowOnError>): RequestResult<GetTransferResponses, GetTransferErrors, ThrowOnError> => (options.client ?? client).get<GetTransferResponses, GetTransferErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/inventory/transfers/{id}',
    ...options
});

/**
 * Send stock from the branch in X-Branch-Id to another branch
 */
export const transferStock = <ThrowOnError extends boolean = false>(options: Options<TransferStockData, ThrowOnError>): RequestResult<TransferStockResponses, TransferStockErrors, ThrowOnError> => (options.client ?? client).post<TransferStockResponses, TransferStockErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/inventory/transfers/to/{branchId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * What each stock item did over a period, valued at posting cost, plus the stock value now
 */
export const getUsageReport = <ThrowOnError extends boolean = false>(options: Options<GetUsageReportData, ThrowOnError>): RequestResult<GetUsageReportResponses, GetUsageReportErrors, ThrowOnError> => (options.client ?? client).get<GetUsageReportResponses, GetUsageReportErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/inventory/reports/usage',
    ...options
});

/**
 * Recompute the branch's levels from its ledger
 */
export const rebuildStockLevels = <ThrowOnError extends boolean = false>(options: Options<RebuildStockLevelsData, ThrowOnError>): RequestResult<RebuildStockLevelsResponses, RebuildStockLevelsErrors, ThrowOnError> => (options.client ?? client).post<RebuildStockLevelsResponses, RebuildStockLevelsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/inventory/levels/rebuild',
    ...options
});

/**
 * Every tracked menu item and what one unit takes
 */
export const getRecipes = <ThrowOnError extends boolean = false>(options: Options<GetRecipesData, ThrowOnError>): RequestResult<GetRecipesResponses, GetRecipesErrors, ThrowOnError> => (options.client ?? client).get<GetRecipesResponses, GetRecipesErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/inventory/recipes',
    ...options
});

/**
 * Stop tracking a menu item
 */
export const removeRecipe = <ThrowOnError extends boolean = false>(options: Options<RemoveRecipeData, ThrowOnError>): RequestResult<RemoveRecipeResponses, RemoveRecipeErrors, ThrowOnError> => (options.client ?? client).delete<RemoveRecipeResponses, RemoveRecipeErrors, ThrowOnError>({ url: '/api/inventory/recipes/{catalogItemId}', ...options });

export const getRecipe = <ThrowOnError extends boolean = false>(options: Options<GetRecipeData, ThrowOnError>): RequestResult<GetRecipeResponses, GetRecipeErrors, ThrowOnError> => (options.client ?? client).get<GetRecipeResponses, GetRecipeErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/inventory/recipes/{catalogItemId}',
    ...options
});

/**
 * Set a menu item's recipe (starts tracking it)
 */
export const setRecipe = <ThrowOnError extends boolean = false>(options: Options<SetRecipeData, ThrowOnError>): RequestResult<SetRecipeResponses, SetRecipeErrors, ThrowOnError> => (options.client ?? client).put<SetRecipeResponses, SetRecipeErrors, ThrowOnError>({
    url: '/api/inventory/recipes/{catalogItemId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Track a menu item sold as-is: one stock item, one each, sells out when it runs dry
 */
export const trackByUnit = <ThrowOnError extends boolean = false>(options: Options<TrackByUnitData, ThrowOnError>): RequestResult<TrackByUnitResponses, TrackByUnitErrors, ThrowOnError> => (options.client ?? client).post<TrackByUnitResponses, TrackByUnitErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/inventory/recipes/track-by-unit',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
