/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignedOutRouteImport } from './routes/(auth)/signed-out'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedTillIndexRouteImport } from './routes/_authenticated/till/index'
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated/staff/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedRequestsIndexRouteImport } from './routes/_authenticated/requests/index'
import { Route as AuthenticatedPromosIndexRouteImport } from './routes/_authenticated/promos/index'
import { Route as AuthenticatedPlacesIndexRouteImport } from './routes/_authenticated/places/index'
import { Route as AuthenticatedPaymentsIndexRouteImport } from './routes/_authenticated/payments/index'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders/index'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications/index'
import { Route as AuthenticatedMenuIndexRouteImport } from './routes/_authenticated/menu/index'
import { Route as AuthenticatedLoyaltyIndexRouteImport } from './routes/_authenticated/loyalty/index'
import { Route as AuthenticatedInventoryIndexRouteImport } from './routes/_authenticated/inventory/index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedBrandIndexRouteImport } from './routes/_authenticated/brand/index'
import { Route as AuthenticatedBranchesIndexRouteImport } from './routes/_authenticated/branches/index'
import { Route as AuthenticatedBillsIndexRouteImport } from './routes/_authenticated/bills/index'
import { Route as AuthenticatedAssistantIndexRouteImport } from './routes/_authenticated/assistant/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedAccountsIndexRouteImport } from './routes/_authenticated/accounts/index'
import { Route as AuthenticatedTillTicketsRouteImport } from './routes/_authenticated/till/tickets'
import { Route as AuthenticatedTillShiftsRouteImport } from './routes/_authenticated/till/shifts'
import { Route as AuthenticatedTillRefundsRouteImport } from './routes/_authenticated/till/refunds'
import { Route as AuthenticatedTillPaymentsRouteImport } from './routes/_authenticated/till/payments'
import { Route as AuthenticatedTillBreakdownRouteImport } from './routes/_authenticated/till/breakdown'
import { Route as AuthenticatedPlacesReservationsRouteImport } from './routes/_authenticated/places/reservations'
import { Route as AuthenticatedPlacesPrintRouteImport } from './routes/_authenticated/places/print'
import { Route as AuthenticatedPlacesHistoryRouteImport } from './routes/_authenticated/places/history'
import { Route as AuthenticatedPayrollPayslipsRouteImport } from './routes/_authenticated/payroll/payslips'
import { Route as AuthenticatedPayrollEmployeesRouteImport } from './routes/_authenticated/payroll/employees'
import { Route as AuthenticatedPayrollAttendanceRouteImport } from './routes/_authenticated/payroll/attendance'
import { Route as AuthenticatedOrdersHistoryRouteImport } from './routes/_authenticated/orders/history'
import { Route as AuthenticatedInventoryReportsRouteImport } from './routes/_authenticated/inventory/reports'
import { Route as AuthenticatedInventoryMenuCostRouteImport } from './routes/_authenticated/inventory/menu-cost'
import { Route as AuthenticatedFinanceSuppliersRouteImport } from './routes/_authenticated/finance/suppliers'
import { Route as AuthenticatedFinanceProfitRouteImport } from './routes/_authenticated/finance/profit'
import { Route as AuthenticatedFinancePartnersRouteImport } from './routes/_authenticated/finance/partners'
import { Route as AuthenticatedFinanceExpensesRouteImport } from './routes/_authenticated/finance/expenses'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedInventoryHistoryIndexRouteImport } from './routes/_authenticated/inventory/history/index'
import { Route as AuthenticatedInventoryHistoryTransfersRouteImport } from './routes/_authenticated/inventory/history/transfers'
import { Route as AuthenticatedInventoryHistoryPurchasesRouteImport } from './routes/_authenticated/inventory/history/purchases'
import { Route as AuthenticatedInventoryHistoryCountsRouteImport } from './routes/_authenticated/inventory/history/counts'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignedOutRoute = authSignedOutRouteImport.update({
  id: '/(auth)/signed-out',
  path: '/signed-out',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTillIndexRoute = AuthenticatedTillIndexRouteImport.update({
  id: '/till/',
  path: '/till/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRequestsIndexRoute =
  AuthenticatedRequestsIndexRouteImport.update({
    id: '/requests/',
    path: '/requests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPromosIndexRoute =
  AuthenticatedPromosIndexRouteImport.update({
    id: '/promos/',
    path: '/promos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlacesIndexRoute =
  AuthenticatedPlacesIndexRouteImport.update({
    id: '/places/',
    path: '/places/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsIndexRoute =
  AuthenticatedPaymentsIndexRouteImport.update({
    id: '/payments/',
    path: '/payments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMenuIndexRoute = AuthenticatedMenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLoyaltyIndexRoute =
  AuthenticatedLoyaltyIndexRouteImport.update({
    id: '/loyalty/',
    path: '/loyalty/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryIndexRoute =
  AuthenticatedInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBrandIndexRoute = AuthenticatedBrandIndexRouteImport.update({
  id: '/brand/',
  path: '/brand/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBranchesIndexRoute =
  AuthenticatedBranchesIndexRouteImport.update({
    id: '/branches/',
    path: '/branches/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillsIndexRoute = AuthenticatedBillsIndexRouteImport.update({
  id: '/bills/',
  path: '/bills/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantIndexRoute =
  AuthenticatedAssistantIndexRouteImport.update({
    id: '/assistant/',
    path: '/assistant/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountsIndexRoute =
  AuthenticatedAccountsIndexRouteImport.update({
    id: '/accounts/',
    path: '/accounts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTillTicketsRoute =
  AuthenticatedTillTicketsRouteImport.update({
    id: '/till/tickets',
    path: '/till/tickets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTillShiftsRoute = AuthenticatedTillShiftsRouteImport.update({
  id: '/till/shifts',
  path: '/till/shifts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTillRefundsRoute =
  AuthenticatedTillRefundsRouteImport.update({
    id: '/till/refunds',
    path: '/till/refunds',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTillPaymentsRoute =
  AuthenticatedTillPaymentsRouteImport.update({
    id: '/till/payments',
    path: '/till/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTillBreakdownRoute =
  AuthenticatedTillBreakdownRouteImport.update({
    id: '/till/breakdown',
    path: '/till/breakdown',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlacesReservationsRoute =
  AuthenticatedPlacesReservationsRouteImport.update({
    id: '/places/reservations',
    path: '/places/reservations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlacesPrintRoute =
  AuthenticatedPlacesPrintRouteImport.update({
    id: '/places/print',
    path: '/places/print',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlacesHistoryRoute =
  AuthenticatedPlacesHistoryRouteImport.update({
    id: '/places/history',
    path: '/places/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPayrollPayslipsRoute =
  AuthenticatedPayrollPayslipsRouteImport.update({
    id: '/payroll/payslips',
    path: '/payroll/payslips',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPayrollEmployeesRoute =
  AuthenticatedPayrollEmployeesRouteImport.update({
    id: '/payroll/employees',
    path: '/payroll/employees',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPayrollAttendanceRoute =
  AuthenticatedPayrollAttendanceRouteImport.update({
    id: '/payroll/attendance',
    path: '/payroll/attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersHistoryRoute =
  AuthenticatedOrdersHistoryRouteImport.update({
    id: '/orders/history',
    path: '/orders/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryReportsRoute =
  AuthenticatedInventoryReportsRouteImport.update({
    id: '/inventory/reports',
    path: '/inventory/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryMenuCostRoute =
  AuthenticatedInventoryMenuCostRouteImport.update({
    id: '/inventory/menu-cost',
    path: '/inventory/menu-cost',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceSuppliersRoute =
  AuthenticatedFinanceSuppliersRouteImport.update({
    id: '/finance/suppliers',
    path: '/finance/suppliers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceProfitRoute =
  AuthenticatedFinanceProfitRouteImport.update({
    id: '/finance/profit',
    path: '/finance/profit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinancePartnersRoute =
  AuthenticatedFinancePartnersRouteImport.update({
    id: '/finance/partners',
    path: '/finance/partners',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceExpensesRoute =
  AuthenticatedFinanceExpensesRouteImport.update({
    id: '/finance/expenses',
    path: '/finance/expenses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryHistoryIndexRoute =
  AuthenticatedInventoryHistoryIndexRouteImport.update({
    id: '/inventory/history/',
    path: '/inventory/history/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryHistoryTransfersRoute =
  AuthenticatedInventoryHistoryTransfersRouteImport.update({
    id: '/inventory/history/transfers',
    path: '/inventory/history/transfers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryHistoryPurchasesRoute =
  AuthenticatedInventoryHistoryPurchasesRouteImport.update({
    id: '/inventory/history/purchases',
    path: '/inventory/history/purchases',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryHistoryCountsRoute =
  AuthenticatedInventoryHistoryCountsRouteImport.update({
    id: '/inventory/history/counts',
    path: '/inventory/history/counts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof authSignInRoute
  '/signed-out': typeof authSignedOutRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/finance/expenses': typeof AuthenticatedFinanceExpensesRoute
  '/finance/partners': typeof AuthenticatedFinancePartnersRoute
  '/finance/profit': typeof AuthenticatedFinanceProfitRoute
  '/finance/suppliers': typeof AuthenticatedFinanceSuppliersRoute
  '/inventory/menu-cost': typeof AuthenticatedInventoryMenuCostRoute
  '/inventory/reports': typeof AuthenticatedInventoryReportsRoute
  '/orders/history': typeof AuthenticatedOrdersHistoryRoute
  '/payroll/attendance': typeof AuthenticatedPayrollAttendanceRoute
  '/payroll/employees': typeof AuthenticatedPayrollEmployeesRoute
  '/payroll/payslips': typeof AuthenticatedPayrollPayslipsRoute
  '/places/history': typeof AuthenticatedPlacesHistoryRoute
  '/places/print': typeof AuthenticatedPlacesPrintRoute
  '/places/reservations': typeof AuthenticatedPlacesReservationsRoute
  '/till/breakdown': typeof AuthenticatedTillBreakdownRoute
  '/till/payments': typeof AuthenticatedTillPaymentsRoute
  '/till/refunds': typeof AuthenticatedTillRefundsRoute
  '/till/shifts': typeof AuthenticatedTillShiftsRoute
  '/till/tickets': typeof AuthenticatedTillTicketsRoute
  '/accounts': typeof AuthenticatedAccountsIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/assistant': typeof AuthenticatedAssistantIndexRoute
  '/bills': typeof AuthenticatedBillsIndexRoute
  '/branches': typeof AuthenticatedBranchesIndexRoute
  '/brand': typeof AuthenticatedBrandIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
  '/loyalty': typeof AuthenticatedLoyaltyIndexRoute
  '/menu': typeof AuthenticatedMenuIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/payments': typeof AuthenticatedPaymentsIndexRoute
  '/places': typeof AuthenticatedPlacesIndexRoute
  '/promos': typeof AuthenticatedPromosIndexRoute
  '/requests': typeof AuthenticatedRequestsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
  '/till': typeof AuthenticatedTillIndexRoute
  '/inventory/history/counts': typeof AuthenticatedInventoryHistoryCountsRoute
  '/inventory/history/purchases': typeof AuthenticatedInventoryHistoryPurchasesRoute
  '/inventory/history/transfers': typeof AuthenticatedInventoryHistoryTransfersRoute
  '/inventory/history': typeof AuthenticatedInventoryHistoryIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/signed-out': typeof authSignedOutRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/finance/expenses': typeof AuthenticatedFinanceExpensesRoute
  '/finance/partners': typeof AuthenticatedFinancePartnersRoute
  '/finance/profit': typeof AuthenticatedFinanceProfitRoute
  '/finance/suppliers': typeof AuthenticatedFinanceSuppliersRoute
  '/inventory/menu-cost': typeof AuthenticatedInventoryMenuCostRoute
  '/inventory/reports': typeof AuthenticatedInventoryReportsRoute
  '/orders/history': typeof AuthenticatedOrdersHistoryRoute
  '/payroll/attendance': typeof AuthenticatedPayrollAttendanceRoute
  '/payroll/employees': typeof AuthenticatedPayrollEmployeesRoute
  '/payroll/payslips': typeof AuthenticatedPayrollPayslipsRoute
  '/places/history': typeof AuthenticatedPlacesHistoryRoute
  '/places/print': typeof AuthenticatedPlacesPrintRoute
  '/places/reservations': typeof AuthenticatedPlacesReservationsRoute
  '/till/breakdown': typeof AuthenticatedTillBreakdownRoute
  '/till/payments': typeof AuthenticatedTillPaymentsRoute
  '/till/refunds': typeof AuthenticatedTillRefundsRoute
  '/till/shifts': typeof AuthenticatedTillShiftsRoute
  '/till/tickets': typeof AuthenticatedTillTicketsRoute
  '/accounts': typeof AuthenticatedAccountsIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/assistant': typeof AuthenticatedAssistantIndexRoute
  '/bills': typeof AuthenticatedBillsIndexRoute
  '/branches': typeof AuthenticatedBranchesIndexRoute
  '/brand': typeof AuthenticatedBrandIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
  '/loyalty': typeof AuthenticatedLoyaltyIndexRoute
  '/menu': typeof AuthenticatedMenuIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/payments': typeof AuthenticatedPaymentsIndexRoute
  '/places': typeof AuthenticatedPlacesIndexRoute
  '/promos': typeof AuthenticatedPromosIndexRoute
  '/requests': typeof AuthenticatedRequestsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
  '/till': typeof AuthenticatedTillIndexRoute
  '/inventory/history/counts': typeof AuthenticatedInventoryHistoryCountsRoute
  '/inventory/history/purchases': typeof AuthenticatedInventoryHistoryPurchasesRoute
  '/inventory/history/transfers': typeof AuthenticatedInventoryHistoryTransfersRoute
  '/inventory/history': typeof AuthenticatedInventoryHistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/signed-out': typeof authSignedOutRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/finance/expenses': typeof AuthenticatedFinanceExpensesRoute
  '/_authenticated/finance/partners': typeof AuthenticatedFinancePartnersRoute
  '/_authenticated/finance/profit': typeof AuthenticatedFinanceProfitRoute
  '/_authenticated/finance/suppliers': typeof AuthenticatedFinanceSuppliersRoute
  '/_authenticated/inventory/menu-cost': typeof AuthenticatedInventoryMenuCostRoute
  '/_authenticated/inventory/reports': typeof AuthenticatedInventoryReportsRoute
  '/_authenticated/orders/history': typeof AuthenticatedOrdersHistoryRoute
  '/_authenticated/payroll/attendance': typeof AuthenticatedPayrollAttendanceRoute
  '/_authenticated/payroll/employees': typeof AuthenticatedPayrollEmployeesRoute
  '/_authenticated/payroll/payslips': typeof AuthenticatedPayrollPayslipsRoute
  '/_authenticated/places/history': typeof AuthenticatedPlacesHistoryRoute
  '/_authenticated/places/print': typeof AuthenticatedPlacesPrintRoute
  '/_authenticated/places/reservations': typeof AuthenticatedPlacesReservationsRoute
  '/_authenticated/till/breakdown': typeof AuthenticatedTillBreakdownRoute
  '/_authenticated/till/payments': typeof AuthenticatedTillPaymentsRoute
  '/_authenticated/till/refunds': typeof AuthenticatedTillRefundsRoute
  '/_authenticated/till/shifts': typeof AuthenticatedTillShiftsRoute
  '/_authenticated/till/tickets': typeof AuthenticatedTillTicketsRoute
  '/_authenticated/accounts/': typeof AuthenticatedAccountsIndexRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/assistant/': typeof AuthenticatedAssistantIndexRoute
  '/_authenticated/bills/': typeof AuthenticatedBillsIndexRoute
  '/_authenticated/branches/': typeof AuthenticatedBranchesIndexRoute
  '/_authenticated/brand/': typeof AuthenticatedBrandIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/_authenticated/loyalty/': typeof AuthenticatedLoyaltyIndexRoute
  '/_authenticated/menu/': typeof AuthenticatedMenuIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/_authenticated/places/': typeof AuthenticatedPlacesIndexRoute
  '/_authenticated/promos/': typeof AuthenticatedPromosIndexRoute
  '/_authenticated/requests/': typeof AuthenticatedRequestsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
  '/_authenticated/till/': typeof AuthenticatedTillIndexRoute
  '/_authenticated/inventory/history/counts': typeof AuthenticatedInventoryHistoryCountsRoute
  '/_authenticated/inventory/history/purchases': typeof AuthenticatedInventoryHistoryPurchasesRoute
  '/_authenticated/inventory/history/transfers': typeof AuthenticatedInventoryHistoryTransfersRoute
  '/_authenticated/inventory/history/': typeof AuthenticatedInventoryHistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sign-in'
    | '/signed-out'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/auth/callback'
    | '/'
    | '/errors/$error'
    | '/finance/expenses'
    | '/finance/partners'
    | '/finance/profit'
    | '/finance/suppliers'
    | '/inventory/menu-cost'
    | '/inventory/reports'
    | '/orders/history'
    | '/payroll/attendance'
    | '/payroll/employees'
    | '/payroll/payslips'
    | '/places/history'
    | '/places/print'
    | '/places/reservations'
    | '/till/breakdown'
    | '/till/payments'
    | '/till/refunds'
    | '/till/shifts'
    | '/till/tickets'
    | '/accounts'
    | '/apps'
    | '/assistant'
    | '/bills'
    | '/branches'
    | '/brand'
    | '/customers'
    | '/inventory'
    | '/loyalty'
    | '/menu'
    | '/notifications'
    | '/orders'
    | '/payments'
    | '/places'
    | '/promos'
    | '/requests'
    | '/settings'
    | '/staff'
    | '/till'
    | '/inventory/history/counts'
    | '/inventory/history/purchases'
    | '/inventory/history/transfers'
    | '/inventory/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/signed-out'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/auth/callback'
    | '/'
    | '/errors/$error'
    | '/finance/expenses'
    | '/finance/partners'
    | '/finance/profit'
    | '/finance/suppliers'
    | '/inventory/menu-cost'
    | '/inventory/reports'
    | '/orders/history'
    | '/payroll/attendance'
    | '/payroll/employees'
    | '/payroll/payslips'
    | '/places/history'
    | '/places/print'
    | '/places/reservations'
    | '/till/breakdown'
    | '/till/payments'
    | '/till/refunds'
    | '/till/shifts'
    | '/till/tickets'
    | '/accounts'
    | '/apps'
    | '/assistant'
    | '/bills'
    | '/branches'
    | '/brand'
    | '/customers'
    | '/inventory'
    | '/loyalty'
    | '/menu'
    | '/notifications'
    | '/orders'
    | '/payments'
    | '/places'
    | '/promos'
    | '/requests'
    | '/settings'
    | '/staff'
    | '/till'
    | '/inventory/history/counts'
    | '/inventory/history/purchases'
    | '/inventory/history/transfers'
    | '/inventory/history'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/sign-in'
    | '/(auth)/signed-out'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/auth/callback'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/finance/expenses'
    | '/_authenticated/finance/partners'
    | '/_authenticated/finance/profit'
    | '/_authenticated/finance/suppliers'
    | '/_authenticated/inventory/menu-cost'
    | '/_authenticated/inventory/reports'
    | '/_authenticated/orders/history'
    | '/_authenticated/payroll/attendance'
    | '/_authenticated/payroll/employees'
    | '/_authenticated/payroll/payslips'
    | '/_authenticated/places/history'
    | '/_authenticated/places/print'
    | '/_authenticated/places/reservations'
    | '/_authenticated/till/breakdown'
    | '/_authenticated/till/payments'
    | '/_authenticated/till/refunds'
    | '/_authenticated/till/shifts'
    | '/_authenticated/till/tickets'
    | '/_authenticated/accounts/'
    | '/_authenticated/apps/'
    | '/_authenticated/assistant/'
    | '/_authenticated/bills/'
    | '/_authenticated/branches/'
    | '/_authenticated/brand/'
    | '/_authenticated/customers/'
    | '/_authenticated/inventory/'
    | '/_authenticated/loyalty/'
    | '/_authenticated/menu/'
    | '/_authenticated/notifications/'
    | '/_authenticated/orders/'
    | '/_authenticated/payments/'
    | '/_authenticated/places/'
    | '/_authenticated/promos/'
    | '/_authenticated/requests/'
    | '/_authenticated/settings/'
    | '/_authenticated/staff/'
    | '/_authenticated/till/'
    | '/_authenticated/inventory/history/counts'
    | '/_authenticated/inventory/history/purchases'
    | '/_authenticated/inventory/history/transfers'
    | '/_authenticated/inventory/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  authSignedOutRoute: typeof authSignedOutRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signed-out': {
      id: '/(auth)/signed-out'
      path: '/signed-out'
      fullPath: '/signed-out'
      preLoaderRoute: typeof authSignedOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/till/': {
      id: '/_authenticated/till/'
      path: '/till'
      fullPath: '/till'
      preLoaderRoute: typeof AuthenticatedTillIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests/': {
      id: '/_authenticated/requests/'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promos/': {
      id: '/_authenticated/promos/'
      path: '/promos'
      fullPath: '/promos'
      preLoaderRoute: typeof AuthenticatedPromosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/places/': {
      id: '/_authenticated/places/'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof AuthenticatedPlacesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments/': {
      id: '/_authenticated/payments/'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menu/': {
      id: '/_authenticated/menu/'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthenticatedMenuIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loyalty/': {
      id: '/_authenticated/loyalty/'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof AuthenticatedLoyaltyIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/': {
      id: '/_authenticated/inventory/'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brand/': {
      id: '/_authenticated/brand/'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof AuthenticatedBrandIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/branches/': {
      id: '/_authenticated/branches/'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AuthenticatedBranchesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bills/': {
      id: '/_authenticated/bills/'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof AuthenticatedBillsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant/': {
      id: '/_authenticated/assistant/'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/': {
      id: '/_authenticated/accounts/'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/till/tickets': {
      id: '/_authenticated/till/tickets'
      path: '/till/tickets'
      fullPath: '/till/tickets'
      preLoaderRoute: typeof AuthenticatedTillTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/till/shifts': {
      id: '/_authenticated/till/shifts'
      path: '/till/shifts'
      fullPath: '/till/shifts'
      preLoaderRoute: typeof AuthenticatedTillShiftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/till/refunds': {
      id: '/_authenticated/till/refunds'
      path: '/till/refunds'
      fullPath: '/till/refunds'
      preLoaderRoute: typeof AuthenticatedTillRefundsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/till/payments': {
      id: '/_authenticated/till/payments'
      path: '/till/payments'
      fullPath: '/till/payments'
      preLoaderRoute: typeof AuthenticatedTillPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/till/breakdown': {
      id: '/_authenticated/till/breakdown'
      path: '/till/breakdown'
      fullPath: '/till/breakdown'
      preLoaderRoute: typeof AuthenticatedTillBreakdownRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/places/reservations': {
      id: '/_authenticated/places/reservations'
      path: '/places/reservations'
      fullPath: '/places/reservations'
      preLoaderRoute: typeof AuthenticatedPlacesReservationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/places/print': {
      id: '/_authenticated/places/print'
      path: '/places/print'
      fullPath: '/places/print'
      preLoaderRoute: typeof AuthenticatedPlacesPrintRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/places/history': {
      id: '/_authenticated/places/history'
      path: '/places/history'
      fullPath: '/places/history'
      preLoaderRoute: typeof AuthenticatedPlacesHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll/payslips': {
      id: '/_authenticated/payroll/payslips'
      path: '/payroll/payslips'
      fullPath: '/payroll/payslips'
      preLoaderRoute: typeof AuthenticatedPayrollPayslipsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll/employees': {
      id: '/_authenticated/payroll/employees'
      path: '/payroll/employees'
      fullPath: '/payroll/employees'
      preLoaderRoute: typeof AuthenticatedPayrollEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll/attendance': {
      id: '/_authenticated/payroll/attendance'
      path: '/payroll/attendance'
      fullPath: '/payroll/attendance'
      preLoaderRoute: typeof AuthenticatedPayrollAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/history': {
      id: '/_authenticated/orders/history'
      path: '/orders/history'
      fullPath: '/orders/history'
      preLoaderRoute: typeof AuthenticatedOrdersHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/reports': {
      id: '/_authenticated/inventory/reports'
      path: '/inventory/reports'
      fullPath: '/inventory/reports'
      preLoaderRoute: typeof AuthenticatedInventoryReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/menu-cost': {
      id: '/_authenticated/inventory/menu-cost'
      path: '/inventory/menu-cost'
      fullPath: '/inventory/menu-cost'
      preLoaderRoute: typeof AuthenticatedInventoryMenuCostRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/suppliers': {
      id: '/_authenticated/finance/suppliers'
      path: '/finance/suppliers'
      fullPath: '/finance/suppliers'
      preLoaderRoute: typeof AuthenticatedFinanceSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/profit': {
      id: '/_authenticated/finance/profit'
      path: '/finance/profit'
      fullPath: '/finance/profit'
      preLoaderRoute: typeof AuthenticatedFinanceProfitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/partners': {
      id: '/_authenticated/finance/partners'
      path: '/finance/partners'
      fullPath: '/finance/partners'
      preLoaderRoute: typeof AuthenticatedFinancePartnersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/expenses': {
      id: '/_authenticated/finance/expenses'
      path: '/finance/expenses'
      fullPath: '/finance/expenses'
      preLoaderRoute: typeof AuthenticatedFinanceExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/history/': {
      id: '/_authenticated/inventory/history/'
      path: '/inventory/history'
      fullPath: '/inventory/history'
      preLoaderRoute: typeof AuthenticatedInventoryHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/history/transfers': {
      id: '/_authenticated/inventory/history/transfers'
      path: '/inventory/history/transfers'
      fullPath: '/inventory/history/transfers'
      preLoaderRoute: typeof AuthenticatedInventoryHistoryTransfersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/history/purchases': {
      id: '/_authenticated/inventory/history/purchases'
      path: '/inventory/history/purchases'
      fullPath: '/inventory/history/purchases'
      preLoaderRoute: typeof AuthenticatedInventoryHistoryPurchasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/history/counts': {
      id: '/_authenticated/inventory/history/counts'
      path: '/inventory/history/counts'
      fullPath: '/inventory/history/counts'
      preLoaderRoute: typeof AuthenticatedInventoryHistoryCountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedFinanceExpensesRoute: typeof AuthenticatedFinanceExpensesRoute
  AuthenticatedFinancePartnersRoute: typeof AuthenticatedFinancePartnersRoute
  AuthenticatedFinanceProfitRoute: typeof AuthenticatedFinanceProfitRoute
  AuthenticatedFinanceSuppliersRoute: typeof AuthenticatedFinanceSuppliersRoute
  AuthenticatedInventoryMenuCostRoute: typeof AuthenticatedInventoryMenuCostRoute
  AuthenticatedInventoryReportsRoute: typeof AuthenticatedInventoryReportsRoute
  AuthenticatedOrdersHistoryRoute: typeof AuthenticatedOrdersHistoryRoute
  AuthenticatedPayrollAttendanceRoute: typeof AuthenticatedPayrollAttendanceRoute
  AuthenticatedPayrollEmployeesRoute: typeof AuthenticatedPayrollEmployeesRoute
  AuthenticatedPayrollPayslipsRoute: typeof AuthenticatedPayrollPayslipsRoute
  AuthenticatedPlacesHistoryRoute: typeof AuthenticatedPlacesHistoryRoute
  AuthenticatedPlacesPrintRoute: typeof AuthenticatedPlacesPrintRoute
  AuthenticatedPlacesReservationsRoute: typeof AuthenticatedPlacesReservationsRoute
  AuthenticatedTillBreakdownRoute: typeof AuthenticatedTillBreakdownRoute
  AuthenticatedTillPaymentsRoute: typeof AuthenticatedTillPaymentsRoute
  AuthenticatedTillRefundsRoute: typeof AuthenticatedTillRefundsRoute
  AuthenticatedTillShiftsRoute: typeof AuthenticatedTillShiftsRoute
  AuthenticatedTillTicketsRoute: typeof AuthenticatedTillTicketsRoute
  AuthenticatedAccountsIndexRoute: typeof AuthenticatedAccountsIndexRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedAssistantIndexRoute: typeof AuthenticatedAssistantIndexRoute
  AuthenticatedBillsIndexRoute: typeof AuthenticatedBillsIndexRoute
  AuthenticatedBranchesIndexRoute: typeof AuthenticatedBranchesIndexRoute
  AuthenticatedBrandIndexRoute: typeof AuthenticatedBrandIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedInventoryIndexRoute: typeof AuthenticatedInventoryIndexRoute
  AuthenticatedLoyaltyIndexRoute: typeof AuthenticatedLoyaltyIndexRoute
  AuthenticatedMenuIndexRoute: typeof AuthenticatedMenuIndexRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
  AuthenticatedPaymentsIndexRoute: typeof AuthenticatedPaymentsIndexRoute
  AuthenticatedPlacesIndexRoute: typeof AuthenticatedPlacesIndexRoute
  AuthenticatedPromosIndexRoute: typeof AuthenticatedPromosIndexRoute
  AuthenticatedRequestsIndexRoute: typeof AuthenticatedRequestsIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
  AuthenticatedTillIndexRoute: typeof AuthenticatedTillIndexRoute
  AuthenticatedInventoryHistoryCountsRoute: typeof AuthenticatedInventoryHistoryCountsRoute
  AuthenticatedInventoryHistoryPurchasesRoute: typeof AuthenticatedInventoryHistoryPurchasesRoute
  AuthenticatedInventoryHistoryTransfersRoute: typeof AuthenticatedInventoryHistoryTransfersRoute
  AuthenticatedInventoryHistoryIndexRoute: typeof AuthenticatedInventoryHistoryIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedFinanceExpensesRoute: AuthenticatedFinanceExpensesRoute,
  AuthenticatedFinancePartnersRoute: AuthenticatedFinancePartnersRoute,
  AuthenticatedFinanceProfitRoute: AuthenticatedFinanceProfitRoute,
  AuthenticatedFinanceSuppliersRoute: AuthenticatedFinanceSuppliersRoute,
  AuthenticatedInventoryMenuCostRoute: AuthenticatedInventoryMenuCostRoute,
  AuthenticatedInventoryReportsRoute: AuthenticatedInventoryReportsRoute,
  AuthenticatedOrdersHistoryRoute: AuthenticatedOrdersHistoryRoute,
  AuthenticatedPayrollAttendanceRoute: AuthenticatedPayrollAttendanceRoute,
  AuthenticatedPayrollEmployeesRoute: AuthenticatedPayrollEmployeesRoute,
  AuthenticatedPayrollPayslipsRoute: AuthenticatedPayrollPayslipsRoute,
  AuthenticatedPlacesHistoryRoute: AuthenticatedPlacesHistoryRoute,
  AuthenticatedPlacesPrintRoute: AuthenticatedPlacesPrintRoute,
  AuthenticatedPlacesReservationsRoute: AuthenticatedPlacesReservationsRoute,
  AuthenticatedTillBreakdownRoute: AuthenticatedTillBreakdownRoute,
  AuthenticatedTillPaymentsRoute: AuthenticatedTillPaymentsRoute,
  AuthenticatedTillRefundsRoute: AuthenticatedTillRefundsRoute,
  AuthenticatedTillShiftsRoute: AuthenticatedTillShiftsRoute,
  AuthenticatedTillTicketsRoute: AuthenticatedTillTicketsRoute,
  AuthenticatedAccountsIndexRoute: AuthenticatedAccountsIndexRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedAssistantIndexRoute: AuthenticatedAssistantIndexRoute,
  AuthenticatedBillsIndexRoute: AuthenticatedBillsIndexRoute,
  AuthenticatedBranchesIndexRoute: AuthenticatedBranchesIndexRoute,
  AuthenticatedBrandIndexRoute: AuthenticatedBrandIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedInventoryIndexRoute: AuthenticatedInventoryIndexRoute,
  AuthenticatedLoyaltyIndexRoute: AuthenticatedLoyaltyIndexRoute,
  AuthenticatedMenuIndexRoute: AuthenticatedMenuIndexRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
  AuthenticatedPaymentsIndexRoute: AuthenticatedPaymentsIndexRoute,
  AuthenticatedPlacesIndexRoute: AuthenticatedPlacesIndexRoute,
  AuthenticatedPromosIndexRoute: AuthenticatedPromosIndexRoute,
  AuthenticatedRequestsIndexRoute: AuthenticatedRequestsIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
  AuthenticatedTillIndexRoute: AuthenticatedTillIndexRoute,
  AuthenticatedInventoryHistoryCountsRoute:
    AuthenticatedInventoryHistoryCountsRoute,
  AuthenticatedInventoryHistoryPurchasesRoute:
    AuthenticatedInventoryHistoryPurchasesRoute,
  AuthenticatedInventoryHistoryTransfersRoute:
    AuthenticatedInventoryHistoryTransfersRoute,
  AuthenticatedInventoryHistoryIndexRoute:
    AuthenticatedInventoryHistoryIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  authSignedOutRoute: authSignedOutRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
