// <auto-generated />
using System;
using Chillax.Branch.API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Chillax.Branch.API.Migrations
{
    [DbContext(typeof(BranchContext))]
    [Migration("20260915233255_BranchReceiptHeader")]
    partial class BranchReceiptHeader
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Chillax.Branch.API.Model.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("DayEndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("DayStartTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOrderingEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReservationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("IsActive");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("Chillax.Branch.API.Model.Branch", b =>
                {
                    b.OwnsOne("Chillax.Branch.API.Model.LocalizedText", "Address", b1 =>
                        {
                            b1.Property<int>("BranchId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("BranchId");

                            b1.ToTable("Branches");

                            b1.ToJson("Address");

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.OwnsOne("Chillax.Branch.API.Model.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<int>("BranchId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("BranchId");

                            b1.ToTable("Branches");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.OwnsOne("Chillax.Branch.API.Model.LocalizedText", "ReceiptFooter", b1 =>
                        {
                            b1.Property<int>("BranchId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("BranchId");

                            b1.ToTable("Branches");

                            b1.ToJson("ReceiptFooter");

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("ReceiptFooter");
                });
#pragma warning restore 612, 618
        }
    }
}
