// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ninja.Branch.API.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ninja.Branch.API.Migrations
{
    [DbContext(typeof(BranchContext))]
    partial class BranchContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ninja.Branch.API.Model.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("DayEndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("DayStartTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOrderingEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReservationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("RequireSignInForTableOrders")
                        .HasColumnType("boolean");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("IsActive");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("Ninja.Branch.API.Model.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("CustomerUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<bool>("FinanceEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("FinanceEntitled")
                        .HasColumnType("boolean");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("InventoryEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("InventoryEntitled")
                        .HasColumnType("boolean");

                    b.Property<bool>("KdsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("KdsEntitled")
                        .HasColumnType("boolean");

                    b.Property<bool>("LoyaltyEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("LoyaltyEntitled")
                        .HasColumnType("boolean");

                    b.Property<bool>("PayrollEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("PayrollEntitled")
                        .HasColumnType("boolean");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<bool>("ReservationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReservationsEntitled")
                        .HasColumnType("boolean");

                    b.Property<bool>("TabsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("TabsEntitled")
                        .HasColumnType("boolean");

                    b.Property<bool>("TimeBillingEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("TimeBillingEntitled")
                        .HasColumnType("boolean");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Ninja.Branch.API.Model.Branch", b =>
                {
                    b.OwnsOne("Ninja.Branch.API.Model.LocalizedText", "Address", b1 =>
                        {
                            b1.Property<int>("BranchId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("BranchId");

                            b1.ToTable("Branches");

                            b1.ToJson("Address");

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.OwnsOne("Ninja.Branch.API.Model.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<int>("BranchId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("BranchId");

                            b1.ToTable("Branches");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.OwnsOne("Ninja.Branch.API.Model.LocalizedText", "ReceiptFooter", b1 =>
                        {
                            b1.Property<int>("BranchId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("BranchId");

                            b1.ToTable("Branches");

                            b1.ToJson("ReceiptFooter");

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("ReceiptFooter");
                });

            modelBuilder.Entity("Ninja.Branch.API.Model.Tenant", b =>
                {
                    b.OwnsOne("Ninja.Branch.API.Model.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<int>("TenantId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("TenantId");

                            b1.ToTable("Tenants");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.OwnsOne("Ninja.Branch.API.Model.TenantTheme", "Theme", b1 =>
                        {
                            b1.Property<int>("TenantId");

                            b1.Property<string>("Accent");

                            b1.Property<string>("FontArabic");

                            b1.Property<string>("FontLatin");

                            b1.Property<string>("HeaderSize");

                            b1.Property<string>("Radius");

                            b1.Property<string>("Surface");

                            b1.HasKey("TenantId");

                            b1.ToTable("Tenants");

                            b1.ToJson("Theme");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");

                            b1.OwnsOne("Ninja.Branch.API.Model.TenantThemeDark", "Dark", b2 =>
                                {
                                    b2.Property<int>("TenantThemeTenantId");

                                    b2.Property<string>("Accent");

                                    b2.Property<string>("Primary");

                                    b2.Property<string>("Surface");

                                    b2.HasKey("TenantThemeTenantId");

                                    b2.ToTable("Tenants");

                                    b2.WithOwner()
                                        .HasForeignKey("TenantThemeTenantId");
                                });

                            b1.Navigation("Dark");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Theme")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
