// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { assignOrderCustomer, cancelOrder, claimGuestOrders, confirmOrder, createOrder, createOrderDraft, createPosOrder, deleteOrder, getAllOrders, getKitchenOrders, getOpenOrdersAtPlace, getOrder, getOrdersByUser, getOrdersByUserId, getOrderStats, getPendingOrders, type Options, rateOrder, rejectGuestOrder, setOrderReady } from '../sdk.gen';
import type { AssignOrderCustomerData, AssignOrderCustomerError, AssignOrderCustomerResponse, CancelOrderData, CancelOrderError, ClaimGuestOrdersData, ClaimGuestOrdersError, ClaimGuestOrdersResponse2, ConfirmOrderData, ConfirmOrderError, CreateOrderData, CreateOrderDraftData, CreateOrderDraftResponse, CreateOrderError, CreatePosOrderData, CreatePosOrderError, CreatePosOrderResponse, DeleteOrderData, DeleteOrderResponse, GetAllOrdersData, GetAllOrdersResponse, GetKitchenOrdersData, GetKitchenOrdersResponse, GetOpenOrdersAtPlaceData, GetOpenOrdersAtPlaceResponse, GetOrderData, GetOrderResponse, GetOrdersByUserData, GetOrdersByUserIdData, GetOrdersByUserIdResponse, GetOrdersByUserResponse, GetOrderStatsData, GetOrderStatsResponse, GetPendingOrdersData, GetPendingOrdersResponse, RateOrderData, RateOrderError, RejectGuestOrderData, RejectGuestOrderError, RejectGuestOrderResponse, SetOrderReadyData, SetOrderReadyError, SetOrderReadyResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getOrdersByUserQueryKey = (options: Options<GetOrdersByUserData>) => createQueryKey('getOrdersByUser', options);

/**
 * Get current user's orders
 *
 * Returns the signed-in customer's orders, or — for an anonymous caller — the orders placed with the X-Guest-Id they send.
 */
export const getOrdersByUserOptions = (options: Options<GetOrdersByUserData>) => queryOptions<GetOrdersByUserResponse, AxiosError<DefaultError>, GetOrdersByUserResponse, ReturnType<typeof getOrdersByUserQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getOrdersByUser({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getOrdersByUserQueryKey(options)
});

/**
 * Create a new cafe order
 *
 * Signed-in customers are identified by their token. A guest may order without an account by sending X-Guest-Id plus a name and phone number.
 */
export const createOrderMutation = (options?: Partial<Options<CreateOrderData>>): UseMutationOptions<unknown, AxiosError<CreateOrderError>, Options<CreateOrderData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<CreateOrderError>, Options<CreateOrderData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createOrder({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create a counter (POS) order (staff)
 *
 * A walk-in sale keyed in by staff. Optionally attached to a customer account for loyalty. Auto-confirms after stock validation.
 */
export const createPosOrderMutation = (options?: Partial<Options<CreatePosOrderData>>): UseMutationOptions<CreatePosOrderResponse, AxiosError<CreatePosOrderError>, Options<CreatePosOrderData>> => {
    const mutationOptions: UseMutationOptions<CreatePosOrderResponse, AxiosError<CreatePosOrderError>, Options<CreatePosOrderData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createPosOrder({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Confirm a submitted order (staff) - lands it on the ticket
 */
export const confirmOrderMutation = (options?: Partial<Options<ConfirmOrderData>>): UseMutationOptions<unknown, AxiosError<ConfirmOrderError>, Options<ConfirmOrderData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<ConfirmOrderError>, Options<ConfirmOrderData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await confirmOrder({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Cancel a submitted order (staff)
 */
export const cancelOrderMutation = (options?: Partial<Options<CancelOrderData>>): UseMutationOptions<unknown, AxiosError<CancelOrderError>, Options<CancelOrderData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<CancelOrderError>, Options<CancelOrderData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await cancelOrder({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Cancel a guest's order and block their device for the day (staff)
 *
 * For an order placed as a guest: cancels it and refuses further orders from the same X-Guest-Id at this branch for 24 hours. Nothing happens to an account holder's order.
 */
export const rejectGuestOrderMutation = (options?: Partial<Options<RejectGuestOrderData>>): UseMutationOptions<RejectGuestOrderResponse, AxiosError<RejectGuestOrderError>, Options<RejectGuestOrderData>> => {
    const mutationOptions: UseMutationOptions<RejectGuestOrderResponse, AxiosError<RejectGuestOrderError>, Options<RejectGuestOrderData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await rejectGuestOrder({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Assign a customer to an order after the fact (staff)
 *
 * Puts an account holder or a bare name on an order placed without one, or moves an order from one account to another — Loyalty moves the points with it. Refused once the order is cancelled, when it already belongs to that account, or when it would drop an account for a bare name.
 */
export const assignOrderCustomerMutation = (options?: Partial<Options<AssignOrderCustomerData>>): UseMutationOptions<AssignOrderCustomerResponse, AxiosError<AssignOrderCustomerError>, Options<AssignOrderCustomerData>> => {
    const mutationOptions: UseMutationOptions<AssignOrderCustomerResponse, AxiosError<AssignOrderCustomerError>, Options<AssignOrderCustomerData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await assignOrderCustomer({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Claim the orders a guest device placed for the signed-in account
 *
 * For a guest who just signed in: every order placed under the given X-Guest-Id that no account holds yet is assigned to the caller, as the till's assign-customer does. Cancelled orders stay behind. Returns how many were claimed; safe to repeat.
 */
export const claimGuestOrdersMutation = (options?: Partial<Options<ClaimGuestOrdersData>>): UseMutationOptions<ClaimGuestOrdersResponse2, AxiosError<ClaimGuestOrdersError>, Options<ClaimGuestOrdersData>> => {
    const mutationOptions: UseMutationOptions<ClaimGuestOrdersResponse2, AxiosError<ClaimGuestOrdersError>, Options<ClaimGuestOrdersData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await claimGuestOrders({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a cancelled order (admin)
 *
 * Permanently removes an order. Only cancelled orders can be deleted.
 */
export const deleteOrderMutation = (options?: Partial<Options<DeleteOrderData>>): UseMutationOptions<DeleteOrderResponse, AxiosError<DefaultError>, Options<DeleteOrderData>> => {
    const mutationOptions: UseMutationOptions<DeleteOrderResponse, AxiosError<DefaultError>, Options<DeleteOrderData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteOrder({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getOrderQueryKey = (options: Options<GetOrderData>) => createQueryKey('getOrder', options);

/**
 * Get order by ID
 *
 * Readable by an admin, the customer who placed it, or the guest whose X-Guest-Id matches.
 */
export const getOrderOptions = (options: Options<GetOrderData>) => queryOptions<GetOrderResponse, AxiosError<DefaultError>, GetOrderResponse, ReturnType<typeof getOrderQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getOrder({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getOrderQueryKey(options)
});

/**
 * Rate a confirmed order
 */
export const rateOrderMutation = (options?: Partial<Options<RateOrderData>>): UseMutationOptions<unknown, AxiosError<RateOrderError>, Options<RateOrderData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<RateOrderError>, Options<RateOrderData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await rateOrder({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getOpenOrdersAtPlaceQueryKey = (options: Options<GetOpenOrdersAtPlaceData>) => createQueryKey('getOpenOrdersAtPlace', options);

/**
 * Open orders at a place, for the people sitting there
 *
 * Every order at the place still waiting for its bill, with lines and a flag on the caller's own — but only for a caller who has an unpaid order there themselves; anyone else gets an empty list. No contact details. The bill being paid is what ends a sitting; no clock does.
 */
export const getOpenOrdersAtPlaceOptions = (options: Options<GetOpenOrdersAtPlaceData>) => queryOptions<GetOpenOrdersAtPlaceResponse, AxiosError<DefaultError>, GetOpenOrdersAtPlaceResponse, ReturnType<typeof getOpenOrdersAtPlaceQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getOpenOrdersAtPlace({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getOpenOrdersAtPlaceQueryKey(options)
});

export const getPendingOrdersQueryKey = (options: Options<GetPendingOrdersData>) => createQueryKey('getPendingOrders', options);

/**
 * Pending orders for the branch (staff)
 */
export const getPendingOrdersOptions = (options: Options<GetPendingOrdersData>) => queryOptions<GetPendingOrdersResponse, AxiosError<DefaultError>, GetPendingOrdersResponse, ReturnType<typeof getPendingOrdersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPendingOrders({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPendingOrdersQueryKey(options)
});

export const getKitchenOrdersQueryKey = (options: Options<GetKitchenOrdersData>) => createQueryKey('getKitchenOrders', options);

/**
 * Confirmed orders in the kitchen, for the kitchen display (staff)
 *
 * Orders confirmed in the last day, ready or not; the screen shows the open ones on the board and the ready ones in its history. Kitchen-only state; customers never see it.
 */
export const getKitchenOrdersOptions = (options: Options<GetKitchenOrdersData>) => queryOptions<GetKitchenOrdersResponse, AxiosError<DefaultError>, GetKitchenOrdersResponse, ReturnType<typeof getKitchenOrdersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getKitchenOrders({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getKitchenOrdersQueryKey(options)
});

/**
 * Mark a confirmed order ready in the kitchen, or bring it back (staff)
 *
 * Ready true when it is done, false to bring a ready order back to the board. Repeating the current state is a no-op. Never shown to the customer.
 */
export const setOrderReadyMutation = (options?: Partial<Options<SetOrderReadyData>>): UseMutationOptions<SetOrderReadyResponse, AxiosError<SetOrderReadyError>, Options<SetOrderReadyData>> => {
    const mutationOptions: UseMutationOptions<SetOrderReadyResponse, AxiosError<SetOrderReadyError>, Options<SetOrderReadyData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await setOrderReady({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getAllOrdersQueryKey = (options: Options<GetAllOrdersData>) => createQueryKey('getAllOrders', options);

/**
 * Get all orders paginated (admin)
 */
export const getAllOrdersOptions = (options: Options<GetAllOrdersData>) => queryOptions<GetAllOrdersResponse, AxiosError<DefaultError>, GetAllOrdersResponse, ReturnType<typeof getAllOrdersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAllOrders({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAllOrdersQueryKey(options)
});

export const getOrderStatsQueryKey = (options: Options<GetOrderStatsData>) => createQueryKey('getOrderStats', options);

/**
 * Get aggregated order statistics (admin)
 *
 * Per-day order counts/revenue and top items over a date range, excluding cancelled orders.
 */
export const getOrderStatsOptions = (options: Options<GetOrderStatsData>) => queryOptions<GetOrderStatsResponse, AxiosError<DefaultError>, GetOrderStatsResponse, ReturnType<typeof getOrderStatsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getOrderStats({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getOrderStatsQueryKey(options)
});

export const getOrdersByUserIdQueryKey = (options: Options<GetOrdersByUserIdData>) => createQueryKey('getOrdersByUserId', options);

/**
 * Get orders for a specific user (admin)
 */
export const getOrdersByUserIdOptions = (options: Options<GetOrdersByUserIdData>) => queryOptions<GetOrdersByUserIdResponse, AxiosError<DefaultError>, GetOrdersByUserIdResponse, ReturnType<typeof getOrdersByUserIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getOrdersByUserId({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getOrdersByUserIdQueryKey(options)
});

/**
 * Create order draft from basket
 */
export const createOrderDraftMutation = (options?: Partial<Options<CreateOrderDraftData>>): UseMutationOptions<CreateOrderDraftResponse, AxiosError<DefaultError>, Options<CreateOrderDraftData>> => {
    const mutationOptions: UseMutationOptions<CreateOrderDraftResponse, AxiosError<DefaultError>, Options<CreateOrderDraftData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createOrderDraft({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
