// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

export type AssignOrderCustomerRequest = {
    customerUserId: null | string;
    customerName: string;
};

export type BasketItem = {
    id?: string;
    productId?: number | string;
    productName?: LocalizedText;
    unitPrice?: number | string;
    oldUnitPrice?: number | string;
    quantity?: number | string;
    pictureUrl?: null | string;
    specialInstructions?: null | string;
    selectedCustomizations?: Array<BasketItemCustomization>;
    totalPrice?: number | string;
};

export type BasketItemCustomization = {
    customizationId?: number | string;
    customizationName?: LocalizedText;
    optionId?: number | string;
    optionName?: LocalizedText;
    priceAdjustment?: number | string;
};

export type CancelOrderCommand = {
    orderNumber: number | string;
};

export type ConfirmOrderCommand = {
    orderNumber: number | string;
};

export type CreateOrderDraftCommand = {
    buyerId: null | string;
    items: null | Array<BasketItem>;
};

export type CreateOrderRequest = {
    userId: string;
    userName: string;
    roomName: null | LocalizedText;
    customerNote: null | string;
    pointsToRedeem: number | string;
    loyaltyDiscount: number | string;
    items: Array<BasketItem>;
    tableId?: null | number | string;
    tableName?: null | LocalizedText;
    guestName?: null | string;
    guestPhone?: null | string;
    sessionId?: null | number | string;
    roomId?: null | number | string;
};

export type KitchenOrder = {
    orderNumber?: number | string;
    date?: string;
    confirmedAt?: null | string;
    preparation?: string;
    preparingAt?: null | string;
    readyAt?: null | string;
    source?: string;
    roomName?: null | LocalizedText;
    tableName?: null | LocalizedText;
    customerName?: null | string;
    customerNote?: null | string;
    items?: Array<KitchenOrderItem>;
};

export type KitchenOrderItem = {
    productName?: LocalizedText;
    units?: number | string;
    customizationsDescription?: null | LocalizedText;
    specialInstructions?: null | string;
};

export type LocalizedText = {
    en?: string;
    ar?: null | string;
};

export type Order = {
    orderNumber?: number | string;
    date?: string;
    status?: string;
    description?: null | string;
    roomName?: null | LocalizedText;
    sessionId?: null | number | string;
    roomId?: null | number | string;
    source?: string;
    tableId?: null | number | string;
    tableName?: null | LocalizedText;
    customerNote?: null | string;
    guestName?: null | string;
    guestPhone?: null | string;
    orderItems?: Array<Orderitem>;
    total?: number | string;
    pointsToRedeem?: number | string;
    loyaltyDiscount?: number | string;
    rating?: null | OrderRatingDto;
};

export type OrderDraftDto = {
    orderItems?: Array<OrderItemDto>;
    total?: number | string;
};

export type Orderitem = {
    productName?: LocalizedText;
    units?: number | string;
    unitPrice?: number | string;
    pictureUrl?: null | string;
    customizationsDescription?: null | LocalizedText;
    specialInstructions?: null | string;
};

export type OrderItemDto = {
    productId?: number | string;
    productName?: LocalizedText;
    unitPrice?: number | string;
    discount?: number | string;
    units?: number | string;
    pictureUrl?: null | string;
    specialInstructions?: null | string;
    customizationsDescription?: null | LocalizedText;
};

export type OrderRatingDto = {
    ratingValue?: number | string;
    comment?: null | string;
    createdAt?: string;
};

export type OrderStats = {
    days?: Array<OrderStatsDay>;
    topItems?: Array<OrderStatsItem>;
};

export type OrderStatsDay = {
    date?: string;
    orders?: number | string;
    revenue?: number | string;
};

export type OrderStatsItem = {
    productName?: LocalizedText;
    units?: number | string;
    revenue?: number | string;
};

export type OrderSummary = {
    orderNumber?: number | string;
    date?: string;
    status?: string;
    total?: number | string;
    pointsToRedeem?: number | string;
    loyaltyDiscount?: number | string;
    roomName?: null | LocalizedText;
    sessionId?: null | number | string;
    source?: string;
    tableId?: null | number | string;
    tableName?: null | LocalizedText;
    userName?: null | string;
    userId?: null | string;
    guestPhone?: null | string;
    ratingValue?: null | number | string;
};

export type PaginatedResultOfOrderSummary = {
    items?: Array<OrderSummary>;
    pageIndex?: number | string;
    pageSize?: number | string;
    totalCount?: number | string;
    totalPages?: number | string;
    hasNextPage?: boolean;
    hasPreviousPage?: boolean;
};

export type PosOrderRequest = {
    items: Array<BasketItem>;
    customerNote?: null | string;
    tableId?: null | number | string;
    tableName?: null | LocalizedText;
    roomName?: null | LocalizedText;
    customerUserId?: null | string;
    customerUserName?: null | string;
    pointsToRedeem?: number | string;
    ticketId?: null | number | string;
    customerName?: null | string;
    placedAt?: null | string;
    replay?: boolean;
};

export type PosOrderResponse = {
    orderId: number | string;
};

export type PreparationStatus = 'NotStarted' | 'Preparing' | 'Ready';

export type RateOrderRequest = {
    ratingValue: number | string;
    comment: null | string;
};

export type SetOrderPreparationRequest = {
    preparation: PreparationStatus;
};

export type GetOrdersByUserData = {
    body?: never;
    path?: never;
    query: {
        pageIndex?: number | string;
        pageSize?: number | string;
        fromDate?: string;
        toDate?: string;
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/orders';
};

export type GetOrdersByUserErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetOrdersByUserResponses = {
    /**
     * OK
     */
    200: PaginatedResultOfOrderSummary;
};

export type GetOrdersByUserResponse = GetOrdersByUserResponses[keyof GetOrdersByUserResponses];

export type CreateOrderData = {
    body: CreateOrderRequest;
    headers: {
        'x-requestid': string;
    };
    path?: never;
    query: {
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/orders';
};

export type CreateOrderErrors = {
    /**
     * Bad Request
     */
    400: string;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type CreateOrderError = CreateOrderErrors[keyof CreateOrderErrors];

export type CreateOrderResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type CreatePosOrderData = {
    body: PosOrderRequest;
    headers: {
        'x-requestid': string;
    };
    path?: never;
    query: {
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/orders/pos';
};

export type CreatePosOrderErrors = {
    /**
     * Bad Request
     */
    400: string;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type CreatePosOrderError = CreatePosOrderErrors[keyof CreatePosOrderErrors];

export type CreatePosOrderResponses = {
    /**
     * OK
     */
    200: PosOrderResponse;
};

export type CreatePosOrderResponse = CreatePosOrderResponses[keyof CreatePosOrderResponses];

export type ConfirmOrderData = {
    body: ConfirmOrderCommand;
    headers: {
        'x-requestid': string;
    };
    path?: never;
    query: {
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/orders/confirm';
};

export type ConfirmOrderErrors = {
    /**
     * Bad Request
     */
    400: string;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type ConfirmOrderError = ConfirmOrderErrors[keyof ConfirmOrderErrors];

export type ConfirmOrderResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type CancelOrderData = {
    body: CancelOrderCommand;
    headers: {
        'x-requestid': string;
    };
    path?: never;
    query: {
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/orders/cancel';
};

export type CancelOrderErrors = {
    /**
     * Bad Request
     */
    400: string;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type CancelOrderError = CancelOrderErrors[keyof CancelOrderErrors];

export type CancelOrderResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type AssignOrderCustomerData = {
    body: AssignOrderCustomerRequest;
    headers: {
        'x-requestid': string;
    };
    path: {
        orderId: number;
    };
    query: {
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/orders/{orderId}/customer';
};

export type AssignOrderCustomerErrors = {
    /**
     * Bad Request
     */
    400: string;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type AssignOrderCustomerError = AssignOrderCustomerErrors[keyof AssignOrderCustomerErrors];

export type AssignOrderCustomerResponses = {
    /**
     * No Content
     */
    204: void;
};

export type AssignOrderCustomerResponse = AssignOrderCustomerResponses[keyof AssignOrderCustomerResponses];

export type DeleteOrderData = {
    body?: never;
    path: {
        orderId: number;
    };
    query: {
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/orders/{orderId}';
};

export type DeleteOrderErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type DeleteOrderResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteOrderResponse = DeleteOrderResponses[keyof DeleteOrderResponses];

export type GetOrderData = {
    body?: never;
    path: {
        orderId: number;
    };
    query: {
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/orders/{orderId}';
};

export type GetOrderErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetOrderResponses = {
    /**
     * OK
     */
    200: Order;
};

export type GetOrderResponse = GetOrderResponses[keyof GetOrderResponses];

export type RateOrderData = {
    body: RateOrderRequest;
    headers: {
        'x-requestid': string;
    };
    path: {
        orderId: number;
    };
    query: {
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/orders/{orderId}/rating';
};

export type RateOrderErrors = {
    /**
     * Bad Request
     */
    400: string;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type RateOrderError = RateOrderErrors[keyof RateOrderErrors];

export type RateOrderResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetPendingOrdersData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/orders/pending';
};

export type GetPendingOrdersErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetPendingOrdersResponses = {
    /**
     * OK
     */
    200: Array<OrderSummary>;
};

export type GetPendingOrdersResponse = GetPendingOrdersResponses[keyof GetPendingOrdersResponses];

export type GetKitchenOrdersData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/orders/kitchen';
};

export type GetKitchenOrdersErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetKitchenOrdersResponses = {
    /**
     * OK
     */
    200: Array<KitchenOrder>;
};

export type GetKitchenOrdersResponse = GetKitchenOrdersResponses[keyof GetKitchenOrdersResponses];

export type SetOrderPreparationData = {
    body: SetOrderPreparationRequest;
    headers: {
        'x-requestid': string;
    };
    path: {
        orderId: number;
    };
    query: {
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/orders/{orderId}/preparation';
};

export type SetOrderPreparationErrors = {
    /**
     * Bad Request
     */
    400: string;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type SetOrderPreparationError = SetOrderPreparationErrors[keyof SetOrderPreparationErrors];

export type SetOrderPreparationResponses = {
    /**
     * No Content
     */
    204: void;
};

export type SetOrderPreparationResponse = SetOrderPreparationResponses[keyof SetOrderPreparationResponses];

export type GetAllOrdersData = {
    body?: never;
    path?: never;
    query: {
        pageIndex?: number | string;
        pageSize?: number | string;
        status?: string;
        buyerId?: string;
        fromDate?: string;
        toDate?: string;
        sessionId?: number | string;
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/orders/all';
};

export type GetAllOrdersErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetAllOrdersResponses = {
    /**
     * OK
     */
    200: PaginatedResultOfOrderSummary;
};

export type GetAllOrdersResponse = GetAllOrdersResponses[keyof GetAllOrdersResponses];

export type GetOrderStatsData = {
    body?: never;
    path?: never;
    query: {
        fromDate: string;
        toDate: string;
        tzOffsetMinutes?: number | string;
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/orders/stats';
};

export type GetOrderStatsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetOrderStatsResponses = {
    /**
     * OK
     */
    200: OrderStats;
};

export type GetOrderStatsResponse = GetOrderStatsResponses[keyof GetOrderStatsResponses];

export type GetOrdersByUserIdData = {
    body?: never;
    path: {
        userId: string;
    };
    query: {
        pageIndex?: number | string;
        pageSize?: number | string;
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/orders/user/{userId}';
};

export type GetOrdersByUserIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetOrdersByUserIdResponses = {
    /**
     * OK
     */
    200: PaginatedResultOfOrderSummary;
};

export type GetOrdersByUserIdResponse = GetOrdersByUserIdResponses[keyof GetOrdersByUserIdResponses];

export type CreateOrderDraftData = {
    body: CreateOrderDraftCommand;
    path?: never;
    query: {
        /**
         * The API version, in the format 'major.minor'.
         */
        'api-version': string;
    };
    url: '/api/orders/draft';
};

export type CreateOrderDraftErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type CreateOrderDraftResponses = {
    /**
     * OK
     */
    200: OrderDraftDto;
};

export type CreateOrderDraftResponse = CreateOrderDraftResponses[keyof CreateOrderDraftResponses];
