// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { addMemberToSession, assignCustomerToSession, cancelMyReservation, cancelSession, changePlayerMode, createRoom, deleteRoom, endSession, getActiveSessions, getAvailableRooms, getMySessions, getRoom, getRoomSessionHistory, getSession, getSessionHistory, joinSessionByRoom, leaveSession, listRooms, type Options, removeMemberFromSession, reserveRoom, scanRoom, startSession, startWalkInSession, updateRoom, updateRoomStatus } from '../sdk.gen';
import type { AddMemberToSessionData, AddMemberToSessionError, AssignCustomerToSessionData, AssignCustomerToSessionError, CancelMyReservationData, CancelMyReservationError, CancelSessionData, CancelSessionError, ChangePlayerModeData, ChangePlayerModeError, CreateRoomData, CreateRoomResponse, DeleteRoomData, DeleteRoomError, EndSessionData, EndSessionError, GetActiveSessionsData, GetActiveSessionsResponse, GetAvailableRoomsData, GetAvailableRoomsResponse, GetMySessionsData, GetMySessionsResponse, GetRoomData, GetRoomResponse, GetRoomSessionHistoryData, GetRoomSessionHistoryResponse, GetSessionData, GetSessionHistoryData, GetSessionHistoryResponse, GetSessionResponse, JoinSessionByRoomData, JoinSessionByRoomError, JoinSessionByRoomResponse, LeaveSessionData, LeaveSessionError, ListRoomsData, ListRoomsResponse, RemoveMemberFromSessionData, RemoveMemberFromSessionError, ReserveRoomData, ReserveRoomError, ReserveRoomResponse, ScanRoomData, ScanRoomResponse, StartSessionData, StartSessionError, StartWalkInSessionData, StartWalkInSessionError, StartWalkInSessionResponse, UpdateRoomData, UpdateRoomStatusData, UpdateRoomStatusError } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const listRoomsQueryKey = (options?: Options<ListRoomsData>) => createQueryKey('listRooms', options);

/**
 * List all rooms
 *
 * Get all PlayStation rooms with their current display status
 */
export const listRoomsOptions = (options?: Options<ListRoomsData>) => queryOptions<ListRoomsResponse, AxiosError<DefaultError>, ListRoomsResponse, ReturnType<typeof listRoomsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listRooms({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listRoomsQueryKey(options)
});

/**
 * Create a new room
 *
 * Create a new PlayStation room (Admin only)
 */
export const createRoomMutation = (options?: Partial<Options<CreateRoomData>>): UseMutationOptions<CreateRoomResponse, AxiosError<DefaultError>, Options<CreateRoomData>> => {
    const mutationOptions: UseMutationOptions<CreateRoomResponse, AxiosError<DefaultError>, Options<CreateRoomData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createRoom({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a room
 *
 * Delete a room (Admin only)
 */
export const deleteRoomMutation = (options?: Partial<Options<DeleteRoomData>>): UseMutationOptions<unknown, AxiosError<DeleteRoomError>, Options<DeleteRoomData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DeleteRoomError>, Options<DeleteRoomData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteRoom({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getRoomQueryKey = (options: Options<GetRoomData>) => createQueryKey('getRoom', options);

/**
 * Get room by ID
 *
 * Get a specific room by its ID
 */
export const getRoomOptions = (options: Options<GetRoomData>) => queryOptions<GetRoomResponse, AxiosError<DefaultError>, GetRoomResponse, ReturnType<typeof getRoomQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRoom({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRoomQueryKey(options)
});

/**
 * Update room details
 *
 * Update room name, description, and rates (Admin only)
 */
export const updateRoomMutation = (options?: Partial<Options<UpdateRoomData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<UpdateRoomData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<UpdateRoomData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateRoom({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getAvailableRoomsQueryKey = (options?: Options<GetAvailableRoomsData>) => createQueryKey('getAvailableRooms', options);

/**
 * Get available rooms
 *
 * Get only rooms that are currently available for reservation
 */
export const getAvailableRoomsOptions = (options?: Options<GetAvailableRoomsData>) => queryOptions<GetAvailableRoomsResponse, AxiosError<DefaultError>, GetAvailableRoomsResponse, ReturnType<typeof getAvailableRoomsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAvailableRooms({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAvailableRoomsQueryKey(options)
});

/**
 * Update room physical status
 *
 * Update the physical status of a room (Admin only)
 */
export const updateRoomStatusMutation = (options?: Partial<Options<UpdateRoomStatusData>>): UseMutationOptions<unknown, AxiosError<UpdateRoomStatusError>, Options<UpdateRoomStatusData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<UpdateRoomStatusError>, Options<UpdateRoomStatusData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateRoomStatus({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Reserve a room
 *
 * Create an immediate reservation for a room. Customer has 15 minutes to arrive before auto-cancellation.
 */
export const reserveRoomMutation = (options?: Partial<Options<ReserveRoomData>>): UseMutationOptions<ReserveRoomResponse, AxiosError<ReserveRoomError>, Options<ReserveRoomData>> => {
    const mutationOptions: UseMutationOptions<ReserveRoomResponse, AxiosError<ReserveRoomError>, Options<ReserveRoomData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await reserveRoom({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Start a session
 *
 * Start the timer for a reserved session (Admin only)
 */
export const startSessionMutation = (options?: Partial<Options<StartSessionData>>): UseMutationOptions<unknown, AxiosError<StartSessionError>, Options<StartSessionData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<StartSessionError>, Options<StartSessionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await startSession({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * End a session
 *
 * End the session and calculate cost (Admin only)
 */
export const endSessionMutation = (options?: Partial<Options<EndSessionData>>): UseMutationOptions<unknown, AxiosError<EndSessionError>, Options<EndSessionData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<EndSessionError>, Options<EndSessionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await endSession({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Cancel a session
 *
 * Cancel a reservation or active session (Admin only)
 */
export const cancelSessionMutation = (options?: Partial<Options<CancelSessionData>>): UseMutationOptions<unknown, AxiosError<CancelSessionError>, Options<CancelSessionData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<CancelSessionError>, Options<CancelSessionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await cancelSession({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Start a walk-in session
 *
 * Start a walk-in session without an assigned customer (Admin only)
 */
export const startWalkInSessionMutation = (options?: Partial<Options<StartWalkInSessionData>>): UseMutationOptions<StartWalkInSessionResponse, AxiosError<StartWalkInSessionError>, Options<StartWalkInSessionData>> => {
    const mutationOptions: UseMutationOptions<StartWalkInSessionResponse, AxiosError<StartWalkInSessionError>, Options<StartWalkInSessionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await startWalkInSession({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Change player mode
 *
 * Change the player mode (Single/Multi) for an active session (Admin only)
 */
export const changePlayerModeMutation = (options?: Partial<Options<ChangePlayerModeData>>): UseMutationOptions<unknown, AxiosError<ChangePlayerModeError>, Options<ChangePlayerModeData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<ChangePlayerModeError>, Options<ChangePlayerModeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await changePlayerMode({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Leave a session
 *
 * Leave a session you've joined (cannot leave if you're the owner)
 */
export const leaveSessionMutation = (options?: Partial<Options<LeaveSessionData>>): UseMutationOptions<unknown, AxiosError<LeaveSessionError>, Options<LeaveSessionData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<LeaveSessionError>, Options<LeaveSessionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await leaveSession({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Cancel my reservation
 *
 * Cancel your own reservation (only if still in Reserved status)
 */
export const cancelMyReservationMutation = (options?: Partial<Options<CancelMyReservationData>>): UseMutationOptions<unknown, AxiosError<CancelMyReservationError>, Options<CancelMyReservationData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<CancelMyReservationError>, Options<CancelMyReservationData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await cancelMyReservation({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getMySessionsQueryKey = (options?: Options<GetMySessionsData>) => createQueryKey('getMySessions', options);

/**
 * Get my sessions
 *
 * Get all sessions for the current authenticated user
 */
export const getMySessionsOptions = (options?: Options<GetMySessionsData>) => queryOptions<GetMySessionsResponse, AxiosError<DefaultError>, GetMySessionsResponse, ReturnType<typeof getMySessionsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getMySessions({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getMySessionsQueryKey(options)
});

export const getActiveSessionsQueryKey = (options?: Options<GetActiveSessionsData>) => createQueryKey('getActiveSessions', options);

/**
 * Get active sessions
 *
 * Get all currently active sessions (Admin only)
 */
export const getActiveSessionsOptions = (options?: Options<GetActiveSessionsData>) => queryOptions<GetActiveSessionsResponse, AxiosError<DefaultError>, GetActiveSessionsResponse, ReturnType<typeof getActiveSessionsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getActiveSessions({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getActiveSessionsQueryKey(options)
});

/**
 * Assign a customer to a walk-in session
 *
 * Assign a customer to an active walk-in session that has no owner (Admin only)
 */
export const assignCustomerToSessionMutation = (options?: Partial<Options<AssignCustomerToSessionData>>): UseMutationOptions<unknown, AxiosError<AssignCustomerToSessionError>, Options<AssignCustomerToSessionData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<AssignCustomerToSessionError>, Options<AssignCustomerToSessionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await assignCustomerToSession({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Add a member to a session
 *
 * Add a customer as a member to an active session (Admin only)
 */
export const addMemberToSessionMutation = (options?: Partial<Options<AddMemberToSessionData>>): UseMutationOptions<unknown, AxiosError<AddMemberToSessionError>, Options<AddMemberToSessionData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<AddMemberToSessionError>, Options<AddMemberToSessionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await addMemberToSession({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Remove a member from a session
 *
 * Remove a non-owner member from an active session (Admin only)
 */
export const removeMemberFromSessionMutation = (options?: Partial<Options<RemoveMemberFromSessionData>>): UseMutationOptions<unknown, AxiosError<RemoveMemberFromSessionError>, Options<RemoveMemberFromSessionData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<RemoveMemberFromSessionError>, Options<RemoveMemberFromSessionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await removeMemberFromSession({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getSessionQueryKey = (options: Options<GetSessionData>) => createQueryKey('getSession', options);

/**
 * Get session by ID
 *
 * Get a specific session by its ID
 */
export const getSessionOptions = (options: Options<GetSessionData>) => queryOptions<GetSessionResponse, AxiosError<DefaultError>, GetSessionResponse, ReturnType<typeof getSessionQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSession({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSessionQueryKey(options)
});

export const getRoomSessionHistoryQueryKey = (options: Options<GetRoomSessionHistoryData>) => createQueryKey('getRoomSessionHistory', options);

/**
 * Get room session history
 *
 * Get completed sessions history for a specific room (Admin only)
 */
export const getRoomSessionHistoryOptions = (options: Options<GetRoomSessionHistoryData>) => queryOptions<GetRoomSessionHistoryResponse, AxiosError<DefaultError>, GetRoomSessionHistoryResponse, ReturnType<typeof getRoomSessionHistoryQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRoomSessionHistory({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRoomSessionHistoryQueryKey(options)
});

export const getSessionHistoryQueryKey = (options?: Options<GetSessionHistoryData>) => createQueryKey('getSessionHistory', options);

/**
 * Get session history
 *
 * Get completed/cancelled sessions across all rooms, paginated (Admin only)
 */
export const getSessionHistoryOptions = (options?: Options<GetSessionHistoryData>) => queryOptions<GetSessionHistoryResponse, AxiosError<DefaultError>, GetSessionHistoryResponse, ReturnType<typeof getSessionHistoryQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSessionHistory({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSessionHistoryQueryKey(options)
});

export const scanRoomQueryKey = (options: Options<ScanRoomData>) => createQueryKey('scanRoom', options);

/**
 * Get room scan info
 *
 * Get room info and active session status for QR code scan-to-join
 */
export const scanRoomOptions = (options: Options<ScanRoomData>) => queryOptions<ScanRoomResponse, AxiosError<DefaultError>, ScanRoomResponse, ReturnType<typeof scanRoomQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await scanRoom({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: scanRoomQueryKey(options)
});

/**
 * Join session by room
 *
 * Join the active session of a room (via QR scan)
 */
export const joinSessionByRoomMutation = (options?: Partial<Options<JoinSessionByRoomData>>): UseMutationOptions<JoinSessionByRoomResponse, AxiosError<JoinSessionByRoomError>, Options<JoinSessionByRoomData>> => {
    const mutationOptions: UseMutationOptions<JoinSessionByRoomResponse, AxiosError<JoinSessionByRoomError>, Options<JoinSessionByRoomData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await joinSessionByRoom({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
